//! Official Flow releases, verified against their published npm integrity.
use anyhow::{Context, Result, ensure};
use camino::{Utf8Path, Utf8PathBuf};
use std::{collections::BTreeMap, fs, process::Command};
use uf_config::UniflowedConfig;

pub(super) const CONFIG_NAME: &str = ".uf-flowconfig";
const HEADER: &str = "# Generated by uf. Edit .flowconfig or uf.config.js instead.\n";

pub(super) fn acquire(version: &str) -> Result<Utf8PathBuf> {
    let store = uf_env::Store::discover()?;
    let directory = store
        .root()
        .parent()
        .context("missing data directory")?
        .join("flow")
        .join(version);
    let binary = directory.join(if cfg!(windows) { "flow.exe" } else { "flow" });
    let _guard = uf_env::lock::guard(&directory.with_extension("lock"))?;
    if !binary.is_file() {
        let parent = directory.parent().context("missing cache parent")?;
        fs::create_dir_all(parent)?;
        let staging = tempfile::tempdir_in(parent)?;
        let staged = Utf8Path::from_path(staging.path()).context("non UTF-8 staging path")?;
        let base = uf_infra::cstr!("https://registry.npmjs.org/flow-bin");
        let source = uf_env::source::Source {
            archive: uf_infra::into_string(uf_infra::cstr!("{base}/-/flow-bin-{version}.tgz")),
            checksum: uf_env::source::Checksum::NpmIntegrity {
                url: uf_infra::into_string(uf_infra::cstr!("{base}/{version}")),
            },
            format: uf_env::source::Format::TarGz,
            strip: 1,
        };
        uf_env::archive::install(&source, staged)?;
        let platform = match (std::env::consts::OS, std::env::consts::ARCH) {
            ("macos", "aarch64") => "osx-arm64",
            ("macos", "x86_64") => "osx",
            ("linux", "aarch64") => "linux-arm64",
            ("linux", "x86_64") => "linux64",
            ("windows", "x86_64") => "win64",
            _ => anyhow::bail!("this platform has no supported official Flow binary"),
        };
        let name = binary.file_name().context("missing binary name")?;
        let input = staged
            .join(uf_infra::into_string(uf_infra::cstr!(
                "flow-{platform}-v{version}"
            )))
            .join(name);
        ensure!(
            fs::symlink_metadata(&input).is_ok_and(|m| m.is_file()),
            "Flow {version} does not publish a binary for this platform"
        );
        let ready = staged.join("ready");
        fs::create_dir(&ready)?;
        fs::rename(input, ready.join(name))?;
        verify_version(&ready.join(name), version)?;
        fs::rename(ready, &directory)?;
    }
    verify_version(&binary, version)?;
    Ok(binary)
}

fn verify_version(binary: &Utf8Path, version: &str) -> Result<()> {
    let result = Command::new(binary).args(["version", "--json"]).output()?;
    let value: serde_json::Value = serde_json::from_slice(&result.stdout)
        .context("the official Flow binary did not report its version")?;
    ensure!(
        result.status.success() && value.get("semver").and_then(|v| v.as_str()) == Some(version),
        "the acquired Flow binary does not match flow.version"
    );
    Ok(())
}

pub(super) fn opted_out(text: &str) -> bool {
    let Ok(parsed) = uf_flow::parse(text) else {
        return false;
    };
    let mut opted_out = false;
    for statement in parsed.program.statements.iter() {
        let uf_flow::ast::statement::StatementInner::Expression { inner, .. } = &**statement else {
            break;
        };
        let Some(directive) = inner.directive.as_deref() else {
            break;
        };
        match directive {
            "use js" => opted_out = true,
            "use flow" => opted_out = false,
            _ => {}
        }
    }
    opted_out
}

/// Preserve the author's sections, adding uf's source mode and checking policy.
pub(super) fn configure(root: &Utf8Path, config: &UniflowedConfig) -> Result<()> {
    let original = match fs::read_to_string(root.join(".flowconfig")) {
        Ok(text) => text,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(e) => return Err(e.into()),
    };
    let version = config
        .flow
        .version
        .as_deref()
        .context("flow.version is absent")?;
    let minor = version
        .split('.')
        .nth(1)
        .and_then(|n| n.parse::<u32>().ok())
        .unwrap_or_default();
    // Official Flow migrated ignore/include in 0.328, untyped in 0.330.
    let glob_ignore = minor >= 328;
    let glob_untyped = minor >= 330;
    let mut sections: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut section = String::new();
    for line in original.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') && trimmed.ends_with(']') {
            section = trimmed[1..trimmed.len() - 1].to_owned();
        } else if !section.is_empty() {
            sections
                .entry(section.clone())
                .or_default()
                .push(line.to_owned());
        }
    }
    sections
        .entry("ignore".into())
        .or_default()
        .push(if glob_ignore { ".uf/**" } else { ".*/\\.uf/.*" }.into());
    let sources = uf_project::scan_source_files(root, config)?;
    ensure!(
        sources.unreadable.is_empty(),
        "some project files could not be read for official Flow configuration"
    );
    for source in &sources.files {
        if opted_out(&source.source) {
            // Newer Flow uses globs; older releases use anchored regular expressions.
            let pattern = if glob_untyped {
                source.relative_path.clone()
            } else {
                let mut escaped = String::from("<PROJECT_ROOT>/");
                for c in source.relative_path.chars() {
                    if ".+*?[](){}^$|\\".contains(c) {
                        escaped.push('\\');
                    }
                    escaped.push(c);
                }
                escaped.push('$');
                escaped
            };
            sections.entry("untyped".into()).or_default().push(pattern);
        }
    }
    let options = sections.entry("options".into()).or_default();
    options.retain(|line| !line.trim_start().starts_with("all="));
    options.push("all=true".into());
    if !options
        .iter()
        .any(|line| line.trim_start().starts_with("server.max_workers="))
    {
        options.push("server.max_workers=4".into());
    }
    if !options
        .iter()
        .any(|line| line.trim_start().starts_with("module.name_mapper="))
    {
        options.push("module.name_mapper='^@uniflowed/react$' -> 'react'".into());
    }
    let mut generated = String::from(HEADER);
    for (section, lines) in sections {
        generated.push('[');
        generated.push_str(&section);
        generated.push_str("]\n");
        for line in lines {
            generated.push_str(&line);
            generated.push('\n');
        }
    }
    let path = root.join(CONFIG_NAME);
    match fs::read_to_string(&path) {
        Ok(existing) => {
            ensure!(
                existing.starts_with(HEADER),
                ".uf-flowconfig is not managed by uf; move it before selecting flow.version"
            );
            if existing == generated {
                return Ok(());
            }
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => return Err(e.into()),
    }
    let mut temporary = tempfile::NamedTempFile::new_in(root)?;
    std::io::Write::write_all(&mut temporary, generated.as_bytes())?;
    temporary.persist(path)?;
    Ok(())
}

#[cfg(feature = "upstream-typecheck")]
pub(super) fn check(root: &Utf8Path, config: &UniflowedConfig) -> Result<serde_json::Value> {
    let version = config
        .flow
        .version
        .as_deref()
        .context("flow.version is absent")?;
    let binary = acquire(version)?;
    configure(root, config)?;
    let output = Command::new(binary)
        .current_dir(root)
        .args([
            "full-check",
            "--json",
            "--include-warnings",
            "--show-all-errors",
            "--flowconfig-name",
            CONFIG_NAME,
        ])
        .arg(root)
        .output()?;
    ensure!(
        matches!(output.status.code(), Some(0 | 2)),
        uf_infra::cstr!(
            "official Flow failed: {}",
            String::from_utf8_lossy(&output.stderr)
        )
    );
    let result: serde_json::Value = serde_json::from_slice(&output.stdout)?;
    ensure!(
        result.get("errors").is_some_and(|v| v.is_array()),
        "official Flow returned an incomplete check"
    );
    Ok(result)
}
