//! The `server-actions.js` generated Flow types.
//!
//! [`RscManifest`](crate::RscManifest) tells the *runtime* which actions exist
//! and what their ids are. This module answers the other question, the one a
//! person writing code has: given the name of a server action, what arguments
//! does it take and what does it return?
//!
//! The answer is not something this crate knows. The scanner is a lexer — it
//! can see that `createUser` is an exported async function, and nothing about
//! its parameters. Flow knows, because the parameters are written in the
//! module. So the generated file does not restate a signature; it *points at*
//! one, with `import typeof`, and lets the checker read the real declaration:
//!
//! ```js
//! import typeof * as Module0 from "./app/actions.js";
//!
//! export type ServerActions = {
//!   "app/actions.js#createUser": Module0["createUser"],
//! };
//! ```
//!
//! What that buys is a closed set of action names with the real function type
//! behind each one, so a caller that addresses an action by name — a dispatch
//! table, a test harness, an RPC client — is checked at the call site. Passing
//! a string where the action wants a number is an error, and so is naming an
//! action that does not exist.
//!
//! # Why the file exists at all when a client can just import the action
//!
//! A Client Component that imports `createUser` from the `"use server"` module
//! already has its type; the bundler rewires the import and Flow reads the
//! declaration. Nothing here replaces that, and nothing here should.
//!
//! This is for the code that cannot import it — anything holding an action's
//! *name* rather than the action. That set has no other source of truth, and
//! it is the set that gets a string wrong.
//!
//! # What is deliberately absent
//!
//! * **Action ids.** [`ActionId`](crate::ActionId) is keyed on the build id,
//!   which changes per build, so an id written into a checked-in file would be
//!   wrong by the next one. The key here is `module#export`, which is stable.
//! * **Inline closures.** A `"use server"` closure inside a component is an
//!   action, but it is not an export, so there is no name to `import typeof`.
//!   It is in the manifest and not here.
//! * **Actions no client boundary reaches.** Same rule the manifest applies,
//!   for the same reason: something that is not a callable endpoint should not
//!   be given a call-site type that says it is one.
//! * **A dispatcher.** There is no runtime that takes a name and calls an
//!   action, so this file declares no function. It is types only, and it
//!   compiles to nothing: every import in it is `import typeof`, which is
//!   erased, so importing this file pulls no server module into a bundle.

use std::fs;

use camino::{Utf8Path, Utf8PathBuf};
use compact_str::CompactString;

use crate::RscError;
use crate::action::{ServerActionKind, ServerActionRegistry};

/// File name of the generated action types, in the project root.
///
/// Beside `router.js`, which is the other generated Flow file a project gets,
/// and named the same way: a plain source file the project can import.
pub const SERVER_ACTION_TYPES_FILE_NAME: &str = "server-actions.js";

/// The header every generated action types file carries.
///
/// A generated file that does not say it is generated gets edited by hand and
/// the edit is lost on the next run. `router.js` does not say it today; this
/// one does, and the sentence is here rather than inline so the test that
/// pins it and the writer that emits it cannot drift apart.
pub const SERVER_ACTION_TYPES_HEADER: &str = "\
// @flow
//
// Generated by `uf prepare`. Do not edit: the next run overwrites this file.
//
// Every callable server action of this project, keyed by `module#export`, with
// its real type read off the declaring module. `ServerActionArgs<Name>` is
// what that action takes and `ServerActionResult<Name>` is what it returns —
// a promise, because a server action is always async.
//
// An action is here when some module that can hand it across a client
// boundary reaches it, which is the same rule `uf-rsc-manifest.json`
// applies to what it publishes. An inline `\"use server\"` closure is not here:
// it has no export name to refer to.
//
// Type-only. Every import below is `import typeof`, which is erased, so
// importing this file adds nothing to a bundle.
";

/// One row of the generated table.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServerActionType {
    /// The key: `module#export`, stable across builds.
    pub name: CompactString,
    /// The module the export lives in, relative to the project root.
    pub module: Utf8PathBuf,
    /// The exported binding, or `default`.
    pub export: CompactString,
}

/// The callable module-export actions of a registry, ordered and deduplicated.
///
/// Ordered by key so that two runs over the same sources produce byte-identical
/// output; the registry is already sorted by module and export, and this only
/// narrows it.
#[must_use]
pub fn server_action_types(registry: &ServerActionRegistry) -> Vec<ServerActionType> {
    let mut rows: Vec<ServerActionType> = registry
        .callable_actions()
        .filter(|action| action.kind == ServerActionKind::ModuleExport)
        .map(|action| ServerActionType {
            name: CompactString::from(format!("{}#{}", action.module, action.export)),
            module: action.module.clone(),
            export: action.export.clone(),
        })
        .collect();
    rows.sort_by(|left, right| left.name.cmp(&right.name));
    rows.dedup_by(|left, right| left.name == right.name);
    rows
}

/// Render `server-actions.js` for a registry.
///
/// Written the way `uf fmt` writes it, down to the trailing commas and the
/// blank lines, for the same reason `uf_router::generate_router_flow` is:
/// `uf prepare` generates this file and then runs `uf fmt --check` over the
/// project, and a generated file the formatter disagrees with fails a commit
/// on code nobody wrote.
#[must_use]
pub fn generate_server_action_types(registry: &ServerActionRegistry) -> String {
    let rows = server_action_types(registry);

    // One namespace import per module rather than one alias per action: the
    // table then reads `Module0["createUser"]`, which names the export, and
    // there is no second numbering scheme to follow when two modules export
    // the same name.
    let mut modules: Vec<&Utf8Path> = rows.iter().map(|row| row.module.as_path()).collect();
    modules.dedup();

    let mut output = String::from(SERVER_ACTION_TYPES_HEADER);
    if !modules.is_empty() {
        output.push('\n');
        for (index, module) in modules.iter().enumerate() {
            output.push_str(&format!(
                "import typeof * as Module{index} from \"./{}\";\n",
                escape_flow_string(module.as_str())
            ));
        }
    }

    output.push('\n');
    if rows.is_empty() {
        // The router writes `RoutePath = empty` for a project with no routes
        // rather than omitting the type; the same choice here, so a consumer
        // can name `ServerActionName` whether or not the project has actions
        // yet. `$Keys<{}>` is `empty`, so every name is rejected.
        output.push_str("export type ServerActions = {};\n");
    } else {
        output.push_str("export type ServerActions = {\n");
        for row in &rows {
            let index = modules
                .iter()
                .position(|module| *module == row.module.as_path())
                .unwrap_or(0);
            output.push_str(&format!(
                "  \"{}\": Module{index}[\"{}\"],\n",
                escape_flow_string(&row.name),
                escape_flow_string(&row.export)
            ));
        }
        output.push_str("};\n");
    }

    // One line each, including the two that are ninety-odd characters wide:
    // `uf fmt` collapses a type alias that was split across lines back onto
    // one, so splitting them here would fail `uf fmt --check` on the file
    // this command has just written.
    output.push_str(
        "\nexport type ServerActionName = $Keys<ServerActions>;\n\
         \nexport type ServerActionArgs<Name extends ServerActionName> = \
         Parameters<ServerActions[Name]>;\n\
         \nexport type ServerActionResult<Name extends ServerActionName> = \
         ReturnType<ServerActions[Name]>;\n",
    );
    output
}

/// Write `server-actions.js` into the project root.
///
/// # Errors
///
/// [`RscError::Write`] when the file cannot be written.
pub fn write_server_action_types(
    root: &Utf8Path,
    registry: &ServerActionRegistry,
) -> Result<Utf8PathBuf, RscError> {
    let path = root.join(SERVER_ACTION_TYPES_FILE_NAME);
    fs::write(&path, generate_server_action_types(registry)).map_err(|source| RscError::Write {
        path: path.clone(),
        source,
    })?;
    Ok(path)
}

/// Escape a value for a double-quoted Flow string literal.
///
/// A module path is not guaranteed to be free of quotes and backslashes —
/// they are legal in a file name on every platform uf runs on — and a
/// generated file that does not parse is worse than one that names an awkward
/// path awkwardly.
fn escape_flow_string(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '"' => escaped.push_str("\\\""),
            '\\' => escaped.push_str("\\\\"),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            other => escaped.push(other),
        }
    }
    escaped
}

#[cfg(test)]
mod tests;
