// Generated by uf from input.js. Do not edit.

export type Frozen<T> = Readonly<T>;

export type List<T> = readonly T[];

export type Names<T> = keyof T;

export type Held<T> = T[keyof T];

export type Present<T> = NonNullable<T>;

export type Sealed<T> = T;

export type Difference<A, B> = unknown;

export type Loosened<T> = unknown;

export type Constructor<T> = unknown;

export type Anything = any;

export type Mapper = unknown;
