//! Descriptors for the rules uf defines itself, on top of Flow's lint set.
//!
//! These are the rules that come from uf being a toolchain rather than a type
//! checker: the router's file names, the server/client boundary, package layout,
//! the fetch client, the security set, and the accessibility and HTML-nesting
//! rules that come free with reading the parser's tree.

use uf_config::RuleLevel;

use crate::rules::RuleRequirement::SourceText;
use crate::rules::{RuleCategory, RuleDescriptor};

/// uf's own rules, on top of the Flow built-in set.
pub(crate) static OWN_RULES: &[RuleDescriptor] = &[
    RuleDescriptor {
        id: "a11y/alt-text",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "`img`, `area` and `input type=\"image\"` need an `alt`",
    },
    RuleDescriptor {
        id: "a11y/anchor-ambiguous-text",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "link text says where the link goes, not \"click here\"",
    },
    RuleDescriptor {
        id: "a11y/anchor-has-content",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "an `a` needs text or a label a screen reader can announce",
    },
    RuleDescriptor {
        id: "a11y/anchor-is-valid",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "an `a` needs a real `href`; an action belongs on a `button`",
    },
    RuleDescriptor {
        id: "a11y/aria-activedescendant-has-tabindex",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "`aria-activedescendant` needs an element that can take focus",
    },
    RuleDescriptor {
        id: "a11y/aria-props",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "an `aria-*` attribute must be one ARIA defines",
    },
    RuleDescriptor {
        id: "a11y/aria-proptypes",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "an `aria-*` value must be one its attribute takes",
    },
    RuleDescriptor {
        id: "a11y/aria-role",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "a `role` must be a real, non-abstract ARIA role",
    },
    RuleDescriptor {
        id: "a11y/aria-unsupported-elements",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "the elements ARIA reserves take no `role` and no `aria-*`",
    },
    RuleDescriptor {
        id: "a11y/autocomplete-valid",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "an autofill token the browser knows is what fills the field",
    },
    RuleDescriptor {
        id: "a11y/click-events-have-key-events",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "an element with a `role` and an `onClick` needs a key handler too",
    },
    RuleDescriptor {
        id: "a11y/control-has-associated-label",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "a control needs a name a screen reader can announce",
    },
    RuleDescriptor {
        id: "a11y/heading-has-content",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "a heading needs text or a label a screen reader can announce",
    },
    RuleDescriptor {
        id: "a11y/heading-order",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "heading levels go down one at a time",
    },
    RuleDescriptor {
        id: "a11y/html-has-lang",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "`html` needs a `lang`",
    },
    RuleDescriptor {
        id: "a11y/iframe-has-title",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "an `iframe` needs a `title` that says what it holds",
    },
    RuleDescriptor {
        id: "a11y/img-redundant-alt",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "`alt` text does not call the image an image, photo or picture",
    },
    RuleDescriptor {
        id: "a11y/interactive-supports-focus",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "a widget role has to be reachable by keyboard",
    },
    RuleDescriptor {
        id: "a11y/label-has-associated-control",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "a `label` must name a control, by `htmlFor` or by holding it",
    },
    RuleDescriptor {
        id: "a11y/lang",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "the `lang` on `html` has to be a language tag",
    },
    RuleDescriptor {
        id: "a11y/media-has-caption",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "`audio` and `video` need a captions `track`",
    },
    RuleDescriptor {
        id: "a11y/mouse-events-have-key-events",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "`onMouseOver` and `onMouseOut` need `onFocus` and `onBlur` beside them",
    },
    RuleDescriptor {
        id: "a11y/no-access-key",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "`accessKey` asks for a shortcut the browser has already given out",
    },
    RuleDescriptor {
        id: "a11y/no-aria-hidden-on-focusable",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "`aria-hidden` does not belong on an element that takes focus",
    },
    RuleDescriptor {
        id: "a11y/no-autofocus",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "`autoFocus` moves focus before the reader knows where they are",
    },
    RuleDescriptor {
        id: "a11y/no-distracting-elements",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "`marquee` and `blink` move with no way for the reader to stop them",
    },
    RuleDescriptor {
        id: "a11y/no-interactive-element-to-noninteractive-role",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "a control keeps its behaviour, so it must keep its announcement",
    },
    RuleDescriptor {
        id: "a11y/no-noninteractive-element-interactions",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "handlers belong on something announced as a control",
    },
    RuleDescriptor {
        id: "a11y/no-noninteractive-element-to-interactive-role",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "an element with its own semantics is not a control to relabel",
    },
    RuleDescriptor {
        id: "a11y/no-noninteractive-tabindex",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "a `tabIndex` belongs on a control, not on what is only read",
    },
    RuleDescriptor {
        id: "a11y/no-redundant-roles",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "a `role` the element already has says nothing twice",
    },
    RuleDescriptor {
        id: "a11y/no-static-element-interactions",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "an `onClick` needs an element a keyboard can reach",
    },
    RuleDescriptor {
        id: "a11y/prefer-tag-over-role",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "an element that is the role beats a `role` that says it",
    },
    RuleDescriptor {
        id: "a11y/role-has-required-aria-props",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "a role must be given the `aria-*` state it is announced by",
    },
    RuleDescriptor {
        id: "a11y/role-supports-aria-props",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "an element carries only the `aria-*` its role takes",
    },
    RuleDescriptor {
        id: "a11y/scope",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "`scope` belongs on a `th` and is ignored anywhere else",
    },
    RuleDescriptor {
        id: "a11y/tabindex-no-positive",
        category: RuleCategory::A11y,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "a `tabIndex` above zero reorders the whole page",
    },
    RuleDescriptor {
        id: "markup/no-invalid-nesting",
        category: RuleCategory::Markup,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "nest elements the HTML parser will leave where you wrote them",
    },
    RuleDescriptor {
        id: "markup/no-invalid-rel",
        category: RuleCategory::Markup,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "a `rel` keyword has to be one this element takes",
    },
    RuleDescriptor {
        id: "vite/hot-needs-optional-chaining",
        category: RuleCategory::Vite,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "reach `import.meta.hot` through `?.`; `if` does not refine it",
    },
    RuleDescriptor {
        id: "flow/syntax",
        category: RuleCategory::Flow,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "the file must parse with the official Flow parser",
    },
    RuleDescriptor {
        id: "import/no-absolute-path",
        category: RuleCategory::Import,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "imports must name packages or project-relative paths, not filesystem roots",
    },
    RuleDescriptor {
        id: "import/no-duplicates",
        category: RuleCategory::Import,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "mergeable static imports from the same module belong together",
    },
    RuleDescriptor {
        id: "import/no-self-import",
        category: RuleCategory::Import,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "a module must not import itself",
    },
    RuleDescriptor {
        id: "import/no-useless-path-segments",
        category: RuleCategory::Import,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "relative imports should name the shortest equivalent path",
    },
    RuleDescriptor {
        id: "uniflowed/no-tabs",
        category: RuleCategory::Uniflowed,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "indent with spaces, never tabs",
    },
    RuleDescriptor {
        id: "uniflowed/no-trailing-whitespace",
        category: RuleCategory::Uniflowed,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "lines must not end in whitespace",
    },
    RuleDescriptor {
        id: "uniflowed/no-npm-script-invocation",
        category: RuleCategory::Uniflowed,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "shell out to uf tasks, not `npm run`/`yarn`/`pnpm`/`bunx`",
    },
    RuleDescriptor {
        id: "uniflowed/unknown-lint-suppression",
        category: RuleCategory::Uniflowed,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "`uf-lint-disable` comments must name a rule this linter knows",
    },
    // The official React Compiler's categories, each at the level
    // `eslint-plugin-react-hooks`' `recommended-latest` preset gives it, except
    // `hooks` (`error`) and `memo-dependencies` (`warn`), which the plugin also
    // answers with its classic `rules-of-hooks` and `exhaustive-deps` at those
    // levels while uf has only the compiler's answer. `uf_config`'s default
    // table argues each level, and `runner::react_compiler::rule_for` says why
    // the categories without a rule have none.
    RuleDescriptor {
        id: "react-compiler/capitalized-calls",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Off,
        requirement: SourceText,
        description: "the React Compiler's `CapitalizedCalls` diagnostics: a capitalized function called instead of rendered with JSX",
    },
    RuleDescriptor {
        id: "react-compiler/error-boundaries",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "the React Compiler's `ErrorBoundaries` diagnostics: JSX built inside `try`/`catch` instead of under an error boundary",
    },
    RuleDescriptor {
        id: "react-compiler/exhaustive-effect-dependencies",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Off,
        requirement: SourceText,
        description: "the React Compiler's `EffectExhaustiveDependencies` diagnostics: an effect's dependency array missing or adding a value",
    },
    RuleDescriptor {
        id: "react-compiler/fbt",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Off,
        requirement: SourceText,
        description: "the React Compiler's `FBT` diagnostics, about Meta's `fbt` internationalization library",
    },
    RuleDescriptor {
        id: "react-compiler/globals",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "the React Compiler's `Globals` diagnostics: a variable from outside a component or hook changed during render",
    },
    RuleDescriptor {
        id: "react-compiler/hooks",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "the React Compiler's `Hooks` diagnostics: the Rules of Hooks",
    },
    RuleDescriptor {
        id: "react-compiler/purity",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "the React Compiler's `Purity` diagnostics: a known-impure function called during render",
    },
    RuleDescriptor {
        id: "react-compiler/immutability",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "the React Compiler's `Immutability` diagnostics: props, state or another value React treats as immutable, mutated",
    },
    RuleDescriptor {
        id: "react-compiler/incompatible-library",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "the React Compiler's `IncompatibleLibrary` diagnostics: an API known to break memoization",
    },
    RuleDescriptor {
        id: "react-compiler/invariant",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Off,
        requirement: SourceText,
        description: "the React Compiler's `Invariant` diagnostics: an internal assumption of the compiler that did not hold",
    },
    RuleDescriptor {
        id: "react-compiler/memo-dependencies",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "the React Compiler's `MemoDependencies` diagnostics: a `useMemo` or `useCallback` dependency array missing or adding a value",
    },
    RuleDescriptor {
        id: "react-compiler/no-deriving-state-in-effects",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Off,
        requirement: SourceText,
        description: "the React Compiler's `EffectDerivationsOfState` diagnostics: a value derived from props or state, computed in an effect",
    },
    RuleDescriptor {
        id: "react-compiler/preserve-manual-memoization",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "the React Compiler's `PreserveManualMemo` diagnostics: a `useMemo` or `useCallback` the compiler cannot preserve",
    },
    RuleDescriptor {
        id: "react-compiler/refs",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "the React Compiler's `Refs` diagnostics: a ref read or written during render",
    },
    RuleDescriptor {
        id: "react-compiler/set-state-in-effect",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "the React Compiler's `EffectSetState` diagnostics: `setState` called synchronously in an effect",
    },
    RuleDescriptor {
        id: "react-compiler/set-state-in-render",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "the React Compiler's `RenderSetState` diagnostics: `setState` called during render",
    },
    RuleDescriptor {
        id: "react-compiler/static-components",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "the React Compiler's `StaticComponents` diagnostics: a component created during render",
    },
    RuleDescriptor {
        id: "react-compiler/syntax",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Off,
        requirement: SourceText,
        description: "the React Compiler's `Syntax` diagnostics: code the compiler rejects as invalid syntax",
    },
    RuleDescriptor {
        id: "react-compiler/todo",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Off,
        requirement: SourceText,
        description: "the React Compiler's `Todo` diagnostics: code the compiler does not compile yet",
    },
    RuleDescriptor {
        id: "react-compiler/unsupported-syntax",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "the React Compiler's `UnsupportedSyntax` diagnostics: syntax the compiler does not support",
    },
    RuleDescriptor {
        id: "react-compiler/use-memo",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "the React Compiler's `UseMemo` diagnostics: a `useMemo` callback that is async, a generator, or takes parameters",
    },
    RuleDescriptor {
        id: "react-compiler/void-use-memo",
        category: RuleCategory::ReactCompiler,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "the React Compiler's `VoidUseMemo` diagnostics: a `useMemo` callback that returns nothing",
    },
    RuleDescriptor {
        id: "react/component-syntax",
        category: RuleCategory::React,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "declare React components with Flow `component` syntax",
    },
    RuleDescriptor {
        id: "react/hook-syntax",
        category: RuleCategory::React,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "declare React hooks with Flow `hook` syntax",
    },
    RuleDescriptor {
        id: "react/jsx-key",
        category: RuleCategory::React,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "an element built in an array or by `map` needs a `key`",
    },
    RuleDescriptor {
        id: "react/jsx-no-comment-textnodes",
        category: RuleCategory::React,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "`//` and `/*` between JSX tags are text on the page, not comments",
    },
    RuleDescriptor {
        id: "react/jsx-no-duplicate-props",
        category: RuleCategory::React,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "give each prop once; a repeated one silently replaces the first",
    },
    // `warn`: an index is the wrong key only for a list that reorders, filters
    // or grows at the front, and a list that does none of those is correct code.
    RuleDescriptor {
        id: "react/no-array-index-key",
        category: RuleCategory::React,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "key a list item by what it is, not by where it stands",
    },
    // `warn`: a `children` prop renders exactly what nesting would, and the one
    // shape that loses content — the prop and nested children together — is
    // the one the message calls out.
    RuleDescriptor {
        id: "react/no-children-prop",
        category: RuleCategory::React,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "write `children` between the tags, not as a prop",
    },
    // `warn`, not `error`, for the same reason as `react/component-syntax`: this
    // is a convention the ecosystem (and uf's own `uf create app` scaffold) is
    // still migrating to, and a linter must not fail a freshly created project.
    // It becomes an error once the scaffold ships named exports.
    RuleDescriptor {
        id: "react/no-default-export-component",
        category: RuleCategory::React,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "modules that declare components must use named exports",
    },
    RuleDescriptor {
        id: "react/no-redundant-memo",
        category: RuleCategory::React,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "drop a `useMemo`/`useCallback` the React Compiler already did",
    },
    RuleDescriptor {
        id: "react/button-has-type",
        category: RuleCategory::React,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "a `button` defaults to `submit`, so say which kind it is",
    },
    RuleDescriptor {
        id: "react/checked-requires-onchange-or-readonly",
        category: RuleCategory::React,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "a `checked` input needs an `onChange` or a `readOnly`",
    },
    RuleDescriptor {
        id: "react/no-namespace",
        category: RuleCategory::React,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "React has no way to render a namespaced element name",
    },
    // A `component` or `hook` declaration is called as a plain function, so
    // `this` in one is `undefined` and reading a prop off it throws.
    RuleDescriptor {
        id: "react/no-this-in-sfc",
        category: RuleCategory::React,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "`this` names nothing inside a `component` or `hook`",
    },
    RuleDescriptor {
        id: "react/no-unescaped-entities",
        category: RuleCategory::React,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "a `>` or `}` left in JSX text is usually a mistyped tag",
    },
    RuleDescriptor {
        id: "react/no-unknown-property",
        category: RuleCategory::React,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "write the prop React spells, not the HTML attribute name",
    },
    // `off`, as in the plugin's own preset: a prop nothing reads is dead weight
    // rather than a defect, and dropping one from a component other code calls
    // is an API decision rather than a lint fix.
    RuleDescriptor {
        id: "react/no-unused-prop-types",
        category: RuleCategory::React,
        default_level: RuleLevel::Off,
        requirement: SourceText,
        description: "a prop a `component` declares should be read by its body",
    },
    RuleDescriptor {
        id: "react/style-prop-object",
        category: RuleCategory::React,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "`style` takes an object; React throws on anything else",
    },
    RuleDescriptor {
        id: "react/void-dom-elements-no-children",
        category: RuleCategory::React,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "void elements such as `img` and `br` take no children",
    },
    RuleDescriptor {
        id: "react-native/platform-split",
        category: RuleCategory::ReactNative,
        default_level: RuleLevel::Warn,
        requirement: SourceText,
        description: "prefer platform-specific files over `Platform.OS` branches",
    },
    RuleDescriptor {
        id: "server/no-client-secret",
        category: RuleCategory::Server,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "client modules must not read server secrets",
    },
    RuleDescriptor {
        id: "server/no-server-only-import-in-client",
        category: RuleCategory::Server,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "client modules must not import server-only modules",
    },
    RuleDescriptor {
        id: "server/use-client-directive-position",
        category: RuleCategory::Server,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "`use client`/`use server` must be the module's first statement",
    },
    RuleDescriptor {
        id: "server/use-server-actions",
        category: RuleCategory::Server,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "server action modules must open with `\"use server\";`",
    },
    RuleDescriptor {
        id: "router/reserved-files",
        category: RuleCategory::Router,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "`$*` file names are reserved for layout, page, and middleware",
    },
    RuleDescriptor {
        id: "router/unsupported-segment",
        category: RuleCategory::Router,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "`(.)segment` directories must be interceptions uf reads, inside a `@slot`",
    },
    RuleDescriptor {
        id: "package/no-npm-scripts",
        category: RuleCategory::Package,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "declare tasks in `uf.config.js`, not `package.json` scripts",
    },
    RuleDescriptor {
        id: "fetch/no-global-override",
        category: RuleCategory::Fetch,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "do not monkey-patch global `fetch`",
    },
    RuleDescriptor {
        id: "security/iframe-has-sandbox",
        category: RuleCategory::Security,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "an `iframe` needs a `sandbox` to bound what the page inside it may do",
    },
    RuleDescriptor {
        id: "security/no-dangerously-set-inner-html",
        category: RuleCategory::Security,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "render HTML only through a sanitizing `@uniflowed/markdown` helper",
    },
    RuleDescriptor {
        id: "security/no-eval",
        category: RuleCategory::Security,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "never turn strings into code via `eval`, `new Function`, or timer strings",
    },
    RuleDescriptor {
        id: "security/no-script-url",
        category: RuleCategory::Security,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "a `javascript:` URL is a program in a prop the browser navigates to",
    },
    RuleDescriptor {
        id: "security/no-target-blank",
        category: RuleCategory::Security,
        default_level: RuleLevel::Error,
        requirement: SourceText,
        description: "`target=\"_blank\"` carries the page's URL on unless `rel` stops it",
    },
];
