// Generated by uf from input.js. Do not edit.

export type Primitive = number | string | boolean | symbol | bigint;

export type Maybe = string | null | undefined;

export type Top = unknown;

export type Bottom = never;

export type Nothing = void;

export type Literals = "a" | 42 | true | null;

export type Template = `id-${string}`;

export type Both = { kind: "a" } & { size: number };

export type Nested = Array<string | null | undefined> | null | undefined;
