[package]
name = "uf_tui"
description = "What @uniflowed/tui is, as the toolchain describes it."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
compact_str.workspace = true
serde.workspace = true
smallvec.workspace = true

[dev-dependencies]
serde_json.workspace = true
