// Generated by uf from input.js. Do not edit.

export type Handler = (event: string, count?: number) => void;

export type Anonymous = (arg0: string, arg1: number) => boolean;

export type Rest = (...items: Array<string>) => number;

export type Bounded<T extends { id: string }> = (value: T) => T;

export type Defaulted<T = string> = (value: T) => T;

export type Varied<out Out, in In> = (input: In) => Out;

export type Constructor = new (size: number) => Array<string>;

export declare function isString(value: unknown): value is string;



export declare function identity<T>(value: T): T;



export declare function pad(raw: string, width?: number, ...rest: Array<string>): string;
