/**
 * Generated by uf's sqlc plugin from the schema with sqlc v1.31.1.
 * Do not edit: change the SQL and run `uf sqlc generate`.
 *
 * @generated SignedSource<<4218651c9c0bef5d5a0a869165ba207e>>
 * @flow
 */

/** A row of `members`. */
export type Member = {|
  readonly id: string,
  readonly name: string,
  readonly handle: string,
  readonly bio: string,
  readonly email: string,
  readonly passwordHash: string | null,
|};

/** A row of `entries`. */
export type Entry = {|
  readonly id: string,
  readonly authorId: string,
  readonly body: string,
  readonly topic: string,
  readonly createdAt: string,
  readonly requestId: string,
|};

/** A row of `reactions`. */
export type Reaction = {|
  readonly entryId: string,
  readonly memberId: string,
|};

/** A row of `conversations`. */
export type Conversation = {|
  readonly id: string,
|};

/** A row of `participants`. */
export type Participant = {|
  readonly conversationId: string,
  readonly memberId: string,
|};

/** A row of `notes`. */
export type Note = {|
  readonly id: string,
  readonly conversationId: string,
  readonly authorId: string,
  readonly body: string,
  readonly createdAt: string,
  readonly requestId: string,
|};

/** A row of `sessions`. */
export type Session = {|
  readonly tokenHash: string,
  readonly memberId: string,
  readonly expiresAt: number,
|};

/** A row of `auth_attempts`. */
export type AuthAttempt = {|
  readonly handle: string,
  readonly attempts: number,
  readonly resetsAt: number,
|};
