/**
 * Generated by uf's sqlc plugin from `query.sql` with sqlc v1.31.1.
 * Do not edit: change the SQL and run `uf sqlc generate`.
 *
 * @generated SignedSource<<7267a052a53ece61bdf4f69ab01af28c>>
 * @flow
 */

import type { SyncQueryable } from "@uniflowed/sql";
import * as sql from "@uniflowed/sql";
import * as sqlite from "@uniflowed/sql/sqlite";
import type { Note } from "./models.js";

export type GetMemberArgs = {|
  readonly id: string,
|};

export type GetMemberRow = {|
  readonly id: string,
  readonly name: string,
  readonly handle: string,
  readonly bio: string,
|};

const getMemberSql = `SELECT id, name, handle, bio
FROM members
WHERE id = ?`;

export function getMember(db: SyncQueryable, args: GetMemberArgs): GetMemberRow | null {
  return sql.oneSync(db, "GetMember", getMemberSql, [sqlite.string.encode(args.id)], 4, (row) => ({
    id: sqlite.string.decode(row[0]),
    name: sqlite.string.decode(row[1]),
    handle: sqlite.string.decode(row[2]),
    bio: sqlite.string.decode(row[3]),
  }));
}

export type ListPostsArgs = {|
  readonly viewerId: string | null,
  readonly topic: string | null,
  readonly needle: string,
  readonly offset: number,
  readonly limit: number,
|};

export type ListPostsRow = {|
  readonly id: string,
  readonly body: string,
  readonly topic: string,
  readonly createdAt: string,
  readonly authorId: string,
  readonly name: string,
  readonly handle: string,
  readonly bio: string,
  readonly likes: number,
  readonly liked: boolean,
|};

const listPostsSql = `SELECT
  e.id,
  e.body,
  e.topic,
  e.created_at,
  m.id AS author_id,
  m.name,
  m.handle,
  m.bio,
  (SELECT count(*) FROM reactions r WHERE r.entry_id = e.id) AS likes,
  EXISTS(
    SELECT 1 FROM reactions r
    WHERE r.entry_id = e.id AND r.member_id = ?
  ) AS liked
FROM entries e
JOIN members m ON m.id = e.author_id
WHERE e.topic = coalesce(?, e.topic)
  AND (
    cast(? AS TEXT) = ''
    OR instr(
      lower(e.body || ' ' || m.name || ' ' || m.handle),
      cast(? AS TEXT)
    ) > 0
  )
ORDER BY e.created_at DESC, e.id DESC
LIMIT ? OFFSET ?`;

export function listPosts(db: SyncQueryable, args: ListPostsArgs): Array<ListPostsRow> {
  return sql.manySync(
    db,
    "ListPosts",
    listPostsSql,
    [
      sqlite.param(sqlite.string, args.viewerId),
      sqlite.param(sqlite.string, args.topic),
      sqlite.string.encode(args.needle),
      sqlite.string.encode(args.needle),
      sqlite.integer.encode(args.limit),
      sqlite.integer.encode(args.offset),
    ],
    10,
    (row) => ({
      id: sqlite.string.decode(row[0]),
      body: sqlite.string.decode(row[1]),
      topic: sqlite.string.decode(row[2]),
      createdAt: sqlite.string.decode(row[3]),
      authorId: sqlite.string.decode(row[4]),
      name: sqlite.string.decode(row[5]),
      handle: sqlite.string.decode(row[6]),
      bio: sqlite.string.decode(row[7]),
      likes: sqlite.integer.decode(row[8]),
      liked: sqlite.boolean.decode(row[9]),
    }),
  );
}

export type GetPostArgs = {|
  readonly viewerId: string | null,
  readonly id: string,
|};

export type GetPostRow = {|
  readonly id: string,
  readonly body: string,
  readonly topic: string,
  readonly createdAt: string,
  readonly authorId: string,
  readonly name: string,
  readonly handle: string,
  readonly bio: string,
  readonly likes: number,
  readonly liked: boolean,
|};

const getPostSql = `SELECT
  e.id,
  e.body,
  e.topic,
  e.created_at,
  m.id AS author_id,
  m.name,
  m.handle,
  m.bio,
  (SELECT count(*) FROM reactions r WHERE r.entry_id = e.id) AS likes,
  EXISTS(
    SELECT 1 FROM reactions r
    WHERE r.entry_id = e.id AND r.member_id = ?
  ) AS liked
FROM entries e
JOIN members m ON m.id = e.author_id
WHERE e.id = ?`;

export function getPost(db: SyncQueryable, args: GetPostArgs): GetPostRow | null {
  return sql.oneSync(
    db,
    "GetPost",
    getPostSql,
    [sqlite.param(sqlite.string, args.viewerId), sqlite.string.encode(args.id)],
    10,
    (row) => ({
      id: sqlite.string.decode(row[0]),
      body: sqlite.string.decode(row[1]),
      topic: sqlite.string.decode(row[2]),
      createdAt: sqlite.string.decode(row[3]),
      authorId: sqlite.string.decode(row[4]),
      name: sqlite.string.decode(row[5]),
      handle: sqlite.string.decode(row[6]),
      bio: sqlite.string.decode(row[7]),
      likes: sqlite.integer.decode(row[8]),
      liked: sqlite.boolean.decode(row[9]),
    }),
  );
}

export type EntryByRequestArgs = {|
  readonly authorId: string,
  readonly requestId: string,
|};

export type EntryByRequestRow = {|
  readonly id: string,
  readonly body: string,
  readonly topic: string,
|};

const entryByRequestSql = `SELECT id, body, topic
FROM entries
WHERE author_id = ? AND request_id = ?`;

export function entryByRequest(
  db: SyncQueryable,
  args: EntryByRequestArgs,
): EntryByRequestRow | null {
  return sql.oneSync(
    db,
    "EntryByRequest",
    entryByRequestSql,
    [sqlite.string.encode(args.authorId), sqlite.string.encode(args.requestId)],
    3,
    (row) => ({
      id: sqlite.string.decode(row[0]),
      body: sqlite.string.decode(row[1]),
      topic: sqlite.string.decode(row[2]),
    }),
  );
}

export type InsertEntryArgs = {|
  readonly id: string,
  readonly authorId: string,
  readonly body: string,
  readonly topic: string,
  readonly createdAt: string,
  readonly requestId: string,
|};

const insertEntrySql = `INSERT INTO entries (id, author_id, body, topic, created_at, request_id)
VALUES (?, ?, ?, ?, ?, ?)`;

export function insertEntry(db: SyncQueryable, args: InsertEntryArgs): void {
  return sql.execSync(db, "InsertEntry", insertEntrySql, [
    sqlite.string.encode(args.id),
    sqlite.string.encode(args.authorId),
    sqlite.string.encode(args.body),
    sqlite.string.encode(args.topic),
    sqlite.string.encode(args.createdAt),
    sqlite.string.encode(args.requestId),
  ]);
}

export type InsertReactionArgs = {|
  readonly entryId: string,
  readonly memberId: string,
|};

const insertReactionSql = `INSERT OR IGNORE INTO reactions (entry_id, member_id)
VALUES (?, ?)`;

export function insertReaction(db: SyncQueryable, args: InsertReactionArgs): void {
  return sql.execSync(db, "InsertReaction", insertReactionSql, [
    sqlite.string.encode(args.entryId),
    sqlite.string.encode(args.memberId),
  ]);
}

export type DeleteReactionArgs = {|
  readonly entryId: string,
  readonly memberId: string,
|};

const deleteReactionSql = `DELETE FROM reactions
WHERE entry_id = ? AND member_id = ?`;

export function deleteReaction(db: SyncQueryable, args: DeleteReactionArgs): void {
  return sql.execSync(db, "DeleteReaction", deleteReactionSql, [
    sqlite.string.encode(args.entryId),
    sqlite.string.encode(args.memberId),
  ]);
}

export type ListThreadsArgs = {|
  readonly viewerId: string,
|};

export type ListThreadsRow = {|
  readonly id: string,
  readonly memberId: string,
  readonly name: string,
  readonly handle: string,
  readonly bio: string,
  readonly lastMessage: string,
|};

const listThreadsSql = `SELECT
  c.id,
  m.id AS member_id,
  m.name,
  m.handle,
  m.bio,
  cast(
    coalesce(
      (SELECT body FROM notes WHERE conversation_id = c.id ORDER BY created_at DESC, id DESC LIMIT 1),
      ''
    ) AS TEXT
  ) AS last_message
FROM conversations c
JOIN participants mine ON mine.conversation_id = c.id AND mine.member_id = ?
JOIN participants other ON other.conversation_id = c.id AND other.member_id <> ?
JOIN members m ON m.id = other.member_id
ORDER BY c.id
LIMIT 50`;

export function listThreads(db: SyncQueryable, args: ListThreadsArgs): Array<ListThreadsRow> {
  return sql.manySync(
    db,
    "ListThreads",
    listThreadsSql,
    [sqlite.string.encode(args.viewerId), sqlite.string.encode(args.viewerId)],
    6,
    (row) => ({
      id: sqlite.string.decode(row[0]),
      memberId: sqlite.string.decode(row[1]),
      name: sqlite.string.decode(row[2]),
      handle: sqlite.string.decode(row[3]),
      bio: sqlite.string.decode(row[4]),
      lastMessage: sqlite.string.decode(row[5]),
    }),
  );
}

export type ParticipantArgs = {|
  readonly conversationId: string,
  readonly memberId: string,
|};

const participantSql = `SELECT member_id
FROM participants
WHERE conversation_id = ? AND member_id = ?`;

export function participant(db: SyncQueryable, args: ParticipantArgs): string | null {
  return sql.oneSync(
    db,
    "Participant",
    participantSql,
    [sqlite.string.encode(args.conversationId), sqlite.string.encode(args.memberId)],
    1,
    (row) => sqlite.string.decode(row[0]),
  );
}

export type ListMessagesArgs = {|
  readonly conversationId: string,
|};

export type ListMessagesRow = {|
  readonly id: string,
  readonly conversationId: string,
  readonly authorId: string,
  readonly body: string,
  readonly createdAt: string,
|};

const listMessagesSql = `SELECT id, conversation_id, author_id, body, created_at
FROM (
  SELECT id, conversation_id, author_id, body, created_at
  FROM notes
  WHERE conversation_id = ?
  ORDER BY created_at DESC, id DESC
  LIMIT 50
)
ORDER BY created_at, id`;

export function listMessages(db: SyncQueryable, args: ListMessagesArgs): Array<ListMessagesRow> {
  return sql.manySync(
    db,
    "ListMessages",
    listMessagesSql,
    [sqlite.string.encode(args.conversationId)],
    5,
    (row) => ({
      id: sqlite.string.decode(row[0]),
      conversationId: sqlite.string.decode(row[1]),
      authorId: sqlite.string.decode(row[2]),
      body: sqlite.string.decode(row[3]),
      createdAt: sqlite.string.decode(row[4]),
    }),
  );
}

export type NoteByRequestArgs = {|
  readonly authorId: string,
  readonly requestId: string,
|};

const noteByRequestSql = `SELECT id, conversation_id, author_id, body, created_at, request_id
FROM notes
WHERE author_id = ? AND request_id = ?`;

export function noteByRequest(db: SyncQueryable, args: NoteByRequestArgs): Note | null {
  return sql.oneSync(
    db,
    "NoteByRequest",
    noteByRequestSql,
    [sqlite.string.encode(args.authorId), sqlite.string.encode(args.requestId)],
    6,
    (row) => ({
      id: sqlite.string.decode(row[0]),
      conversationId: sqlite.string.decode(row[1]),
      authorId: sqlite.string.decode(row[2]),
      body: sqlite.string.decode(row[3]),
      createdAt: sqlite.string.decode(row[4]),
      requestId: sqlite.string.decode(row[5]),
    }),
  );
}

export type InsertNoteArgs = {|
  readonly id: string,
  readonly conversationId: string,
  readonly authorId: string,
  readonly body: string,
  readonly createdAt: string,
  readonly requestId: string,
|};

const insertNoteSql = `INSERT INTO notes (id, conversation_id, author_id, body, created_at, request_id)
VALUES (?, ?, ?, ?, ?, ?)`;

export function insertNote(db: SyncQueryable, args: InsertNoteArgs): void {
  return sql.execSync(db, "InsertNote", insertNoteSql, [
    sqlite.string.encode(args.id),
    sqlite.string.encode(args.conversationId),
    sqlite.string.encode(args.authorId),
    sqlite.string.encode(args.body),
    sqlite.string.encode(args.createdAt),
    sqlite.string.encode(args.requestId),
  ]);
}

export type MemberSettingsArgs = {|
  readonly id: string,
|};

export type MemberSettingsRow = {|
  readonly name: string,
  readonly handle: string,
  readonly bio: string,
  readonly email: string,
|};

const memberSettingsSql = `SELECT name, handle, bio, email
FROM members
WHERE id = ?`;

export function memberSettings(
  db: SyncQueryable,
  args: MemberSettingsArgs,
): MemberSettingsRow | null {
  return sql.oneSync(
    db,
    "MemberSettings",
    memberSettingsSql,
    [sqlite.string.encode(args.id)],
    4,
    (row) => ({
      name: sqlite.string.decode(row[0]),
      handle: sqlite.string.decode(row[1]),
      bio: sqlite.string.decode(row[2]),
      email: sqlite.string.decode(row[3]),
    }),
  );
}

export type HandleOwnerArgs = {|
  readonly handle: string,
  readonly id: string,
|};

const handleOwnerSql = `SELECT id
FROM members
WHERE handle = ? AND id <> ?`;

export function handleOwner(db: SyncQueryable, args: HandleOwnerArgs): string | null {
  return sql.oneSync(
    db,
    "HandleOwner",
    handleOwnerSql,
    [sqlite.string.encode(args.handle), sqlite.string.encode(args.id)],
    1,
    (row) => sqlite.string.decode(row[0]),
  );
}

export type UpdateMemberArgs = {|
  readonly name: string,
  readonly handle: string,
  readonly bio: string,
  readonly email: string,
  readonly id: string,
|};

const updateMemberSql = `UPDATE members
SET name = ?, handle = ?, bio = ?, email = ?
WHERE id = ?`;

export function updateMember(db: SyncQueryable, args: UpdateMemberArgs): void {
  return sql.execSync(db, "UpdateMember", updateMemberSql, [
    sqlite.string.encode(args.name),
    sqlite.string.encode(args.handle),
    sqlite.string.encode(args.bio),
    sqlite.string.encode(args.email),
    sqlite.string.encode(args.id),
  ]);
}

export type InsertConversationArgs = {|
  readonly id: string,
|};

const insertConversationSql = `INSERT INTO conversations (id)
VALUES (?)`;

export function insertConversation(db: SyncQueryable, args: InsertConversationArgs): void {
  return sql.execSync(db, "InsertConversation", insertConversationSql, [
    sqlite.string.encode(args.id),
  ]);
}

export type InsertParticipantArgs = {|
  readonly conversationId: string,
  readonly memberId: string,
|};

const insertParticipantSql = `INSERT INTO participants (conversation_id, member_id)
VALUES (?, ?)`;

export function insertParticipant(db: SyncQueryable, args: InsertParticipantArgs): void {
  return sql.execSync(db, "InsertParticipant", insertParticipantSql, [
    sqlite.string.encode(args.conversationId),
    sqlite.string.encode(args.memberId),
  ]);
}

export type SeedMemberArgs = {|
  readonly id: string,
  readonly name: string,
  readonly handle: string,
  readonly bio: string,
|};

const seedMemberSql = `INSERT OR IGNORE INTO members (id, name, handle, bio)
VALUES (?, ?, ?, ?)`;

export function seedMember(db: SyncQueryable, args: SeedMemberArgs): void {
  return sql.execSync(db, "SeedMember", seedMemberSql, [
    sqlite.string.encode(args.id),
    sqlite.string.encode(args.name),
    sqlite.string.encode(args.handle),
    sqlite.string.encode(args.bio),
  ]);
}

export type SeedEntryArgs = {|
  readonly id: string,
  readonly authorId: string,
  readonly body: string,
  readonly topic: string,
  readonly createdAt: string,
  readonly requestId: string,
|};

const seedEntrySql = `INSERT OR IGNORE INTO entries (id, author_id, body, topic, created_at, request_id)
VALUES (?, ?, ?, ?, ?, ?)`;

export function seedEntry(db: SyncQueryable, args: SeedEntryArgs): void {
  return sql.execSync(db, "SeedEntry", seedEntrySql, [
    sqlite.string.encode(args.id),
    sqlite.string.encode(args.authorId),
    sqlite.string.encode(args.body),
    sqlite.string.encode(args.topic),
    sqlite.string.encode(args.createdAt),
    sqlite.string.encode(args.requestId),
  ]);
}

export type SeedReactionArgs = {|
  readonly entryId: string,
  readonly memberId: string,
|};

const seedReactionSql = `INSERT OR IGNORE INTO reactions (entry_id, member_id)
VALUES (?, ?)`;

export function seedReaction(db: SyncQueryable, args: SeedReactionArgs): void {
  return sql.execSync(db, "SeedReaction", seedReactionSql, [
    sqlite.string.encode(args.entryId),
    sqlite.string.encode(args.memberId),
  ]);
}

export type SessionMemberArgs = {|
  readonly tokenHash: string,
  readonly expiresAt: number,
|};

const sessionMemberSql = `SELECT member_id
FROM sessions
WHERE token_hash = ? AND expires_at > ?`;

export function sessionMember(db: SyncQueryable, args: SessionMemberArgs): string | null {
  return sql.oneSync(
    db,
    "SessionMember",
    sessionMemberSql,
    [sqlite.string.encode(args.tokenHash), sqlite.integer.encode(args.expiresAt)],
    1,
    (row) => sqlite.string.decode(row[0]),
  );
}

export type DeleteExpiredAttemptsArgs = {|
  readonly resetsAt: number,
|};

const deleteExpiredAttemptsSql = `DELETE FROM auth_attempts
WHERE resets_at < ?`;

export function deleteExpiredAttempts(db: SyncQueryable, args: DeleteExpiredAttemptsArgs): void {
  return sql.execSync(db, "DeleteExpiredAttempts", deleteExpiredAttemptsSql, [
    sqlite.integer.encode(args.resetsAt),
  ]);
}

export type RecordAttemptArgs = {|
  readonly handle: string,
  readonly resetsAt: number,
|};

const recordAttemptSql = `INSERT INTO auth_attempts (handle, attempts, resets_at)
VALUES (?, 1, ?)
ON CONFLICT(handle) DO UPDATE SET attempts = attempts + 1`;

export function recordAttempt(db: SyncQueryable, args: RecordAttemptArgs): void {
  return sql.execSync(db, "RecordAttempt", recordAttemptSql, [
    sqlite.string.encode(args.handle),
    sqlite.integer.encode(args.resetsAt),
  ]);
}

export type AttemptCountArgs = {|
  readonly handle: string,
|};

const attemptCountSql = `SELECT attempts
FROM auth_attempts
WHERE handle = ?`;

export function attemptCount(db: SyncQueryable, args: AttemptCountArgs): number | null {
  return sql.oneSync(
    db,
    "AttemptCount",
    attemptCountSql,
    [sqlite.string.encode(args.handle)],
    1,
    (row) => sqlite.integer.decode(row[0]),
  );
}

export type MemberByHandleArgs = {|
  readonly handle: string,
|};

export type MemberByHandleRow = {|
  readonly id: string,
  readonly name: string,
  readonly handle: string,
  readonly bio: string,
  readonly passwordHash: string | null,
|};

const memberByHandleSql = `SELECT id, name, handle, bio, password_hash
FROM members
WHERE handle = ?`;

export function memberByHandle(
  db: SyncQueryable,
  args: MemberByHandleArgs,
): MemberByHandleRow | null {
  return sql.oneSync(
    db,
    "MemberByHandle",
    memberByHandleSql,
    [sqlite.string.encode(args.handle)],
    5,
    (row) => ({
      id: sqlite.string.decode(row[0]),
      name: sqlite.string.decode(row[1]),
      handle: sqlite.string.decode(row[2]),
      bio: sqlite.string.decode(row[3]),
      passwordHash: sqlite.nullable(sqlite.string, row[4]),
    }),
  );
}

export type InsertMemberArgs = {|
  readonly id: string,
  readonly name: string,
  readonly handle: string,
  readonly email: string,
  readonly passwordHash: string | null,
|};

const insertMemberSql = `INSERT INTO members (id, name, handle, email, password_hash)
VALUES (?, ?, ?, ?, ?)`;

export function insertMember(db: SyncQueryable, args: InsertMemberArgs): void {
  return sql.execSync(db, "InsertMember", insertMemberSql, [
    sqlite.string.encode(args.id),
    sqlite.string.encode(args.name),
    sqlite.string.encode(args.handle),
    sqlite.string.encode(args.email),
    sqlite.param(sqlite.string, args.passwordHash),
  ]);
}

export type DeleteAttemptsArgs = {|
  readonly handle: string,
|};

const deleteAttemptsSql = `DELETE FROM auth_attempts
WHERE handle = ?`;

export function deleteAttempts(db: SyncQueryable, args: DeleteAttemptsArgs): void {
  return sql.execSync(db, "DeleteAttempts", deleteAttemptsSql, [sqlite.string.encode(args.handle)]);
}

export type DeleteSessionArgs = {|
  readonly tokenHash: string,
|};

const deleteSessionSql = `DELETE FROM sessions
WHERE token_hash = ?`;

export function deleteSession(db: SyncQueryable, args: DeleteSessionArgs): void {
  return sql.execSync(db, "DeleteSession", deleteSessionSql, [
    sqlite.string.encode(args.tokenHash),
  ]);
}

export type DeleteExpiredSessionsArgs = {|
  readonly expiresAt: number,
|};

const deleteExpiredSessionsSql = `DELETE FROM sessions
WHERE expires_at <= ?`;

export function deleteExpiredSessions(db: SyncQueryable, args: DeleteExpiredSessionsArgs): void {
  return sql.execSync(db, "DeleteExpiredSessions", deleteExpiredSessionsSql, [
    sqlite.integer.encode(args.expiresAt),
  ]);
}

export type InsertSessionArgs = {|
  readonly tokenHash: string,
  readonly memberId: string,
  readonly expiresAt: number,
|};

const insertSessionSql = `INSERT INTO sessions (token_hash, member_id, expires_at)
VALUES (?, ?, ?)`;

export function insertSession(db: SyncQueryable, args: InsertSessionArgs): void {
  return sql.execSync(db, "InsertSession", insertSessionSql, [
    sqlite.string.encode(args.tokenHash),
    sqlite.string.encode(args.memberId),
    sqlite.integer.encode(args.expiresAt),
  ]);
}
