// Generated by uf from input.js. Do not edit.

export declare const count: unknown;

export declare function guess(value: string): unknown;



export declare const named: string;

declare const _default: unknown;
export default _default;
