[package]
name = "uf_pm"
description = "Native package manager contracts for @uniflowed/pm."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
camino.workspace = true
compact_str.workspace = true
serde.workspace = true
serde_json.workspace = true
smallvec.workspace = true
thiserror.workspace = true
uf_config = { path = "../uf_config" }

[dev-dependencies]
tempfile.workspace = true
