//! An offline documentation site using uf's own visual language.

use std::fs;

use camino::{Utf8Path, Utf8PathBuf};
use ox_content_allocator::Allocator;
use ox_content_ast::Node;
use ox_content_parser::{Parser, ParserOptions};
use ox_content_renderer::{
    HtmlRenderContext, HtmlRenderControl, HtmlRenderHooks, HtmlRenderer, HtmlRendererOptions,
};

use crate::{DocError, DocModule, DocReport, render_markdown_with};

/// Render Flow API documentation as an accessible, standalone HTML page.
///
/// ox-content parses and renders the Markdown body. uf owns the page shell,
/// navigation and styling. Raw HTML in documentation comments is escaped.
pub fn render_html(report: &DocReport, title: &str) -> Result<String, DocError> {
    let (markdown, offsets) = source(report);
    render_page(report, title, &markdown, &offsets)
}

fn source(report: &DocReport) -> (String, uf_infra::InlineVec<usize, 16>) {
    let mut offsets = uf_infra::InlineVec::with_capacity(report.modules.len());
    let markdown = render_markdown_with(report, |offset| offsets.push(offset));
    (markdown, offsets)
}

// Filenames can share a Markdown slug, and description headings can precede a
// module with the same slug. Match native source spans to the generated module
// headings and give those stable, independent anchors.
struct Modules<'a> {
    offsets: &'a [usize],
    modules: &'a [DocModule],
    next: usize,
}

impl HtmlRenderHooks for Modules<'_> {
    fn render_node(
        &mut self,
        node: &Node<'_>,
        cx: &mut HtmlRenderContext<'_>,
    ) -> HtmlRenderControl {
        if let Node::Heading(heading) = node
            && heading.depth == 2
            && self.offsets.get(self.next).copied() == Some(heading.span.start as usize)
        {
            cx.write("<h2 id=\"uf:module:");
            cx.write_display(self.next);
            cx.write("\">");
            cx.write_escaped(&self.modules[self.next].path);
            cx.write("</h2>\n");
            self.next += 1;
            return HtmlRenderControl::Handled;
        }
        HtmlRenderControl::Default
    }
}

fn render_page(
    report: &DocReport,
    title: &str,
    markdown: &str,
    offsets: &[usize],
) -> Result<String, DocError> {
    let arena = Allocator::for_source_len(markdown.len());
    let document = Parser::with_options(&arena, markdown, ParserOptions::gfm()).parse()?;
    let mut renderer = HtmlRenderer::with_options(HtmlRendererOptions {
        sanitize: true,
        ..HtmlRendererOptions::default()
    });
    let mut modules = Modules {
        offsets,
        modules: &report.modules,
        next: 0,
    };
    let body = renderer.render_borrowed_with_hooks(&document, &mut modules);
    let mut out = String::with_capacity(body.len() + 2048 + report.modules.len() * 96);
    out.push_str("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><meta name=\"color-scheme\" content=\"light dark\"><title>");
    escape(&mut out, title);
    out.push_str(" — API · uf</title><link rel=\"icon\" href=\"uf-mark.svg\"><link rel=\"stylesheet\" href=\"uf-tokens.css\"><link rel=\"stylesheet\" href=\"uf-doc.css\"></head><body><a class=\"skip\" href=\"#content\">Skip to content</a><div class=\"shell\"><header class=\"masthead\"><a class=\"brand\" href=\"#content\"><img src=\"uf-mark.svg\" width=\"24\" height=\"24\" alt=\"\">uf<span>API reference</span></a><span class=\"project\">");
    escape(&mut out, title);
    out.push_str("</span></header><div class=\"manual\"><nav class=\"sidebar\" aria-label=\"Modules\"><h2>Modules</h2><ul>");
    for (index, module) in report.modules.iter().enumerate() {
        uf_infra::append!(out, "<li><a href=\"#uf:module:{}\">", index);
        escape(&mut out, &module.path);
        out.push_str("</a></li>");
    }
    out.push_str("</ul></nav><main id=\"content\" class=\"prose\" tabindex=\"-1\">");
    out.push_str(body);
    out.push_str("</main></div><footer>Generated by <code>uf doc</code> · <a href=\"api.md\">Markdown source</a></footer></div></body></html>\n");
    Ok(out)
}

/// Write `index.html`, `api.md` and the local uf design assets.
///
/// The directory can be opened directly or served by any static host. No
/// JavaScript, npm install or external font request is needed to read it.
pub fn write_site(
    report: &DocReport,
    out_dir: &Utf8Path,
    title: &str,
) -> Result<Utf8PathBuf, DocError> {
    let (markdown, offsets) = source(report);
    let html = render_page(report, title, &markdown, &offsets)?;
    fs::create_dir_all(out_dir).map_err(|source| DocError::Write {
        path: out_dir.to_path_buf(),
        source,
    })?;
    for (name, content) in [
        ("api.md", markdown.as_str()),
        ("index.html", html.as_str()),
        ("uf-doc.css", include_str!("site.css")),
        ("uf-tokens.css", include_str!("../../../brand/tokens.css")),
        (
            "uf-mark.svg",
            include_str!("../../../brand/favicon.svg"),
        ),
    ] {
        let path = out_dir.join(name);
        fs::write(&path, content).map_err(|source| DocError::Write { path, source })?;
    }
    Ok(out_dir.join("index.html"))
}

fn escape(out: &mut String, text: &str) {
    let mut start = 0;
    for (index, byte) in text.bytes().enumerate() {
        let escaped = match byte {
            b'&' => "&amp;",
            b'<' => "&lt;",
            b'>' => "&gt;",
            b'\"' => "&quot;",
            b'\'' => "&#39;",
            _ => continue,
        };
        out.push_str(&text[start..index]);
        out.push_str(escaped);
        start = index + 1;
    }
    out.push_str(&text[start..]);
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{DocEntry, DocKind, DocModule, render_markdown};

    #[test]
    fn generated_site_has_flow_signatures_gfm_and_local_uf_assets() {
        let report = DocReport {
            files_scanned: 1,
            modules: vec![DocModule {
                path: "src/api.js".into(),
                entries: vec![DocEntry {
                    name: "UserId".into(),
                    kind: DocKind::OpaqueType,
                    line: 3,
                    signature: "export opaque type UserId = string;".into(),
                    description: "| Field | Value |\n| --- | --- |\n| id | stable |\n\n<script>alert(1)</script>".into(),
                    tags: vec![],
                }],
            }],
            ..DocReport::default()
        };
        let dir = tempfile::tempdir().unwrap();
        let root = Utf8Path::from_path(dir.path()).unwrap();
        let output = write_site(&report, root, "Project <&\" 漢字").unwrap();
        let html = fs::read_to_string(output).unwrap();
        assert!(html.contains("Project &lt;&amp;&quot; 漢字"));
        assert!(html.contains("<table>"));
        assert!(html.contains("export opaque type UserId = string;"));
        assert!(!html.contains("<script>"));
        assert!(html.contains("&lt;script&gt;"));
        assert!(html.contains("href=\"#uf:module:0\""));
        assert!(html.contains("id=\"uf:module:0\""));
        for asset in ["api.md", "uf-doc.css", "uf-tokens.css", "uf-mark.svg"] {
            assert!(root.join(asset).is_file(), "missing {asset}");
        }
        assert_eq!(
            fs::read_to_string(root.join("api.md")).unwrap(),
            render_markdown(&report)
        );
    }

    #[test]
    fn module_navigation_remains_unique_when_filenames_share_a_slug() {
        let report = DocReport {
            modules: ["src/a.b.js", "src/ab.js"]
                .into_iter()
                .map(|path| DocModule {
                    path: path.into(),
                    entries: vec![],
                })
                .collect(),
            ..DocReport::default()
        };
        let html = render_html(&report, "Project").unwrap();
        for index in 0..2 {
            let id = uf_infra::cstr!("id=\"uf:module:{}\"", index);
            let href = uf_infra::cstr!("href=\"#uf:module:{}\"", index);
            assert_eq!(html.matches(id.as_str()).count(), 1);
            assert!(html.contains(href.as_str()));
        }
    }
}
