// Generated by uf from input.js. Do not edit.

export declare class Store<T> {
  size: number;
  readonly name: string;


  constructor(initial: T);





  static create(): Store<unknown>;



  get current(): T;



  run(input: string): number;
}



declare class Remote {
  url: string;
  fetch(path: string): Promise<string>;
}

export type Fetcher = Remote;
