[package]
name = "uniflowed_fmt"
description = "Native formatter runner primitives for uniflowed."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
uniflowed_config = { path = "../uniflowed_config" }
thiserror.workspace = true

[dev-dependencies]
similar-asserts.workspace = true
