// Generated by uf from input.js. Do not edit.

declare const Id$brand: unique symbol;
export type Id = { readonly [Id$brand]: "Id" };
declare const Token$brand: unique symbol;
export type Token = string & { readonly [Token$brand]: "Token" };
export declare function makeId(raw: string): Id;



export declare function readId(id: Id): string;



export declare function useToken(token: Token): string;
