// Generated by uf from input.js. Do not edit.

export type Pair = [string, number];

export type Labelled = [first: string, second?: number];

export type Spread = [string, ...Array<number>];

export type Loose = [string];

export type Empty = [];
