[package]
name = "uniflowed_lib"
description = "Native modules exposed to Flow for the Unified Toolchain for Flow (React)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
compact_str.workspace = true
uniflowed_infra = { path = "../uniflowed_infra" }
serde.workspace = true
