// Generated by uf from input.js. Do not edit.

export interface Serializable {
  serialize(): string;
}

export interface Keyed<K, V> extends Serializable {
  readonly key: K;
  get(key: K): V | null | undefined;
}

export type Anonymous = { size: number };
