[package]
name = "uf_rm"
description = "Runtime manager contracts for @uniflowed/rm."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
compact_str.workspace = true
serde.workspace = true
smallvec.workspace = true
uf_config = { path = "../uf_config" }
uf_runtime = { path = "../uf_runtime" }
