[package]
name = "uf_devserver"
description = "Access-controlled development HTTP server for the Unified Toolchain for Flow (React)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
uf_config = { path = "../uf_config" }
uf_infra = { path = "../uf_infra" }
uf_rsc = { path = "../uf_rsc" }
uf_term = { path = "../uf_term" }
camino.workspace = true
compact_str.workspace = true
serde.workspace = true
serde_json.workspace = true
smallvec.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true
tempfile.workspace = true

[[bench]]
name = "invalidate"
harness = false
