//! Lockfile evidence: which manager it names, and when it is ambiguous.

use super::*;

#[test]
fn empty_directory_defaults_to_uf_native() {
    let (_guard, root) = temp_root();

    let detection = detect_within(&root, &root);

    assert_eq!(detection.package_manager, PackageManager::Uf);
    assert_eq!(detection.source, DetectionSource::Default);
    assert_eq!(detection.source.kind(), "default");
    assert!(detection.alternatives.is_empty());
    assert!(detection.issues.is_empty());
    assert!(detection.is_uf_native());
    assert!(!detection.is_ambiguous());
}

#[test]
fn uf_lock_detects_the_native_resolver() {
    let (_guard, root) = temp_root();
    write(&root.join("uf.lock"), "{}\n");

    let detection = detect_within(&root, &root);

    assert_eq!(detection.package_manager, PackageManager::Uf);
    assert_eq!(detection.source.kind(), "lockfile");
}

#[test]
fn pnpm_lockfile_detects_pnpm() {
    let (_guard, root) = temp_root();
    write(&root.join("pnpm-lock.yaml"), "lockfileVersion: '9.0'\n");

    let detection = detect_within(&root, &root);

    assert_eq!(detection.package_manager, PackageManager::Pnpm);
    assert_eq!(
        detection.source,
        DetectionSource::Lockfile {
            lockfile: Lockfile::PnpmLock,
            path: root.join("pnpm-lock.yaml"),
        }
    );
}

#[test]
fn package_lock_detects_npm() {
    let (_guard, root) = temp_root();
    write(&root.join("package-lock.json"), "{}\n");

    assert_eq!(
        detect_within(&root, &root).package_manager,
        PackageManager::Npm
    );
}

#[test]
fn npm_shrinkwrap_detects_npm() {
    let (_guard, root) = temp_root();
    write(&root.join("npm-shrinkwrap.json"), "{}\n");

    assert_eq!(
        detect_within(&root, &root).package_manager,
        PackageManager::Npm
    );
}

#[test]
fn bun_text_lockfile_detects_bun() {
    let (_guard, root) = temp_root();
    write(&root.join("bun.lock"), "{}\n");

    assert_eq!(
        detect_within(&root, &root).package_manager,
        PackageManager::Bun
    );
}

#[test]
fn bun_binary_lockfile_detects_bun() {
    let (_guard, root) = temp_root();
    write(&root.join("bun.lockb"), "\0binary\n");

    assert_eq!(
        detect_within(&root, &root).package_manager,
        PackageManager::Bun
    );
}

#[test]
fn both_bun_lockfiles_are_one_manager_not_an_ambiguity() {
    let (_guard, root) = temp_root();
    write(&root.join("bun.lock"), "{}\n");
    write(&root.join("bun.lockb"), "\0binary\n");

    let detection = detect_within(&root, &root);

    assert_eq!(detection.package_manager, PackageManager::Bun);
    assert!(!detection.is_ambiguous());
    assert_eq!(detection.alternatives.len(), 1);
}

#[test]
fn plain_yarn_lock_detects_yarn_classic() {
    let (_guard, root) = temp_root();
    write(&root.join("yarn.lock"), "# yarn lockfile v1\n\n");

    assert_eq!(
        detect_within(&root, &root).package_manager,
        PackageManager::Yarn(YarnEdition::Classic)
    );
}

#[test]
fn yarn_lock_metadata_header_detects_berry() {
    let (_guard, root) = temp_root();
    write(
        &root.join("yarn.lock"),
        "# This file is generated by running \"yarn install\"\n\n__metadata:\n  version: 8\n",
    );

    assert_eq!(
        detect_within(&root, &root).package_manager,
        PackageManager::Yarn(YarnEdition::Berry)
    );
}

#[test]
fn yarnrc_yml_detects_berry_even_without_a_lockfile_header() {
    let (_guard, root) = temp_root();
    write(&root.join("yarn.lock"), "");
    write(&root.join(".yarnrc.yml"), "nodeLinker: node-modules\n");

    assert_eq!(
        detect_within(&root, &root).package_manager,
        PackageManager::Yarn(YarnEdition::Berry)
    );
}

#[test]
fn yarn_edition_probe_ignores_a_huge_lockfile_tail() {
    let (_guard, root) = temp_root();
    let mut lock = String::from("# yarn lockfile v1\n");
    lock.push_str(&"# padding\n".repeat(4096));
    lock.push_str("__metadata:\n");
    write(&root.join("yarn.lock"), &lock);

    // The `__metadata:` marker sits past the probe window, so the header wins.
    assert_eq!(yarn_edition_in(&root), YarnEdition::Classic);
}

#[test]
fn side_by_side_lockfiles_report_ambiguity_without_silently_picking() {
    let (_guard, root) = temp_root();
    write(&root.join("pnpm-lock.yaml"), "lockfileVersion: '9.0'\n");
    write(&root.join("package-lock.json"), "{}\n");
    write(&root.join("yarn.lock"), "# yarn lockfile v1\n");

    let detection = detect_within(&root, &root);

    assert_eq!(detection.package_manager, PackageManager::Pnpm);
    assert!(detection.is_ambiguous());
    let DetectionOutcome::Ambiguous { lockfiles } = &detection.outcome else {
        panic!("expected an ambiguous outcome");
    };
    assert_eq!(
        lockfiles.as_slice(),
        [
            Lockfile::PnpmLock,
            Lockfile::YarnLock,
            Lockfile::PackageLock
        ]
    );
    assert_eq!(detection.alternatives.len(), 2);
}

#[test]
fn uf_lock_outranks_every_other_lockfile() {
    let (_guard, root) = temp_root();
    for lockfile in Lockfile::ALL {
        write(&root.join(lockfile.file_name()), "");
    }

    let detection = detect_within(&root, &root);

    assert_eq!(detection.package_manager, PackageManager::Uf);
    assert!(detection.is_ambiguous());
    assert_eq!(detection.alternatives.len(), Lockfile::ALL.len() - 1);
}
