[package]
name = "uf_orm"
description = "Native type-safe ORM contracts for @uniflowed/orm."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
compact_str.workspace = true
serde.workspace = true
smallvec.workspace = true
