//! The table of every `@uniflowed/*` module uf ships, and the hooks beside it.
//!
//! Deliberately long and deliberately flat: this is data, not logic. It is the
//! one list that says which specifiers exist, how stable each is, and what Flow
//! names it exports, so a module that is not here does not exist as far as the
//! toolchain is concerned.

use uf_std::{StdModule, std_modules};
use uf_tui::TuiFrameworkContract;

use crate::descriptor::{HookDescriptor, NativeModule, NativeModuleKind, Stability};

pub fn builtin_modules() -> Vec<NativeModule> {
    vec![
        NativeModule::new(
            "@uniflowed/core",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &[
                "describe",
                "it",
                "test",
                "expect",
                "beforeEach",
                "afterEach",
            ],
        ),
        NativeModule::new(
            "@uniflowed/react",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["Node", "React", "SetState", "Suspense", "use", "cache"],
        ),
        NativeModule::new(
            "@uniflowed/react-native",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["View", "Text", "Platform"],
        ),
        NativeModule::new(
            "@uniflowed/brand",
            NativeModuleKind::Style,
            Stability::Experimental,
            &[
                "ufBrand",
                "ufBrandAssets",
                "ufPalette",
                "ufTextScale",
                "ufSpacingScale",
                "ufRadiusScale",
                "ufCommands",
            ],
        ),
        NativeModule::new(
            "@uniflowed/testing",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &["describe", "it", "test", "expect", "fn", "render", "screen"],
        ),
        NativeModule::new(
            "@uniflowed/test",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &[
                "describe",
                "it",
                "test",
                "expect",
                "fn",
                "spyOn",
                "uft",
                "beforeAll",
                "afterAll",
                "beforeEach",
                "afterEach",
            ],
        ),
        NativeModule::new(
            "@uniflowed/react-testing",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &[
                "render",
                "screen",
                "within",
                "fireEvent",
                "userEvent",
                "waitFor",
                "cleanup",
                "act",
                "dispatch",
                "normalize",
                "accessibleName",
                "roleOf",
            ],
        ),
        NativeModule::new(
            "@uniflowed/hooks",
            NativeModuleKind::Hooks,
            Stability::Experimental,
            &[
                "useAsync",
                "useClickOutside",
                "useCounter",
                "useDebouncedCallback",
                "useDebouncedValue",
                "useDocumentVisible",
                "useElementRef",
                "useElementSize",
                "useEventListener",
                "useFocusWithin",
                "useHover",
                "useIntersecting",
                "useInterval",
                "useIsomorphicLayoutEffect",
                "useMediaQuery",
                "useMount",
                "useMounted",
                "useOnline",
                "usePreferredColorScheme",
                "usePrefersReducedMotion",
                "usePrevious",
                "useRerender",
                "useStableCallback",
                "useStorage",
                "useThrottledCallback",
                "useTimeout",
                "useToggle",
                "useUnmount",
                "useWindowSize",
            ],
        ),
        NativeModule::new(
            "@uniflowed/router",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &[
                "FileRoute",
                "loader",
                "action",
                "redirect",
                "useRoute",
                "useRouter",
                "defineNavigationGuard",
            ],
        ),
        NativeModule::new(
            "@uniflowed/server",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["serverAction", "headers", "cookies", "cache"],
        ),
        NativeModule::new(
            "@uniflowed/query",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "CancelledError",
                "DEFAULT_GC_TIME",
                "InfiniteQueryObserver",
                "Mutation",
                "Presence",
                "Query",
                "QueryCache",
                "QueryClient",
                "QueryClientProvider",
                "QueryObserver",
                "backoffDelay",
                "hashKey",
                "infinitePages",
                "matchesKey",
                "structuralShare",
                "useInfiniteQuery",
                "useMutation",
                "useQuery",
                "useQueryClient",
            ],
        ),
        NativeModule::new(
            "@uniflowed/fetch",
            NativeModuleKind::Data,
            Stability::Experimental,
            &["FetchError", "createFetch"],
        ),
        NativeModule::new(
            "@uniflowed/loader",
            NativeModuleKind::Data,
            Stability::Experimental,
            &["createLoader", "useLoader", "loaderCell", "preload"],
        ),
        NativeModule::new(
            "@uniflowed/effect",
            NativeModuleKind::Effect,
            Stability::Experimental,
            &[
                "succeed",
                "fail",
                "die",
                "sync",
                "suspend",
                "promise",
                "tryPromise",
                "call",
                "effect",
                "map",
                "mapError",
                "flatMap",
                "andThen",
                "zip",
                "all",
                "forEach",
                "race",
                "catchAll",
                "catchTag",
                "orElse",
                "either",
                "retry",
                "timeout",
                "acquireRelease",
                "scoped",
                "tag",
                "provide",
                "provideService",
                "fork",
                "join",
                "interrupt",
                "runPromise",
                "runSyncExit",
                "runFork",
            ],
        ),
        NativeModule::new(
            "@uniflowed/orm",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "defineTable",
                "column",
                "relation",
                "query",
                "migration",
                "db",
            ],
        ),
        NativeModule::new(
            "@uniflowed/relay",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "graphql",
                "useFragment",
                "useLazyLoadQuery",
                "usePreloadedQuery",
                "useMutation",
                "commitMutation",
                "RelayEnvironmentProvider",
                "loadQuery",
            ],
        ),
        NativeModule::new(
            "@uniflowed/graphql",
            NativeModuleKind::Data,
            Stability::Experimental,
            &["createEnvironment", "GraphQlResponseError", "Observable"],
        ),
        NativeModule::new(
            "@uniflowed/web",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &[
                "Font",
                "Image",
                "OgImage",
                "Link",
                "Page",
                "Layout",
                "Time",
                "Announcer",
                "Picture",
                "useCookie",
                "useHead",
            ],
        ),
        NativeModule::new(
            "@uniflowed/markdown",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "Markdown",
                "renderMarkdown",
                "compileMarkdown",
                "Mdx",
                "renderMdx",
                "compileMdx",
            ],
        ),
        NativeModule::new(
            "@uniflowed/temporal",
            NativeModuleKind::Data,
            Stability::Experimental,
            &["Temporal", "Instant", "PlainDate", "ZonedDateTime"],
        ),
        NativeModule::new(
            "@uniflowed/pwa",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["definePwa", "Manifest", "ServiceWorker"],
        ),
        NativeModule::new(
            "@uniflowed/prepare",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &["prepare", "lintStaged", "codegen"],
        ),
        NativeModule::new(
            "@uniflowed/pm",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &["inferFromConfig", "install", "upgrade", "lock", "store"],
        ),
        NativeModule::new(
            "@uniflowed/rm",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &["inferRuntime", "acquireRuntime", "applyRuntime", "doctor"],
        ),
        NativeModule::new(
            "@uniflowed/cell",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "batch",
                "cell",
                "computed",
                "effect",
                "peek",
                "read",
                "refresh",
                "resource",
                "snapshot",
                "status",
                "subscribe",
                "untracked",
                "update",
                "write",
            ],
        ),
        NativeModule::new(
            "@uniflowed/state",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "Provider",
                "action",
                "asyncAtom",
                "atom",
                "atomFamily",
                "atomWithDefault",
                "atomWithStorage",
                "createStore",
                "getDefaultStore",
                "selector",
                "unwrap",
                "useAtom",
                "useAtomValue",
                "useCell",
                "useSetAtom",
                "writableSelector",
            ],
        ),
        NativeModule::new(
            "@uniflowed/validator",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "v",
                "string",
                "number",
                "boolean",
                "unknown",
                "literal",
                "enum_",
                "array",
                "tuple",
                "union",
                "object",
                "strictObject",
                "partial",
                "optional",
                "nullable",
                "pipe",
                "transform",
                "brand",
                "email",
                "date",
                "instance",
                "parse",
                "safeParse",
            ],
        ),
        NativeModule::new(
            "@uniflowed/immer",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "produce",
                "produceWithPatches",
                "applyPatches",
                "original",
                "current",
                "isDraft",
                "isDraftable",
                "freeze",
                "setAutoFreeze",
                "Draft",
                "Patch",
            ],
        ),
        NativeModule::new(
            "@uniflowed/mock",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &["mock", "get", "post", "use"],
        ),
        NativeModule::new(
            "@uniflowed/browser",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &["browser", "viewport", "visit", "screenshot"],
        ),
        NativeModule::new(
            "@uniflowed/story",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &["story", "variant", "withMocks", "withBrowser"],
        ),
        NativeModule::new(
            "@uniflowed/vrt",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &["plan", "snapshot", "diff", "baseline"],
        ),
        NativeModule::new(
            "@uniflowed/motion",
            NativeModuleKind::Ui,
            Stability::Experimental,
            &["motion", "animate", "timeline", "spring", "reducedMotion"],
        ),
        NativeModule::new(
            "@uniflowed/tui",
            NativeModuleKind::Ui,
            Stability::Experimental,
            &[
                "Box",
                "Text",
                "Input",
                "Select",
                "ScrollBox",
                "FrameBuffer",
                "renderTui",
                "contract",
            ],
        ),
        NativeModule::new(
            "@uniflowed/cli",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &["defineCli", "command", "arg", "option"],
        ),
        NativeModule::new(
            "@uniflowed/std",
            NativeModuleKind::Std,
            Stability::Experimental,
            &[
                "modules",
                "wintertc",
                "vfs",
                "fs",
                "crypto",
                "http",
                "buffer",
                "importMeta",
                "defer",
            ],
        ),
        NativeModule::new(
            "@uniflowed/stylex",
            NativeModuleKind::Style,
            Stability::Experimental,
            &["stylex", "defineVars", "createTheme"],
        ),
        NativeModule::new(
            "@uniflowed/ui",
            NativeModuleKind::Ui,
            Stability::Experimental,
            &[
                "Checkbox", "Combobox", "Dialog", "Field", "Menu", "Switch", "Tabs",
            ],
        ),
        NativeModule::new(
            "@uniflowed/react-compiler",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["compiler", "syntaxMode"],
        ),
        // Imported by generated code rather than by hand: `uf build` injects
        // the import when it lowers a module's JSX.
        NativeModule::new(
            "@uniflowed/jsx-runtime",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["jsx", "jsxs", "Fragment"],
        ),
        NativeModule::new(
            "@uniflowed/runtime",
            NativeModuleKind::Runtime,
            Stability::Planned,
            &["run", "resolve", "spawn"],
        ),
        NativeModule::new(
            "@uniflowed/lib",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &["modules", "hooks", "ui", "version"],
        ),
        NativeModule::new(
            "@uniflowed/lint",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["defineRule", "typeAwareRule", "reactRule"],
        ),
        NativeModule::new(
            "@uniflowed/form",
            NativeModuleKind::Ui,
            Stability::Experimental,
            &[
                "useForm",
                "useFieldArray",
                "useWatch",
                "useFormState",
                "useController",
                "Controller",
                "FormProvider",
                "useFormContext",
                "validatorResolver",
            ],
        ),
    ]
}

pub fn std_module_descriptors() -> Vec<StdModule> {
    std_modules().into_iter().collect()
}

pub fn tui_contract() -> TuiFrameworkContract {
    TuiFrameworkContract::default()
}

pub fn hook_descriptors() -> Vec<HookDescriptor> {
    vec![
        HookDescriptor::new("useAsync", true, false),
        HookDescriptor::new("useDebouncedValue", true, false),
        HookDescriptor::new("useEvent", true, false),
        HookDescriptor::new("useInterval", true, false),
        HookDescriptor::new("useIsomorphicLayoutEffect", true, false),
        HookDescriptor::new("useLocalStorage", true, false),
        HookDescriptor::new("useMediaQuery", true, false),
        HookDescriptor::new("useMounted", true, false),
        HookDescriptor::new("usePrevious", true, false),
        HookDescriptor::new("useStableCallback", true, false),
        HookDescriptor::new("useServerValue", true, true),
    ]
}

pub fn module_by_specifier(specifier: &str) -> Option<NativeModule> {
    builtin_modules()
        .into_iter()
        .find(|module| module.specifier == specifier)
}
