//! The table of every `@uniflowed/*` module uf ships, and the hooks beside it.
//!
//! Deliberately long and deliberately flat: this is data, not logic. It is the
//! one list that says which specifiers exist, how stable each is, and what Flow
//! names it exports, so a module that is not here does not exist as far as the
//! toolchain is concerned.
//!
//! # What the export list is, exactly
//!
//! **Every value the package's entry point exports, and nothing else.**
//!
//! Two readings were possible — every export, or the names an editor should
//! suggest — and the data settled it rather than taste. Twenty-nine of the
//! forty-four entries already matched their package exactly, including the four
//! largest: `@uniflowed/effect` at 71 names — 91 since #325 to #329 —
//! `@uniflowed/validator` at 73, `@uniflowed/hooks` at 52, `@uniflowed/state`
//! at 24. A hand-curated list does
//! not come out exact for seventy-three names by accident. The fifteen that
//! disagreed were drift, and `the_registry_names_exactly_what_each_package_exports`
//! is what stops them drifting again.
//!
//! **Values, not types.** No entry had ever listed one, and there is a reason
//! beyond habit: a type is imported with `import type`, which the checker
//! resolves through the file itself, so this table is not what answers for it.
//! This table answers "what can I import and call".
//!
//! **A name that is not exported does not belong here**, however much it ought
//! to exist. `uf dev`'s hover prints this list to a person as "Flow exports:
//! …", so a name in it that the package does not export is the editor telling
//! somebody they can import something that fails at run time. Planned names
//! belong in an issue.
//!
//! Two entries cannot be checked and are named in the test rather than left to
//! be noticed: `@uniflowed/react` and `@uniflowed/relay` hand on another
//! package's whole surface with `export * from`, so their names are not in the
//! file to be read.

use uf_std::{StdModule, std_modules};
use uf_tui::TuiFrameworkContract;

use crate::descriptor::{HookDescriptor, NativeModule, NativeModuleKind, Stability};

pub fn builtin_modules() -> Vec<NativeModule> {
    vec![
        NativeModule::new(
            "@uniflowed/core",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &[
                "afterAll",
                "afterEach",
                "beforeAll",
                "beforeEach",
                "defineConfig",
                "describe",
                "expect",
                "fn",
                "it",
                "test",
            ],
        ),
        NativeModule::new(
            "@uniflowed/config",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &["defineConfig"],
        ),
        NativeModule::new(
            "@uniflowed/react",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["Node", "React", "SetState", "Suspense", "use", "cache"],
        ),
        NativeModule::new(
            "@uniflowed/react-native",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &[
                "ReactNative",
                "View",
                "Text",
                "Image",
                "TextInput",
                "Pressable",
                "ScrollView",
                "StyleSheet",
                "Platform",
            ],
        ),
        NativeModule::new(
            "@uniflowed/brand",
            NativeModuleKind::Style,
            Stability::Experimental,
            &[
                "ufBrand",
                "ufBrandAssets",
                "ufPalette",
                "ufTextScale",
                "ufSpacingScale",
                "ufRadiusScale",
                "ufCommands",
            ],
        ),
        NativeModule::new(
            "@uniflowed/testing",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &[
                "AssertionError",
                "act",
                "afterAll",
                "afterEach",
                "beforeAll",
                "beforeEach",
                "bench",
                "cleanup",
                "describe",
                "expect",
                "fireEvent",
                "fn",
                "it",
                "render",
                "screen",
                "test",
                "userEvent",
                "waitFor",
                "within",
            ],
        ),
        NativeModule::new(
            "@uniflowed/test",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &[
                "AssertionError",
                "DEFAULT_TIMEOUT_MS",
                "NAME_SEPARATOR",
                "RunawayTimersError",
                "UnsupportedError",
                "afterAll",
                "afterEach",
                "beforeAll",
                "beforeEach",
                "bench",
                "describe",
                "equals",
                "expect",
                "fn",
                "it",
                "render",
                "spyOn",
                "test",
                "uft",
            ],
        ),
        NativeModule::new(
            "@uniflowed/react-testing",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &[
                "render",
                "screen",
                "within",
                "fireEvent",
                "userEvent",
                "waitFor",
                "cleanup",
                "act",
                "dispatch",
                "normalize",
                "accessibleName",
                "roleOf",
            ],
        ),
        NativeModule::new(
            "@uniflowed/react-native-testing",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &[
                "NativeTestingUnsupportedError",
                "accessibilityStateOf",
                "accessibilityValueOf",
                "accessibleName",
                "createNativeScreen",
                "render",
                "roleOf",
                "textContent",
                "within",
            ],
        ),
        NativeModule::new(
            "@uniflowed/hooks",
            NativeModuleKind::Hooks,
            Stability::Experimental,
            &[
                "RENDER_META",
                "RenderProvider",
                "browserWindow",
                "useAnimationFrame",
                "useAsync",
                "useBroadcast",
                "useClickOutside",
                "useClipboard",
                "useCounter",
                "useCycle",
                "useDebouncedCallback",
                "useDebouncedValue",
                "useDocumentVisible",
                "useElementRef",
                "useElementSize",
                "useElementState",
                "useEventListener",
                "useEventSource",
                "useFocusWithin",
                "useGeolocation",
                "useHash",
                "useHover",
                "useIdle",
                "useIntersecting",
                "useInterval",
                "useIsomorphicLayoutEffect",
                "useKeyCombo",
                "useKeyHeld",
                "useList",
                "useLongPress",
                "useMediaQuery",
                "useMount",
                "useMounted",
                "useMutationObserver",
                "useNetwork",
                "useNow",
                "useOnline",
                "usePermission",
                "usePreferredColorScheme",
                "usePrefersReducedMotion",
                "usePrevious",
                "useRandom",
                "useRenderEnvelope",
                "useRenderTimeZone",
                "useRenderedAt",
                "useRerender",
                "useScroll",
                "useScrollLock",
                "useSet",
                "useShuffled",
                "useStableCallback",
                "useStorage",
                "useSupported",
                "useThrottledCallback",
                "useTimeAgo",
                "useTimeout",
                "useToggle",
                "useUndoable",
                "useUnmount",
                "useWindowScroll",
                "useWindowSize",
            ],
        ),
        NativeModule::new(
            "@uniflowed/router",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &[
                "ForbiddenError",
                "Link",
                "NotFoundError",
                "RedirectError",
                "RouteView",
                "RouterProvider",
                "UnauthorizedError",
                "basePath",
                "buildRoute",
                "forbidden",
                "hasClientPage",
                "matchRoute",
                "notFound",
                "parseSearch",
                "permanentRedirect",
                "redirect",
                "resolveFailure",
                "resolveMatch",
                "routeErrorStatus",
                "routerView",
                "splitUrl",
                "unauthorized",
                "useIsServer",
                "useLoaderData",
                "useRoute",
                "useRouter",
                "useSeo",
            ],
        ),
        NativeModule::new(
            "@uniflowed/server",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &[
                "DraftModeError",
                "OutsideRequestError",
                "after",
                "cookies",
                "draftMode",
                "headers",
                "logger",
                "requestId",
            ],
        ),
        NativeModule::new(
            "@uniflowed/query",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "CancelledError",
                "DEFAULT_GC_TIME",
                "InfiniteQueryObserver",
                "Mutation",
                "Presence",
                "Query",
                "QueryCache",
                "QueryClient",
                "QueryClientProvider",
                "QueryObserver",
                "backoffDelay",
                "hashKey",
                "infinitePages",
                "matchesKey",
                "structuralShare",
                "useInfiniteQuery",
                "useMutation",
                "useQuery",
                "useQueryClient",
            ],
        ),
        NativeModule::new(
            "@uniflowed/fetch",
            NativeModuleKind::Data,
            Stability::Experimental,
            &["FetchError", "createFetch"],
        ),
        NativeModule::new(
            "@uniflowed/loader",
            NativeModuleKind::Data,
            Stability::Experimental,
            &["createLoader", "useLoader", "loaderCell", "preload"],
        ),
        NativeModule::new(
            "@uniflowed/effect",
            NativeModuleKind::Effect,
            Stability::Experimental,
            &[
                "succeed",
                "fail",
                "die",
                "never",
                "sync",
                "suspend",
                "promise",
                "tryPromise",
                "trySync",
                "call",
                "effect",
                "map",
                "mapError",
                "flatMap",
                "andThen",
                "zip",
                "tap",
                "tapError",
                "as",
                "filterOrFail",
                "exit",
                "all",
                "forEach",
                "race",
                "catchAll",
                "catchTag",
                "orElse",
                "either",
                "orDie",
                "retry",
                "repeat",
                "timeout",
                "acquireRelease",
                "scoped",
                "ensuring",
                "tag",
                "provide",
                "provideService",
                "layerSucceed",
                "layerEffect",
                "layerScoped",
                "layerMerge",
                "layerProvide",
                "layerProvideMerge",
                "managedRuntime",
                "fork",
                "forkDaemon",
                "forkScoped",
                "join",
                "interrupt",
                "ref",
                "refGet",
                "refSet",
                "refModify",
                "refUpdate",
                "refUpdateAndGet",
                "refUpdateEffect",
                "refGetAndUpdate",
                "refGetAndSet",
                "deferred",
                "deferredAwait",
                "deferredSucceed",
                "deferredFail",
                "deferredIsDone",
                "semaphore",
                "withPermit",
                "withPermits",
                "queue",
                "queueOffer",
                "queueTake",
                "queueTakeAll",
                "queueTakeUpTo",
                "queueSize",
                "queueShutdown",
                "queueIsShutdown",
                "pubSub",
                "pubSubSubscribe",
                "pubSubPublish",
                "pubSubShutdown",
                "sleep",
                "delay",
                "runSync",
                "runSyncExit",
                "runPromise",
                "runPromiseExit",
                "runFork",
                "runtimeRunSync",
                "runtimeRunSyncExit",
                "runtimeRunPromise",
                "runtimeRunPromiseExit",
                "runtimeRunFork",
                "runtimeDispose",
            ],
        ),
        NativeModule::new(
            "@uniflowed/orm",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "column",
                "contract",
                "db",
                "defineTable",
                "limit",
                "migration",
                "nullable",
                "primaryKey",
                "query",
                "relation",
                "whereEq",
            ],
        ),
        NativeModule::new(
            "@uniflowed/relay",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "graphql",
                "useFragment",
                "useLazyLoadQuery",
                "usePreloadedQuery",
                "useMutation",
                "commitMutation",
                "RelayEnvironmentProvider",
                "loadQuery",
            ],
        ),
        NativeModule::new(
            "@uniflowed/graphql",
            NativeModuleKind::Data,
            Stability::Experimental,
            &["createEnvironment", "GraphQlResponseError", "Observable"],
        ),
        NativeModule::new(
            "@uniflowed/web",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &[
                "Announcer",
                "Font",
                "Icon",
                "IconSprite",
                "Image",
                "Layout",
                "OgImage",
                "Page",
                "Picture",
                "SkipLink",
                "Time",
                "VITALS_ENDPOINT",
                "asInstant",
                "collectVitals",
                "relative",
                "useCookie",
                "useHead",
                "useVitals",
                "vitalsBeacon",
            ],
        ),
        NativeModule::new(
            "@uniflowed/markdown",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "Markdown",
                "renderMarkdown",
                "compileMarkdown",
                "Mdx",
                "renderMdx",
                "compileMdx",
            ],
        ),
        NativeModule::new(
            "@uniflowed/temporal",
            NativeModuleKind::Data,
            Stability::Experimental,
            &["Temporal", "isLite", "withCalendar"],
        ),
        NativeModule::new(
            "@uniflowed/pwa",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["definePwa", "Manifest", "ServiceWorker"],
        ),
        NativeModule::new(
            "@uniflowed/prepare",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &["prepare", "lintStaged", "codegen"],
        ),
        NativeModule::new(
            "@uniflowed/pm",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &["inferFromConfig", "install", "upgrade"],
        ),
        NativeModule::new(
            "@uniflowed/rm",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &[
                "acquireRuntime",
                "applyRuntime",
                "doctor",
                "inferRuntime",
                "useRuntime",
            ],
        ),
        NativeModule::new(
            "@uniflowed/cell",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "batch",
                "derived",
                "effect",
                "peek",
                "read",
                "refresh",
                "resource",
                "snapshot",
                "state",
                "status",
                "subscribe",
                "untracked",
                "update",
                "write",
            ],
        ),
        NativeModule::new(
            "@uniflowed/state",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "Provider",
                "RESET",
                "action",
                "asyncAtom",
                "atom",
                "atomFamily",
                "atomWithAsyncStorage",
                "atomWithDefault",
                "atomWithReducer",
                "atomWithReset",
                "atomWithStorage",
                "batch",
                "createJSONStorage",
                "createStore",
                "freezeAtom",
                "getDefaultStore",
                "read",
                "refresh",
                "selectAtom",
                "selector",
                "subscribe",
                "unwrap",
                "useAtom",
                "useAtomCallback",
                "useAtomValue",
                "useCell",
                "useResetAtom",
                "useSetAtom",
                "useStore",
                "writableSelector",
                "write",
            ],
        ),
        NativeModule::new(
            "@uniflowed/validator",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "ValidationError",
                "array",
                "bigint",
                "boolean",
                "brand",
                "check",
                "checkAsync",
                "custom",
                "date",
                "describe",
                "email",
                "endsWith",
                "enum_",
                "fallback",
                "flatten",
                "includes",
                "instance",
                "integer",
                "intersect",
                "is",
                "isAsync",
                "isoDate",
                "lazy",
                "lazyAsync",
                "length",
                "literal",
                "looseObject",
                "map",
                "max",
                "maxItems",
                "maxLength",
                "min",
                "minItems",
                "minLength",
                "multipleOf",
                "never",
                "nonEmpty",
                "null_",
                "nullable",
                "nullish",
                "number",
                "object",
                "optional",
                "parse",
                "parseAsync",
                "parser",
                "partial",
                "pipe",
                "record",
                "refine",
                "regex",
                "safeParse",
                "safeParseAsync",
                "set",
                "startsWith",
                "strictObject",
                "string",
                "toJsonSchema",
                "toLowerCase",
                "toUpperCase",
                "transform",
                "transformAsync",
                "trim",
                "tuple",
                "undefined_",
                "union",
                "unknown",
                "url",
                "useValidation",
                "uuid",
                "v",
                "variant",
                "withDefault",
            ],
        ),
        NativeModule::new(
            "@uniflowed/i18n",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "MessageContractError",
                "MessageFormatError",
                "MessageSyntaxError",
                "boolean",
                "date",
                "defineCatalogue",
                "defineLocales",
                "formatMessage",
                "message",
                "messageUsage",
                "negotiate",
                "number",
                "parseAcceptLanguage",
                "parseMessage",
                "string",
                "translate",
            ],
        ),
        NativeModule::new(
            "@uniflowed/immer",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "applyPatches",
                "current",
                "freeze",
                "isDraft",
                "isDraftable",
                "original",
                "produce",
                "produceWithPatches",
                "setAutoFreeze",
            ],
        ),
        NativeModule::new(
            "@uniflowed/mock",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &[
                "HttpResponse",
                "UnhandledRequestError",
                "delay",
                "http",
                "mock",
                "passthrough",
            ],
        ),
        NativeModule::new(
            "@uniflowed/browser",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &["browser", "viewport", "visit", "screenshot"],
        ),
        NativeModule::new(
            "@uniflowed/story",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &[
                "STORY_FILE",
                "STORY_ROLE",
                "STORY_SET",
                "StoryPlayError",
                "classifyStoryFile",
                "collectStories",
                "defineStories",
                "findStory",
                "findStoryFiles",
                "indexStories",
                "isStoryEntry",
                "isStorySet",
                "loadStoryFile",
                "mountStory",
                "renderStoryToHtml",
                "storyId",
            ],
        ),
        NativeModule::new(
            "@uniflowed/vrt",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &["plan", "snapshot", "diff", "baseline"],
        ),
        NativeModule::new(
            "@uniflowed/motion",
            NativeModuleKind::Ui,
            Stability::Experimental,
            &["motion", "animate", "timeline", "spring", "reducedMotion"],
        ),
        NativeModule::new(
            "@uniflowed/tui",
            NativeModuleKind::Ui,
            Stability::Experimental,
            &[
                "Attributes",
                "Box",
                "FALLBACK_COLUMNS",
                "FALLBACK_ROWS",
                "INHERIT",
                "Input",
                "MouseButton",
                "ScrollBox",
                "Text",
                "borderGlyphs",
                "createInputDecoder",
                "decodeInput",
                "decodeKeys",
                "detectCapabilities",
                "detectSize",
                "frameRow",
                "frameText",
                "parseColor",
                "plainCapabilities",
                "render",
                "selectionContains",
                "testRender",
                "useClipboard",
                "useKeyboard",
                "useRenderer",
                "useTerminalSize",
            ],
        ),
        NativeModule::new(
            "@uniflowed/cli",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &["defineCli", "command", "arg", "option"],
        ),
        NativeModule::new(
            "@uniflowed/std",
            NativeModuleKind::Std,
            Stability::Experimental,
            &[
                "bufferFromUtf8",
                "clamp",
                "colorize",
                "defer",
                "defineFunction",
                "detectYaml",
                "digest",
                "dnsQuery",
                "fastHash",
                "glob",
                "importMeta",
                "joinPath",
                "lazy",
                "lerp",
                "modules",
                "motion",
                "normalizePath",
                "osInfo",
                "parseCron",
                "parseDotEnv",
                "parseJson",
                "parseQuery",
                "parseToml",
                "parseUrl",
                "parseUuid",
                "s3Object",
                "sigv4Scope",
                "stream",
                "stringifyJson",
                "stringifyQuery",
                "terminalCapabilities",
                "timingSafeEqual",
                "toHex",
                "virtualPath",
                "wasmModule",
                "wintertc",
            ],
        ),
        NativeModule::new(
            "@uniflowed/stylex",
            NativeModuleKind::Style,
            Stability::Experimental,
            &["create", "createTheme", "defineVars", "props", "stylex"],
        ),
        NativeModule::new(
            "@uniflowed/ui",
            NativeModuleKind::Ui,
            Stability::Experimental,
            &[
                "Accordion",
                "AccordionContent",
                "AccordionHeader",
                "AccordionItem",
                "AccordionRoot",
                "AccordionTrigger",
                "Alert",
                "AlertDescription",
                "AlertDialog",
                "AlertDialogAction",
                "AlertDialogBody",
                "AlertDialogCancel",
                "AlertDialogDescription",
                "AlertDialogFooter",
                "AlertDialogHeader",
                "AlertDialogOverlay",
                "AlertDialogRoot",
                "AlertDialogTitle",
                "AlertDialogTrigger",
                "AlertRoot",
                "AlertTitle",
                "Avatar",
                "AvatarFallback",
                "AvatarImage",
                "AvatarRoot",
                "Breadcrumb",
                "BreadcrumbItem",
                "BreadcrumbLink",
                "BreadcrumbList",
                "BreadcrumbPage",
                "BreadcrumbRoot",
                "BreadcrumbSeparator",
                "Calendar",
                "CalendarDay",
                "CalendarMonth",
                "CalendarNext",
                "CalendarPrevious",
                "CalendarRoot",
                "Carousel",
                "CarouselContent",
                "CarouselItem",
                "CarouselNext",
                "CarouselPause",
                "CarouselPrevious",
                "CarouselRoot",
                "Checkbox",
                "Collapsible",
                "CollapsibleContent",
                "CollapsibleRoot",
                "CollapsibleTrigger",
                "Combobox",
                "ComboboxEmpty",
                "ComboboxGroup",
                "ComboboxGroupLabel",
                "ComboboxInput",
                "ComboboxLabel",
                "ComboboxList",
                "ComboboxOption",
                "ComboboxRoot",
                "ComboboxStatus",
                "ContextMenu",
                "ContextMenuRoot",
                "ContextMenuTrigger",
                "DatePicker",
                "DatePickerCalendar",
                "DatePickerInput",
                "DatePickerRoot",
                "DatePickerTrigger",
                "Dialog",
                "DialogBody",
                "DialogClose",
                "DialogDescription",
                "DialogFooter",
                "DialogHeader",
                "DialogOverlay",
                "DialogRoot",
                "DialogTitle",
                "DialogTrigger",
                "Drawer",
                "DrawerBody",
                "DrawerClose",
                "DrawerDescription",
                "DrawerFooter",
                "DrawerHandle",
                "DrawerHeader",
                "DrawerOverlay",
                "DrawerRoot",
                "DrawerTitle",
                "DrawerTrigger",
                "Field",
                "FieldControl",
                "FieldDescription",
                "FieldError",
                "FieldLabel",
                "FieldRoot",
                "FieldStatus",
                "HoverCard",
                "HoverCardBody",
                "HoverCardRoot",
                "HoverCardTrigger",
                "InputOtp",
                "InputOtpGroup",
                "InputOtpRoot",
                "InputOtpSeparator",
                "InputOtpSlot",
                "Menu",
                "MenuBody",
                "MenuCheckboxItem",
                "MenuGroup",
                "MenuItem",
                "MenuLabel",
                "MenuRadioGroup",
                "MenuRadioItem",
                "MenuRoot",
                "MenuSeparator",
                "MenuSub",
                "MenuSubTrigger",
                "MenuTrigger",
                "Menubar",
                "MenubarMenu",
                "MenubarRoot",
                "MenubarTrigger",
                "NavigationMenu",
                "NavigationMenuBody",
                "NavigationMenuItem",
                "NavigationMenuLink",
                "NavigationMenuList",
                "NavigationMenuRoot",
                "NavigationMenuTrigger",
                "Pagination",
                "PaginationContent",
                "PaginationItem",
                "PaginationNext",
                "PaginationPrevious",
                "PaginationRoot",
                "Popover",
                "PopoverBody",
                "PopoverRoot",
                "PopoverTrigger",
                "Progress",
                "RadioGroup",
                "RadioGroupIndicator",
                "RadioGroupItem",
                "RadioGroupRoot",
                "Resizable",
                "ResizableHandle",
                "ResizablePanel",
                "ResizablePanelGroup",
                "ScrollArea",
                "ScrollAreaRoot",
                "ScrollAreaScrollbar",
                "ScrollAreaViewport",
                "Select",
                "SelectGroup",
                "SelectGroupLabel",
                "SelectLabel",
                "SelectList",
                "SelectOption",
                "SelectRoot",
                "SelectSeparator",
                "SelectTrigger",
                "SelectValue",
                "Separator",
                "Sheet",
                "SheetBody",
                "SheetClose",
                "SheetDescription",
                "SheetFooter",
                "SheetHeader",
                "SheetOverlay",
                "SheetRoot",
                "SheetTitle",
                "SheetTrigger",
                "Sidebar",
                "SidebarBody",
                "SidebarFooter",
                "SidebarHeader",
                "SidebarItem",
                "SidebarRoot",
                "SidebarTrigger",
                "Skeleton",
                "SkeletonBox",
                "SkeletonRoot",
                "Slider",
                "SliderRange",
                "SliderRoot",
                "SliderThumb",
                "SliderTrack",
                "Switch",
                "Table",
                "TableBody",
                "TableCaption",
                "TableCell",
                "TableHead",
                "TableHeader",
                "TableRoot",
                "TableRow",
                "TableRowHeader",
                "TableRowSelect",
                "TableSelectAll",
                "Tabs",
                "TabsList",
                "TabsPanel",
                "TabsRoot",
                "TabsTab",
                "Toast",
                "ToastAction",
                "ToastClose",
                "ToastDescription",
                "ToastRegion",
                "ToastRoot",
                "ToastTitle",
                "Toggle",
                "ToggleGroup",
                "ToggleGroupItem",
                "ToggleGroupRoot",
                "Tooltip",
                "TooltipBody",
                "TooltipProvider",
                "TooltipRoot",
                "TooltipTrigger",
                "dismissAllToasts",
                "dismissToast",
                "getInteractionModality",
                "mergeProps",
                "toast",
                "updateToast",
                "useFocusRing",
                "useFocusVisible",
                "useHover",
                "useInteractionModality",
                "useKeyboard",
                "useLongPress",
                "useMove",
                "usePress",
            ],
        ),
        NativeModule::new(
            "@uniflowed/react-compiler",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["compiler", "syntaxMode"],
        ),
        // Imported by generated code rather than by hand: `uf build` injects
        // the import when it lowers a module's JSX.
        NativeModule::new(
            "@uniflowed/jsx-runtime",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["jsx", "jsxs", "Fragment"],
        ),
        NativeModule::new(
            "@uniflowed/runtime",
            NativeModuleKind::Runtime,
            Stability::Planned,
            &["run", "resolve", "spawn"],
        ),
        NativeModule::new(
            "@uniflowed/lib",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &["modules", "version"],
        ),
        NativeModule::new(
            "@uniflowed/lint",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["defineRule", "typeAwareRule", "reactRule"],
        ),
        NativeModule::new(
            "@uniflowed/form",
            NativeModuleKind::Ui,
            Stability::Experimental,
            &[
                "Controller",
                "FormProvider",
                "collectErrors",
                "constraintsOf",
                "errorsFromIssues",
                "errorsOf",
                "isRequired",
                "runResolver",
                "runRules",
                "useController",
                "useFieldArray",
                "useFieldSource",
                "useForm",
                "useFormContext",
                "useFormState",
                "useWatch",
                "validatorResolver",
                "whenSettled",
            ],
        ),
    ]
}

pub fn std_module_descriptors() -> Vec<StdModule> {
    std_modules().into_iter().collect()
}

pub fn tui_contract() -> TuiFrameworkContract {
    TuiFrameworkContract::default()
}

/// Every hook `@uniflowed/hooks` exports, and what a compiler may assume.
///
/// `idempotent_render` is the package's contract rather than an observation:
/// every hook here reads through `useSyncExternalStore` or a ref and writes
/// nothing during render, which is what makes them safe under the React
/// Compiler and under Strict Mode's double invocation.
///
/// `server_component_safe` is true for exactly one. The others each report a
/// stated server value — `useMediaQuery` answers `false`, `useNow` answers the
/// time the render happened — which is a correct answer rather than a safe
/// one: it is the client that will disagree on hydration, and a Server
/// Component has no client. `useIsomorphicLayoutEffect` is the exception
/// because it is inert on a server by construction.
///
/// The list had drifted twice, in both directions, which is why
/// `the_hook_table_names_exactly_the_hooks_the_package_exports` now holds it
/// rather than care does. First it named `useEvent`,
/// `useLocalStorage` and `useServerValue`, none of which the package has ever
/// exported. Then it fell six behind — `useEventSource`, and the five of
/// `packages/hooks/render.js` — because a hook added to the package and to the
/// export list above is complete as far as an editor is concerned, and this
/// table is a second place with the same name in it.
///
/// The six are `(true, false)` like almost everything here, and for the two
/// separate reasons the paragraphs above give. `useEventSource` holds a
/// connection open from an effect and reports it through state, so it writes
/// nothing during a render and cannot have a connection on a server.
/// `render.js`'s five read a `RenderProvider`'s decisions through
/// `useContext`, which is what makes both renders of a prerendered page agree
/// — and `useContext` is the API a Server Component may not call, so the hook
/// that is *about* rendering twice is not one a Server Component can use.
pub fn hook_descriptors() -> Vec<HookDescriptor> {
    vec![
        HookDescriptor::new("useAnimationFrame", true, false),
        HookDescriptor::new("useAsync", true, false),
        HookDescriptor::new("useBroadcast", true, false),
        HookDescriptor::new("useClickOutside", true, false),
        HookDescriptor::new("useClipboard", true, false),
        HookDescriptor::new("useCounter", true, false),
        HookDescriptor::new("useCycle", true, false),
        HookDescriptor::new("useDebouncedCallback", true, false),
        HookDescriptor::new("useDebouncedValue", true, false),
        HookDescriptor::new("useDocumentVisible", true, false),
        HookDescriptor::new("useElementRef", true, false),
        HookDescriptor::new("useElementSize", true, false),
        HookDescriptor::new("useElementState", true, false),
        HookDescriptor::new("useEventListener", true, false),
        HookDescriptor::new("useEventSource", true, false),
        HookDescriptor::new("useFocusWithin", true, false),
        HookDescriptor::new("useGeolocation", true, false),
        HookDescriptor::new("useHash", true, false),
        HookDescriptor::new("useHover", true, false),
        HookDescriptor::new("useIdle", true, false),
        HookDescriptor::new("useIntersecting", true, false),
        HookDescriptor::new("useInterval", true, false),
        HookDescriptor::new("useIsomorphicLayoutEffect", true, true),
        HookDescriptor::new("useKeyCombo", true, false),
        HookDescriptor::new("useKeyHeld", true, false),
        HookDescriptor::new("useList", true, false),
        HookDescriptor::new("useLongPress", true, false),
        HookDescriptor::new("useMediaQuery", true, false),
        HookDescriptor::new("useMount", true, false),
        HookDescriptor::new("useMounted", true, false),
        HookDescriptor::new("useMutationObserver", true, false),
        HookDescriptor::new("useNetwork", true, false),
        HookDescriptor::new("useNow", true, false),
        HookDescriptor::new("useOnline", true, false),
        HookDescriptor::new("usePermission", true, false),
        HookDescriptor::new("usePreferredColorScheme", true, false),
        HookDescriptor::new("usePrefersReducedMotion", true, false),
        HookDescriptor::new("usePrevious", true, false),
        HookDescriptor::new("useRandom", true, false),
        HookDescriptor::new("useRenderEnvelope", true, false),
        HookDescriptor::new("useRenderTimeZone", true, false),
        HookDescriptor::new("useRenderedAt", true, false),
        HookDescriptor::new("useRerender", true, false),
        HookDescriptor::new("useScroll", true, false),
        HookDescriptor::new("useScrollLock", true, false),
        HookDescriptor::new("useSet", true, false),
        HookDescriptor::new("useShuffled", true, false),
        HookDescriptor::new("useStableCallback", true, false),
        HookDescriptor::new("useStorage", true, false),
        HookDescriptor::new("useSupported", true, false),
        HookDescriptor::new("useThrottledCallback", true, false),
        HookDescriptor::new("useTimeAgo", true, false),
        HookDescriptor::new("useTimeout", true, false),
        HookDescriptor::new("useToggle", true, false),
        HookDescriptor::new("useUndoable", true, false),
        HookDescriptor::new("useUnmount", true, false),
        HookDescriptor::new("useWindowScroll", true, false),
        HookDescriptor::new("useWindowSize", true, false),
    ]
}

pub fn module_by_specifier(specifier: &str) -> Option<NativeModule> {
    builtin_modules()
        .into_iter()
        .find(|module| module.specifier == specifier)
}

/// The package whose modules [`CLIENT_MODULE_SUBPATHS`] lists.
pub const CLIENT_MODULE_PACKAGE: &str = "@uniflowed/ui";

/// The modules of [`CLIENT_MODULE_PACKAGE`] that are client modules, by the name
/// uf gives each after the package: `switch` is `@uniflowed/ui/switch`.
///
/// Named for the subpaths the package exported until its barrel became its one
/// entry point. A project imports `{ Switch }` from `@uniflowed/ui`, and
/// [`client_modules_exporting`] is how that name reaches `switch`.
///
/// uf's RSC scan walks a project and skips `node_modules`, which is the right
/// default — a dependency tree is enormous and almost none of it is in the
/// application graph. The cost is that in a project that *installs*
/// `@uniflowed/ui` rather than being this repository, uf's own components are
/// invisible to the analysis that exists to find exactly them: every one of
/// these carries `"use client"` and is a client bundle root, and the scan never
/// opens the file to see it. See ubugeeei-prod/uf#718.
///
/// A list rather than a walk, and here rather than in `uf_rsc`, for the reason
/// [`hook_descriptors`] is here: a fact about a package uf ships belongs beside
/// the registry of packages uf ships, and a walk of an installed tree is the
/// expense this exists to avoid. `the_client_module_list_names_exactly_the_ui_
/// modules_that_are_client_modules` in `uf_rsc` holds the list to the files —
/// with the parser that decides the question in production, not a second
/// answer to it — which is the whole value of writing the names down.
///
/// The modules the barrel re-exports from, and no others, so this says where a
/// name a project imports can come from. `internal/form-value` and
/// `internal/menu-tree` are client modules too and are deliberately absent: the
/// barrel exports nothing of theirs, and the modules that import them are
/// already here.
///
/// Not the whole package, which is the reason this is a list and not a rule.
/// `alert`, `breadcrumb`, `pagination`, `progress` and `separator` are markup
/// with no state and each says so in a section headed "No `use client`" — they
/// are Server Components, and shipping them to the browser because they came
/// out of the same package would be exactly the mistake RSC exists to stop.
///
/// uf's own package only. A third party still needs a way to *declare* a
/// client root — a manifest field, or the `react-server` export condition —
/// before the same package-specifier boundary can be populated from its data.
pub const CLIENT_MODULE_SUBPATHS: &[&str] = &[
    "accordion",
    "alert-dialog",
    "avatar",
    "calendar",
    "carousel",
    "checkbox",
    "collapsible",
    "combobox",
    "context-menu",
    "date-picker",
    "dialog",
    "drawer",
    "field",
    "hover-card",
    "input-otp",
    "interactions",
    "menu",
    "menubar",
    "navigation-menu",
    "popover",
    "radio-group",
    "resizable",
    "scroll-area",
    "select",
    "sheet",
    "sidebar",
    "skeleton",
    "slider",
    "switch",
    "table",
    "tabs",
    "toast",
    "toggle",
    "toggle-group",
    "tooltip",
];

/// Whether `@uniflowed/ui/<module>`, the name uf gives one of the package's
/// modules, is a module uf knows carries `"use client"`.
///
/// Not a specifier a project writes: the package exports its barrel alone, and
/// a name imported from the barrel reaches its module through
/// [`client_modules_exporting`]. The barrel, `@uniflowed/ui`, is a server
/// module: it re-exports the client ones, which makes it a module that
/// *imports* client modules rather than one that is one, and that distinction
/// is the difference between a bundle root and an edge leading to one.
#[must_use]
pub fn is_client_module(specifier: &str) -> bool {
    specifier
        .strip_prefix(CLIENT_MODULE_PACKAGE)
        .and_then(|rest| rest.strip_prefix('/'))
        .is_some_and(|subpath| CLIENT_MODULE_SUBPATHS.contains(&subpath))
}

/// Names the barrel exports that [`client_modules_exporting`]'s rule does not
/// fit, with the client modules each comes from.
///
/// `ContextMenu` and `Menubar` are namespaces whose items include `Menu`'s own
/// parts, so either reaches `menu` as well as its own module. `toast` and its
/// three companions are functions named for what they do, and the interactions
/// layer is hooks.
const BARREL_EXPORT_MODULES: &[(&str, &[&str])] = &[
    ("ContextMenu", &["context-menu", "menu"]),
    ("Menubar", &["menu", "menubar"]),
    ("dismissAllToasts", &["toast"]),
    ("dismissToast", &["toast"]),
    ("getInteractionModality", &["interactions"]),
    ("mergeProps", &["interactions"]),
    ("toast", &["toast"]),
    ("updateToast", &["toast"]),
    ("useFocusRing", &["interactions"]),
    ("useFocusVisible", &["interactions"]),
    ("useHover", &["interactions"]),
    ("useInteractionModality", &["interactions"]),
    ("useKeyboard", &["interactions"]),
    ("useLongPress", &["interactions"]),
    ("useMove", &["interactions"]),
    ("usePress", &["interactions"]),
];

/// The client modules a name imported from the [`CLIENT_MODULE_PACKAGE`] barrel
/// comes from, or none for a name no client module exports.
///
/// The barrel re-exports every module, so a page that imports `{ Switch }` from
/// `@uniflowed/ui` reaches the `switch` module and nothing else. That is what
/// lets a boundary name the module rather than the package, and a bundle carry
/// one component's client code rather than every component's.
///
/// A rule rather than a table of every name, because the barrel's names follow
/// its modules': a family's namespace is its module in PascalCase (`AlertDialog`
/// is `alert-dialog`), a part begins with it (`AlertDialogBody`), and where two
/// modules fit, the longer one is where the name comes from (`MenubarTrigger` is
/// `menubar`, not `menu`). A name from a Server Component module, such as
/// `AlertRoot`, fits no client module and reaches none. [`BARREL_EXPORT_MODULES`]
/// holds the names the rule does not fit, and
/// `the_barrel_names_the_client_modules_each_export_comes_from` in `uf_rsc` holds
/// the rule to `packages/ui/index.js`.
#[must_use]
pub fn client_modules_exporting(name: &str) -> Vec<&'static str> {
    if let Some((_, modules)) = BARREL_EXPORT_MODULES
        .iter()
        .find(|(export, _)| *export == name)
    {
        return modules.to_vec();
    }
    CLIENT_MODULE_SUBPATHS
        .iter()
        .copied()
        .filter(|module| name.starts_with(pascal_case(module).as_str()))
        .max_by_key(|module| module.len())
        .into_iter()
        .collect()
}

/// `alert-dialog` as `AlertDialog`.
fn pascal_case(kebab: &str) -> String {
    let mut out = String::with_capacity(kebab.len());
    for word in kebab.split('-') {
        let mut letters = word.chars();
        if let Some(first) = letters.next() {
            out.push(first.to_ascii_uppercase());
            out.push_str(letters.as_str());
        }
    }
    out
}
