//! The table of every `@uniflowed/*` module uf ships, and the hooks beside it.
//!
//! Deliberately long and deliberately flat: this is data, not logic. It is the
//! one list that says which specifiers exist, how stable each is, and what Flow
//! names it exports, so a module that is not here does not exist as far as the
//! toolchain is concerned.

use uf_std::{StdModule, std_modules};
use uf_tui::TuiFrameworkContract;

use crate::descriptor::{HookDescriptor, NativeModule, NativeModuleKind, Stability};

pub fn builtin_modules() -> Vec<NativeModule> {
    vec![
        NativeModule::new(
            "@uniflowed/core",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &[
                "describe",
                "it",
                "test",
                "expect",
                "beforeEach",
                "afterEach",
            ],
        ),
        NativeModule::new(
            "@uniflowed/react",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["Node", "React", "SetState", "Suspense", "use", "cache"],
        ),
        NativeModule::new(
            "@uniflowed/react-native",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["View", "Text", "Platform"],
        ),
        NativeModule::new(
            "@uniflowed/brand",
            NativeModuleKind::Style,
            Stability::Experimental,
            &[
                "ufBrand",
                "ufBrandAssets",
                "ufPalette",
                "ufTextScale",
                "ufSpacingScale",
                "ufRadiusScale",
                "ufCommands",
            ],
        ),
        NativeModule::new(
            "@uniflowed/testing",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &["describe", "it", "test", "expect", "fn", "render", "screen"],
        ),
        NativeModule::new(
            "@uniflowed/test",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &[
                "describe",
                "it",
                "test",
                "expect",
                "fn",
                "spyOn",
                "uft",
                "beforeAll",
                "afterAll",
                "beforeEach",
                "afterEach",
            ],
        ),
        NativeModule::new(
            "@uniflowed/react-testing",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &[
                "render",
                "screen",
                "within",
                "fireEvent",
                "userEvent",
                "waitFor",
                "cleanup",
                "act",
                "dispatch",
                "normalize",
                "accessibleName",
                "roleOf",
            ],
        ),
        NativeModule::new(
            "@uniflowed/hooks",
            NativeModuleKind::Hooks,
            Stability::Experimental,
            &[
                "browserWindow",
                "useAnimationFrame",
                "useAsync",
                "useBroadcast",
                "useClickOutside",
                "useClipboard",
                "useCounter",
                "useCycle",
                "useDebouncedCallback",
                "useDebouncedValue",
                "useDocumentVisible",
                "useElementRef",
                "useElementSize",
                "useElementState",
                "useEventListener",
                "useFocusWithin",
                "useGeolocation",
                "useHover",
                "useIdle",
                "useIntersecting",
                "useInterval",
                "useIsomorphicLayoutEffect",
                "useKeyCombo",
                "useKeyHeld",
                "useList",
                "useLongPress",
                "useMediaQuery",
                "useMount",
                "useMounted",
                "useMutationObserver",
                "useNetwork",
                "useNow",
                "useOnline",
                "usePermission",
                "usePreferredColorScheme",
                "usePrefersReducedMotion",
                "usePrevious",
                "useRerender",
                "useScroll",
                "useScrollLock",
                "useSet",
                "useStableCallback",
                "useStorage",
                "useSupported",
                "useThrottledCallback",
                "useTimeAgo",
                "useTimeout",
                "useToggle",
                "useUndoable",
                "useUnmount",
                "useWindowScroll",
                "useWindowSize",
            ],
        ),
        NativeModule::new(
            "@uniflowed/router",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &[
                "FileRoute",
                "loader",
                "action",
                "redirect",
                "useRoute",
                "useRouter",
                "defineNavigationGuard",
            ],
        ),
        NativeModule::new(
            "@uniflowed/server",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["serverAction", "headers", "cookies", "cache"],
        ),
        NativeModule::new(
            "@uniflowed/query",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "CancelledError",
                "DEFAULT_GC_TIME",
                "InfiniteQueryObserver",
                "Mutation",
                "Presence",
                "Query",
                "QueryCache",
                "QueryClient",
                "QueryClientProvider",
                "QueryObserver",
                "backoffDelay",
                "hashKey",
                "infinitePages",
                "matchesKey",
                "structuralShare",
                "useInfiniteQuery",
                "useMutation",
                "useQuery",
                "useQueryClient",
            ],
        ),
        NativeModule::new(
            "@uniflowed/fetch",
            NativeModuleKind::Data,
            Stability::Experimental,
            &["FetchError", "createFetch"],
        ),
        NativeModule::new(
            "@uniflowed/loader",
            NativeModuleKind::Data,
            Stability::Experimental,
            &["createLoader", "useLoader", "loaderCell", "preload"],
        ),
        NativeModule::new(
            "@uniflowed/effect",
            NativeModuleKind::Effect,
            Stability::Experimental,
            &[
                "succeed",
                "fail",
                "die",
                "never",
                "sync",
                "suspend",
                "promise",
                "tryPromise",
                "call",
                "effect",
                "map",
                "mapError",
                "flatMap",
                "andThen",
                "zip",
                "tap",
                "tapError",
                "as",
                "filterOrFail",
                "exit",
                "all",
                "forEach",
                "race",
                "catchAll",
                "catchTag",
                "orElse",
                "either",
                "orDie",
                "retry",
                "timeout",
                "acquireRelease",
                "scoped",
                "ensuring",
                "tag",
                "provide",
                "provideService",
                "layerSucceed",
                "layerEffect",
                "layerMerge",
                "fork",
                "join",
                "interrupt",
                "sleep",
                "delay",
                "runSync",
                "runSyncExit",
                "runPromise",
                "runPromiseExit",
                "runFork",
            ],
        ),
        NativeModule::new(
            "@uniflowed/orm",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "defineTable",
                "column",
                "relation",
                "query",
                "migration",
                "db",
            ],
        ),
        NativeModule::new(
            "@uniflowed/relay",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "graphql",
                "useFragment",
                "useLazyLoadQuery",
                "usePreloadedQuery",
                "useMutation",
                "commitMutation",
                "RelayEnvironmentProvider",
                "loadQuery",
            ],
        ),
        NativeModule::new(
            "@uniflowed/graphql",
            NativeModuleKind::Data,
            Stability::Experimental,
            &["createEnvironment", "GraphQlResponseError", "Observable"],
        ),
        NativeModule::new(
            "@uniflowed/web",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &[
                "Font",
                "Image",
                "OgImage",
                "Link",
                "Page",
                "Layout",
                "Time",
                "Announcer",
                "Picture",
                "useCookie",
                "useHead",
            ],
        ),
        NativeModule::new(
            "@uniflowed/markdown",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "Markdown",
                "renderMarkdown",
                "compileMarkdown",
                "Mdx",
                "renderMdx",
                "compileMdx",
            ],
        ),
        NativeModule::new(
            "@uniflowed/temporal",
            NativeModuleKind::Data,
            Stability::Experimental,
            &["Temporal", "Instant", "PlainDate", "ZonedDateTime"],
        ),
        NativeModule::new(
            "@uniflowed/pwa",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["definePwa", "Manifest", "ServiceWorker"],
        ),
        NativeModule::new(
            "@uniflowed/prepare",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &["prepare", "lintStaged", "codegen"],
        ),
        NativeModule::new(
            "@uniflowed/pm",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &["inferFromConfig", "install", "upgrade", "lock", "store"],
        ),
        NativeModule::new(
            "@uniflowed/rm",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &["inferRuntime", "acquireRuntime", "applyRuntime", "doctor"],
        ),
        NativeModule::new(
            "@uniflowed/cell",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "batch",
                "cell",
                "computed",
                "effect",
                "peek",
                "read",
                "refresh",
                "resource",
                "snapshot",
                "status",
                "subscribe",
                "untracked",
                "update",
                "write",
            ],
        ),
        NativeModule::new(
            "@uniflowed/state",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "Provider",
                "RESET",
                "action",
                "asyncAtom",
                "atom",
                "atomFamily",
                "atomWithDefault",
                "atomWithStorage",
                "batch",
                "createStore",
                "getDefaultStore",
                "read",
                "refresh",
                "selector",
                "subscribe",
                "unwrap",
                "useAtom",
                "useAtomValue",
                "useCell",
                "useSetAtom",
                "useStore",
                "writableSelector",
                "write",
            ],
        ),
        NativeModule::new(
            "@uniflowed/validator",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "ValidationError",
                "array",
                "bigint",
                "boolean",
                "brand",
                "check",
                "checkAsync",
                "custom",
                "date",
                "describe",
                "email",
                "endsWith",
                "enum_",
                "fallback",
                "flatten",
                "includes",
                "instance",
                "integer",
                "intersect",
                "is",
                "isAsync",
                "isoDate",
                "lazy",
                "lazyAsync",
                "length",
                "literal",
                "looseObject",
                "map",
                "max",
                "maxItems",
                "maxLength",
                "min",
                "minItems",
                "minLength",
                "multipleOf",
                "never",
                "nonEmpty",
                "null_",
                "nullable",
                "nullish",
                "number",
                "object",
                "optional",
                "parse",
                "parseAsync",
                "parser",
                "partial",
                "pipe",
                "record",
                "refine",
                "regex",
                "safeParse",
                "safeParseAsync",
                "set",
                "startsWith",
                "strictObject",
                "string",
                "toJsonSchema",
                "toLowerCase",
                "toUpperCase",
                "transform",
                "transformAsync",
                "trim",
                "tuple",
                "undefined_",
                "union",
                "unknown",
                "url",
                "useValidation",
                "uuid",
                "v",
                "variant",
                "withDefault",
            ],
        ),
        NativeModule::new(
            "@uniflowed/immer",
            NativeModuleKind::Data,
            Stability::Experimental,
            &[
                "produce",
                "produceWithPatches",
                "applyPatches",
                "original",
                "current",
                "isDraft",
                "isDraftable",
                "freeze",
                "setAutoFreeze",
                "Draft",
                "Patch",
            ],
        ),
        NativeModule::new(
            "@uniflowed/mock",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &[
                "HttpResponse",
                "UnhandledRequestError",
                "delay",
                "http",
                "mock",
                "passthrough",
            ],
        ),
        NativeModule::new(
            "@uniflowed/browser",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &["browser", "viewport", "visit", "screenshot"],
        ),
        NativeModule::new(
            "@uniflowed/story",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &[
                "STORY_FILE",
                "STORY_ROLE",
                "STORY_SET",
                "StoryPlayError",
                "classifyStoryFile",
                "collectStories",
                "defineStories",
                "findStory",
                "findStoryFiles",
                "indexStories",
                "isStoryEntry",
                "isStorySet",
                "loadStoryFile",
                "mountStory",
                "renderStoryToHtml",
                "storyId",
            ],
        ),
        NativeModule::new(
            "@uniflowed/vrt",
            NativeModuleKind::Testing,
            Stability::Experimental,
            &["plan", "snapshot", "diff", "baseline"],
        ),
        NativeModule::new(
            "@uniflowed/motion",
            NativeModuleKind::Ui,
            Stability::Experimental,
            &["motion", "animate", "timeline", "spring", "reducedMotion"],
        ),
        NativeModule::new(
            "@uniflowed/tui",
            NativeModuleKind::Ui,
            Stability::Experimental,
            &[
                "Box",
                "Text",
                "Input",
                "Select",
                "ScrollBox",
                "FrameBuffer",
                "renderTui",
                "contract",
            ],
        ),
        NativeModule::new(
            "@uniflowed/cli",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &["defineCli", "command", "arg", "option"],
        ),
        NativeModule::new(
            "@uniflowed/std",
            NativeModuleKind::Std,
            Stability::Experimental,
            &[
                "modules",
                "wintertc",
                "vfs",
                "fs",
                "crypto",
                "http",
                "buffer",
                "importMeta",
                "defer",
            ],
        ),
        NativeModule::new(
            "@uniflowed/stylex",
            NativeModuleKind::Style,
            Stability::Experimental,
            &[
                "CompiledClasses",
                "CompiledStyle",
                "StyleArgument",
                "StyleProps",
                "ThemeOverrides",
                "ThemeValue",
                "create",
                "createTheme",
                "defineVars",
                "props",
                "stylex",
            ],
        ),
        NativeModule::new(
            "@uniflowed/ui",
            NativeModuleKind::Ui,
            Stability::Experimental,
            &[
                "Checkbox", "Combobox", "Dialog", "Field", "Menu", "Switch", "Tabs",
            ],
        ),
        NativeModule::new(
            "@uniflowed/react-compiler",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["compiler", "syntaxMode"],
        ),
        // Imported by generated code rather than by hand: `uf build` injects
        // the import when it lowers a module's JSX.
        NativeModule::new(
            "@uniflowed/jsx-runtime",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["jsx", "jsxs", "Fragment"],
        ),
        NativeModule::new(
            "@uniflowed/runtime",
            NativeModuleKind::Runtime,
            Stability::Planned,
            &["run", "resolve", "spawn"],
        ),
        NativeModule::new(
            "@uniflowed/lib",
            NativeModuleKind::Runtime,
            Stability::Experimental,
            &["modules", "hooks", "ui", "version"],
        ),
        NativeModule::new(
            "@uniflowed/lint",
            NativeModuleKind::Framework,
            Stability::Experimental,
            &["defineRule", "typeAwareRule", "reactRule"],
        ),
        NativeModule::new(
            "@uniflowed/form",
            NativeModuleKind::Ui,
            Stability::Experimental,
            &[
                "useForm",
                "useFieldArray",
                "useWatch",
                "useFormState",
                "useController",
                "Controller",
                "FormProvider",
                "useFormContext",
                "validatorResolver",
            ],
        ),
    ]
}

pub fn std_module_descriptors() -> Vec<StdModule> {
    std_modules().into_iter().collect()
}

pub fn tui_contract() -> TuiFrameworkContract {
    TuiFrameworkContract::default()
}

/// Every hook `@uniflowed/hooks` exports, and what a compiler may assume.
///
/// `idempotent_render` is the package's contract rather than an observation:
/// every hook here reads through `useSyncExternalStore` or a ref and writes
/// nothing during render, which is what makes them safe under the React
/// Compiler and under Strict Mode's double invocation.
///
/// `server_component_safe` is true for exactly one. The others each report a
/// stated server value — `useMediaQuery` answers `false`, `useNow` answers the
/// time the render happened — which is a correct answer rather than a safe
/// one: it is the client that will disagree on hydration, and a Server
/// Component has no client. `useIsomorphicLayoutEffect` is the exception
/// because it is inert on a server by construction.
///
/// The list had drifted: it named `useEvent`, `useLocalStorage` and
/// `useServerValue`, none of which the package has ever exported.
pub fn hook_descriptors() -> Vec<HookDescriptor> {
    vec![
        HookDescriptor::new("useAnimationFrame", true, false),
        HookDescriptor::new("useAsync", true, false),
        HookDescriptor::new("useBroadcast", true, false),
        HookDescriptor::new("useClickOutside", true, false),
        HookDescriptor::new("useClipboard", true, false),
        HookDescriptor::new("useCounter", true, false),
        HookDescriptor::new("useCycle", true, false),
        HookDescriptor::new("useDebouncedCallback", true, false),
        HookDescriptor::new("useDebouncedValue", true, false),
        HookDescriptor::new("useDocumentVisible", true, false),
        HookDescriptor::new("useElementRef", true, false),
        HookDescriptor::new("useElementSize", true, false),
        HookDescriptor::new("useElementState", true, false),
        HookDescriptor::new("useEventListener", true, false),
        HookDescriptor::new("useFocusWithin", true, false),
        HookDescriptor::new("useGeolocation", true, false),
        HookDescriptor::new("useHover", true, false),
        HookDescriptor::new("useIdle", true, false),
        HookDescriptor::new("useIntersecting", true, false),
        HookDescriptor::new("useInterval", true, false),
        HookDescriptor::new("useIsomorphicLayoutEffect", true, true),
        HookDescriptor::new("useKeyCombo", true, false),
        HookDescriptor::new("useKeyHeld", true, false),
        HookDescriptor::new("useList", true, false),
        HookDescriptor::new("useLongPress", true, false),
        HookDescriptor::new("useMediaQuery", true, false),
        HookDescriptor::new("useMount", true, false),
        HookDescriptor::new("useMounted", true, false),
        HookDescriptor::new("useMutationObserver", true, false),
        HookDescriptor::new("useNetwork", true, false),
        HookDescriptor::new("useNow", true, false),
        HookDescriptor::new("useOnline", true, false),
        HookDescriptor::new("usePermission", true, false),
        HookDescriptor::new("usePreferredColorScheme", true, false),
        HookDescriptor::new("usePrefersReducedMotion", true, false),
        HookDescriptor::new("usePrevious", true, false),
        HookDescriptor::new("useRerender", true, false),
        HookDescriptor::new("useScroll", true, false),
        HookDescriptor::new("useScrollLock", true, false),
        HookDescriptor::new("useSet", true, false),
        HookDescriptor::new("useStableCallback", true, false),
        HookDescriptor::new("useStorage", true, false),
        HookDescriptor::new("useSupported", true, false),
        HookDescriptor::new("useThrottledCallback", true, false),
        HookDescriptor::new("useTimeAgo", true, false),
        HookDescriptor::new("useTimeout", true, false),
        HookDescriptor::new("useToggle", true, false),
        HookDescriptor::new("useUndoable", true, false),
        HookDescriptor::new("useUnmount", true, false),
        HookDescriptor::new("useWindowScroll", true, false),
        HookDescriptor::new("useWindowSize", true, false),
    ]
}

pub fn module_by_specifier(specifier: &str) -> Option<NativeModule> {
    builtin_modules()
        .into_iter()
        .find(|module| module.specifier == specifier)
}
