//! Packing a finished build into a JavaScript module, for `uf build --compile`.
//!
//! A standalone binary has nothing beside it, so everything `uf build` wrote to
//! the output directory has to travel inside it. This module turns that
//! directory into one JavaScript module that the linker can bundle:
//!
//! ```js
//! export const assets = JSON.parse("{\"index.html\":{\"type\":\"text/html; charset=utf-8\",\"body\":\"PCFkb2N0eXBl…\"}}");
//! ```
//!
//! It walks with [`collect_assets`] rather than with a walk of its own, which
//! buys an invariant worth having: **what the size report measures is exactly
//! what the binary embeds**. A file the report skips as build metadata —
//! `uf-build-manifest.json` and friends — is a file no visitor can ever fetch,
//! so shipping it inside the executable would be dead weight and a small
//! disclosure of how the build was made.
//!
//! `uf build` writes those three beside the output directory now rather than
//! inside it (ubugeeei-prod/uf#339), so the walk no longer meets them here.
//! The exclusion in [`ReportOptions`] is what keeps that true for an output
//! directory a previous release wrote, which is the whole reason it stayed.

use std::fs;

use base64::Engine as _;
use camino::{Utf8Path, Utf8PathBuf};

use crate::report::{ReportError, ReportOptions, collect_assets};

/// What [`write_embedded_assets`] put in the module.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Embedded {
    /// How many files were embedded.
    pub files: usize,
    /// What they weigh before encoding, which is what the binary grows by
    /// once the runtime has parsed them back out.
    pub bytes: u64,
}

/// A build that could not be packed.
#[derive(Debug, thiserror::Error)]
pub enum EmbedError {
    /// The output directory could not be walked or measured.
    #[error(transparent)]
    Collect(#[from] ReportError),
    /// One asset could not be read.
    #[error("failed to read {path}: {source}")]
    Read {
        /// Path that failed.
        path: Utf8PathBuf,
        /// Underlying error.
        #[source]
        source: std::io::Error,
    },
    /// The generated module could not be written.
    #[error("failed to write {path}: {source}")]
    Write {
        /// Path that failed.
        path: Utf8PathBuf,
        /// Underlying error.
        #[source]
        source: std::io::Error,
    },
}

/// Write `out_dir` to `dest` as a JavaScript module.
///
/// `options` is the same exclusion list the size report uses; a caller
/// compiling into the output directory adds the binary's own name to it, so a
/// rebuild cannot embed the previous run's executable inside this one's.
///
/// # Why `JSON.parse` of a string, and not an object literal
///
/// The obvious spelling is `export const assets = { … }`, and it is
/// measurably the wrong one: a JavaScript object literal has to go through the
/// bundler's *JavaScript* parser, which builds an AST node per key and per
/// value, while the same bytes inside a string literal are one token that
/// `JSON.parse` reads at native speed at startup. The docs site's output is a
/// megabyte of base64; a project with images is tens of them, and that is the
/// size at which the difference stops being academic. The cost is one more
/// escaping pass here.
pub fn write_embedded_assets(
    out_dir: &Utf8Path,
    options: &ReportOptions,
    dest: &Utf8Path,
) -> Result<Embedded, EmbedError> {
    let entries = collect_assets(out_dir, options)?;

    let mut payload = serde_json::Map::with_capacity(entries.len());
    let mut bytes = 0u64;
    for entry in &entries {
        let path = out_dir.join(entry.path.as_str());
        let contents = fs::read(&path).map_err(|source| EmbedError::Read {
            path: path.clone(),
            source,
        })?;
        bytes += contents.len() as u64;
        payload.insert(
            entry.path.to_string(),
            serde_json::json!({
                "type": content_type(&path),
                "body": base64::engine::general_purpose::STANDARD.encode(&contents),
            }),
        );
    }

    // Both `to_string` calls are on values this function built, so neither can
    // fail on a non-string key or a NaN; the `expect` records that rather than
    // inventing an error variant nothing can reach.
    let json = serde_json::to_string(&payload).expect("a map of strings always serialises");
    let literal = serde_json::to_string(&json).expect("a string always serialises");
    let module = format!(
        "// Generated by `uf build --compile` from {out_dir}. Not checked in, not edited.\n\
         export const assets = JSON.parse({literal});\n"
    );

    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent).map_err(|source| EmbedError::Write {
            path: parent.to_path_buf(),
            source,
        })?;
    }
    fs::write(dest, module).map_err(|source| EmbedError::Write {
        path: dest.to_path_buf(),
        source,
    })?;

    Ok(Embedded {
        files: entries.len(),
        bytes,
    })
}

/// What to serve a file as, by extension.
///
/// Decided here rather than in the shim that serves it, so there is one table
/// and it is the one the build can be tested against. Anything unrecognised is
/// `application/octet-stream`: a browser asked to guess at a type is a worse
/// outcome than a download, and a build that emits a type this list has never
/// heard of is a bug report worth receiving.
#[must_use]
pub fn content_type(path: &Utf8Path) -> &'static str {
    match path
        .extension()
        .unwrap_or_default()
        .to_ascii_lowercase()
        .as_str()
    {
        "html" | "htm" => "text/html; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" | "map" => "application/json; charset=utf-8",
        "webmanifest" => "application/manifest+json; charset=utf-8",
        "txt" => "text/plain; charset=utf-8",
        "xml" => "application/xml; charset=utf-8",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "avif" => "image/avif",
        "ico" => "image/x-icon",
        "woff" => "font/woff",
        "woff2" => "font/woff2",
        "ttf" => "font/ttf",
        "otf" => "font/otf",
        "wasm" => "application/wasm",
        "pdf" => "application/pdf",
        "mp4" => "video/mp4",
        "webm" => "video/webm",
        _ => "application/octet-stream",
    }
}
