[package]
name = "uf_vrt"
description = "Native visual regression testing contracts exposed as @uniflowed/vrt."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
compact_str.workspace = true
serde.workspace = true
smallvec.workspace = true
uf_browser = { path = "../uf_browser" }
