//! Golden-file tests for the Flow printer.
//!
//! Every `<name>.js` under `tests/fixtures/` is formatted and compared to
//! `<name>.expected.js`, which was generated by Prettier 3 with the
//! `hermes` parser:
//!
//! ```sh
//! npx prettier --parser hermes --plugin prettier-plugin-hermes-parser \
//!   --print-width 100 tests/fixtures/<name>.js
//! ```
//!
//! The four `config_*` fixtures use the Prettier options that match the
//! non-default `FmtConfig` they are named for (`--print-width 40`,
//! `--single-quote`, `--no-semi`, `--tab-width 4`). Keeping the
//! expectations byte-identical to Prettier's own output is what makes
//! "Prettier compatible" a claim the test suite can check rather than a
//! description of intent.
//!
//! On top of the golden comparison every fixture is held to the printer's
//! four guarantees: the output is a fixed point, formatting is idempotent,
//! the tree survives, and so does every comment.

mod support;

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use uf_config::{FmtConfig, QuoteStyle};
use uf_fmt::format_source;

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

/// A default config with `mutate` applied.
///
/// `FmtConfig` is `#[non_exhaustive]`, because every feature that lands
/// adds a knob to it and a struct literal would break on each one.
fn config_with(mutate: impl FnOnce(&mut FmtConfig)) -> FmtConfig {
    let mut config = FmtConfig::default();
    mutate(&mut config);
    config
}

/// The configuration a fixture is formatted with, from its name.
fn config_for(name: &str) -> FmtConfig {
    match name {
        "config_narrow_lines" => config_with(|config| config.line_width = 40),
        "config_single_quotes" => config_with(|config| config.quotes = QuoteStyle::Single),
        "config_no_semicolons" => config_with(|config| config.semicolons = false),
        "config_wide_indent" => config_with(|config| config.indent_width = 4),
        _ => FmtConfig::default(),
    }
}

/// Every fixture, keyed by name, as `(input, expected)` pairs.
fn fixtures() -> BTreeMap<String, (String, String)> {
    let dir = fixtures_dir();
    let entries = fs::read_dir(&dir)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", dir.display()));

    let mut fixtures = BTreeMap::new();
    for entry in entries {
        let path = entry.expect("readable directory entry").path();
        let file_name = path
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or_default()
            .to_string();
        let Some(name) = file_name.strip_suffix(".js") else {
            continue;
        };
        if name.ends_with(".expected") {
            continue;
        }
        let expected_path = dir.join(format!("{name}.expected.js"));
        let expected = fs::read_to_string(&expected_path).unwrap_or_else(|error| {
            panic!("missing {}: {error}", expected_path.display());
        });
        let input = fs::read_to_string(&path).expect("readable fixture input");
        fixtures.insert(name.to_string(), (input, expected));
    }

    assert!(
        fixtures.len() >= 20,
        "expected a broad fixture corpus, found {} in {}",
        fixtures.len(),
        dir.display()
    );
    fixtures
}

/// Set `UF_FMT_BLESS=1` to rewrite the `.expected.js` files from the
/// current output. Only do that after checking the new output against
/// Prettier itself; review the diff before committing it.
fn blessing() -> bool {
    std::env::var_os("UF_FMT_BLESS").is_some()
}

#[test]
fn fixtures_match_prettiers_output() {
    let dir = fixtures_dir();
    for (name, (input, expected)) in fixtures() {
        let result = format_source(&input, &config_for(&name)).expect("fixture formats");
        if blessing() {
            fs::write(dir.join(format!("{name}.expected.js")), &result.output)
                .expect("writable fixture");
            continue;
        }
        similar_asserts::assert_eq!(result.output, expected, "fixture {name} formatted wrong");
    }
    assert!(
        !blessing(),
        "fixtures were rewritten; rerun without UF_FMT_BLESS"
    );
}

#[test]
fn expected_output_is_already_formatted() {
    for (name, (_, expected)) in fixtures() {
        let result = format_source(&expected, &config_for(&name)).expect("fixture formats");
        assert!(
            !result.changed,
            "fixture {name} expected output is not a fixed point"
        );
    }
}

#[test]
fn fixtures_are_idempotent() {
    for (name, (input, _)) in fixtures() {
        let config = config_for(&name);
        let once = format_source(&input, &config)
            .expect("fixture formats")
            .output;
        let twice = format_source(&once, &config)
            .expect("fixture formats")
            .output;
        similar_asserts::assert_eq!(once, twice, "fixture {name} is not idempotent");
    }
}

#[test]
fn fixtures_preserve_the_tree() {
    for (name, (input, _)) in fixtures() {
        let output = format_source(&input, &config_for(&name))
            .expect("fixture formats")
            .output;
        similar_asserts::assert_eq!(
            support::structure(&input),
            support::structure(&output),
            "fixture {name} changed the program"
        );
    }
}

#[test]
fn fixtures_preserve_every_comment() {
    for (name, (input, _)) in fixtures() {
        let output = format_source(&input, &config_for(&name))
            .expect("fixture formats")
            .output;
        assert_eq!(
            support::comment_multiset(&input),
            support::comment_multiset(&output),
            "fixture {name} lost, gained or rewrote a comment"
        );
    }
}

#[test]
fn every_expected_file_has_an_input() {
    let dir = fixtures_dir();
    for entry in fs::read_dir(&dir).expect("readable fixture directory") {
        let path = entry.expect("readable directory entry").path();
        let file_name = path
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or_default()
            .to_string();
        if let Some(name) = file_name.strip_suffix(".expected.js") {
            let input = dir.join(format!("{name}.js"));
            assert!(input.exists(), "orphan fixture {}", path.display());
        }
    }
}
