[package]
name = "uniflowed_router"
description = "File-system router discovery and Flow type generation for uniflowed apps."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
camino.workspace = true
compact_str.workspace = true
uniflowed_config = { path = "../uniflowed_config" }
thiserror.workspace = true
walkdir.workspace = true

[dev-dependencies]
criterion.workspace = true
tempfile.workspace = true

[[bench]]
name = "router"
harness = false
