use camino::Utf8Path;

use super::*;
use crate::action::BuildId;
use crate::graph::{EntryKind, RscGraphBuilder};

/// A registry over `sources`, with `entries` as server entry points.
///
/// A fresh build id every time, because that is the thing a generated file
/// must not depend on.
fn registry(sources: &[(&str, &str)], entries: &[&str]) -> ServerActionRegistry {
    let mut builder = RscGraphBuilder::new();
    for (path, source) in sources {
        builder.add_source(*path, source);
    }
    for entry in entries {
        builder.add_entry(*entry, EntryKind::Server);
    }
    let graph = builder.build();
    ServerActionRegistry::from_graph(&graph, &BuildId::generate())
}

/// A page that imports a client component and an action module: the shape
/// that makes an action a callable endpoint.
fn a_project_with_one_action() -> ServerActionRegistry {
    registry(
        &[
            (
                "app/_uf.page.js",
                "import Counter from \"./Counter.js\";\nimport { createUser } from \"./actions.js\";\n",
            ),
            ("app/Counter.js", "\"use client\";\n"),
            (
                "app/actions.js",
                "\"use server\";\n\nexport async function createUser(name: string): Promise<void> {}\n",
            ),
        ],
        &["app/_uf.page.js"],
    )
}

#[test]
fn a_callable_export_becomes_a_row_pointing_at_its_module() {
    let generated = generate_server_action_types(&a_project_with_one_action());

    assert!(
        generated.contains("import typeof * as Module0 from \"./app/actions.js\";"),
        "{generated}"
    );
    assert!(
        generated.contains("  \"app/actions.js#createUser\": Module0[\"createUser\"],"),
        "{generated}"
    );
    assert!(generated.contains("export type ServerActionName = $Keys<ServerActions>;"));
    assert!(generated.contains(
        "export type ServerActionArgs<Name extends ServerActionName> = \
         Parameters<ServerActions[Name]>;"
    ));
    assert!(generated.contains(
        "export type ServerActionResult<Name extends ServerActionName> = \
         ReturnType<ServerActions[Name]>;"
    ));
}

/// It says it is generated, and it says it in the first line a reader sees.
#[test]
fn the_generated_file_says_it_is_generated() {
    let generated = generate_server_action_types(&a_project_with_one_action());

    assert!(generated.starts_with("// @flow\n"), "{generated}");
    assert!(
        generated.contains("Generated by `uf prepare`. Do not edit"),
        "{generated}"
    );
}

/// Two runs over the same sources produce the same bytes.
///
/// The registry is keyed on a build id that changes every build, so this is
/// only true because no id reaches the file: `module#export` is the key.
#[test]
fn two_builds_of_the_same_sources_generate_the_same_bytes() {
    let sources = [
        (
            "app/_uf.page.js",
            "import C from \"./C.js\";\nimport { b, a } from \"./actions.js\";\n",
        ),
        ("app/C.js", "\"use client\";\n"),
        (
            "app/actions.js",
            "\"use server\";\n\nexport async function b(): Promise<void> {}\nexport async function a(): Promise<void> {}\n",
        ),
    ];
    let first = registry(&sources, &["app/_uf.page.js"]);
    let second = registry(&sources, &["app/_uf.page.js"]);

    assert_ne!(
        first.build_fingerprint(),
        second.build_fingerprint(),
        "the two runs must not share a build id, or this proves nothing"
    );
    assert_eq!(
        generate_server_action_types(&first),
        generate_server_action_types(&second)
    );
}

/// Rows are ordered by key, whatever order the sources were declared in.
#[test]
fn rows_are_ordered_by_name() {
    let generated = generate_server_action_types(&registry(
        &[
            (
                "app/_uf.page.js",
                "import C from \"./C.js\";\nimport { z } from \"./z.js\";\nimport { a } from \"./a.js\";\n",
            ),
            ("app/C.js", "\"use client\";\n"),
            (
                "app/z.js",
                "\"use server\";\n\nexport async function z(): Promise<void> {}\n",
            ),
            (
                "app/a.js",
                "\"use server\";\n\nexport async function a(): Promise<void> {}\n",
            ),
        ],
        &["app/_uf.page.js"],
    ));

    let a = generated.find("app/a.js#a").expect("the first action");
    let z = generated.find("app/z.js#z").expect("the second action");
    assert!(a < z, "{generated}");
    assert!(generated.contains("import typeof * as Module0 from \"./app/a.js\";"));
    assert!(generated.contains("import typeof * as Module1 from \"./app/z.js\";"));
}

/// A project with no server actions still gets a nameable `ServerActionName`.
///
/// `$Keys<{}>` is `empty`, so every name is rejected — the same choice the
/// router makes with `RoutePath = empty` for a project with no routes.
#[test]
fn a_project_with_no_actions_generates_an_empty_table() {
    let generated = generate_server_action_types(&registry(
        &[("app/_uf.page.js", "export default function Page() {}\n")],
        &["app/_uf.page.js"],
    ));

    assert!(
        generated.contains("export type ServerActions = {};"),
        "{generated}"
    );
    assert!(generated.contains("export type ServerActionName = $Keys<ServerActions>;"));
    assert!(!generated.contains("\nimport typeof"), "{generated}");
}

/// An action no client boundary reaches is not given a call-site type.
///
/// The manifest applies the same rule to what it publishes; a type that says
/// "you can call this" over something the build will not expose is the same
/// lie in a different file.
#[test]
fn an_action_no_client_can_reach_is_not_in_the_table() {
    let generated = generate_server_action_types(&registry(
        &[
            (
                "app/_uf.page.js",
                "import { hidden } from \"./actions.js\";\n",
            ),
            (
                "app/actions.js",
                "\"use server\";\n\nexport async function hidden(): Promise<void> {}\n",
            ),
        ],
        &["app/_uf.page.js"],
    ));

    assert!(!generated.contains("hidden"), "{generated}");
    assert!(
        generated.contains("export type ServerActions = {};"),
        "{generated}"
    );
}

/// An inline `"use server"` closure has no export name to point at.
#[test]
fn an_inline_closure_is_left_to_the_manifest() {
    let registry = registry(
        &[
            (
                "app/_uf.page.js",
                "import C from \"./C.js\";\n\nexport default function Page() {\n  async function save() {\n    \"use server\";\n  }\n  return save;\n}\n",
            ),
            ("app/C.js", "\"use client\";\n"),
        ],
        &["app/_uf.page.js"],
    );

    // The closure is registered — this is not a test that the scanner missed it.
    assert!(
        registry
            .actions()
            .iter()
            .any(|action| action.kind == ServerActionKind::InlineClosure),
        "the fixture has no inline closure to leave out"
    );
    assert!(server_action_types(&registry).is_empty());
}

/// A quote in a module path does not produce a file that will not parse.
#[test]
fn an_awkward_path_is_escaped_rather_than_emitted_raw() {
    assert_eq!(escape_flow_string("app/\"odd\".js"), "app/\\\"odd\\\".js");
    assert_eq!(escape_flow_string("a\\b"), "a\\\\b");
    assert_eq!(escape_flow_string("a\nb"), "a\\nb");
    assert_eq!(escape_flow_string("plain/path.js"), "plain/path.js");
}

#[test]
fn writing_puts_the_file_in_the_project_root() {
    let dir = tempfile::tempdir().expect("a temporary directory");
    let root = Utf8Path::from_path(dir.path()).expect("a UTF-8 path");
    let registry = a_project_with_one_action();

    let written = write_server_action_types(root, &registry).expect("a written file");

    assert_eq!(written, root.join("server-actions.js"));
    assert_eq!(
        std::fs::read_to_string(&written).expect("the file"),
        generate_server_action_types(&registry)
    );
}
