//! What a task said it reads, resolved to files and their contents.
//!
//! # Why the walk starts where it does
//!
//! A pattern's literal prefix is where its walk begins: `target/release/uf` is
//! a file and is stat'd, `packages/**/*.js` walks `packages/`, and `**/*.sh`
//! walks the project. That is not only speed — it is what lets the walk prune
//! [`PRUNED`] without lying. `node_modules` and `target` are where a
//! repository keeps the things a glob was never meant to sweep up, and a
//! `**/*.js` that hashed thirty thousand installed modules would invalidate on
//! every `npm install` and cost more than the task it is meant to save. But a
//! task *may* legitimately name a file inside one — `target/release/uf` is the
//! most important input in this repository — and starting the walk at the
//! literal prefix means the pruning never applies to a directory the pattern
//! named on the way in. Pruning is for what a `**` wanders into.

use std::collections::BTreeMap;
use std::path::Path;

use camino::{Utf8Path, Utf8PathBuf};
use globset::{Glob, GlobBuilder, GlobSet, GlobSetBuilder};
use walkdir::WalkDir;

use crate::digest::{Digest, Fields, file_digest, hex};

/// Directory names a `**` does not descend into.
///
/// Named rather than read from `.gitignore`: a cache key has to mean the same
/// thing on a machine whose ignore file differs, and these six are what every
/// checkout of every project puts machine-generated bytes in.
pub(crate) const PRUNED: [&str; 6] = [
    ".git",
    ".uf",
    ".uniflowed",
    "dist",
    "node_modules",
    "target",
];

/// How many files one task's inputs may resolve to.
///
/// A ceiling rather than a target: past it the patterns are describing the
/// whole checkout, and the honest answer is that uf will not key on it. Not
/// caching is the failure mode being chosen here, which is the safe one.
pub(crate) const MAX_INPUT_FILES: usize = 200_000;

/// One file, and what was in it.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct InputFile {
    /// Where it is, relative to the project root, with `/` separators.
    pub path: String,
    /// The digest of its contents.
    pub digest: String,
}

/// Why a task's inputs could not be turned into a key.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InputError {
    /// A pattern globset would not accept, and what it said.
    BadPattern { pattern: String, reason: String },
    /// A file matched and could not be read, or was too large to hash.
    Unreadable { path: String },
    /// The patterns matched more files than [`MAX_INPUT_FILES`].
    TooMany { matched: usize },
}

impl std::fmt::Display for InputError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::BadPattern { pattern, reason } => {
                write!(f, "{pattern:?} is not a valid pattern: {reason}")
            }
            Self::Unreadable { path } => {
                write!(f, "{path} could not be read")
            }
            Self::TooMany { matched } => write!(
                f,
                "these patterns match {matched} files, past the {MAX_INPUT_FILES} uf will key on"
            ),
        }
    }
}

/// A compiled `inputs` or `outputs` list.
#[derive(Debug)]
pub(crate) struct Patterns {
    include: GlobSet,
    exclude: GlobSet,
    /// Where each include pattern's walk begins, deduplicated.
    roots: Vec<Utf8PathBuf>,
    /// Whether any include pattern walks the project root itself.
    from_root: bool,
    /// The patterns as written, in the order written.
    written: Vec<String>,
}

impl Patterns {
    /// Compile `patterns`. A pattern beginning `!` excludes what it matches.
    pub(crate) fn compile<S: AsRef<str>>(patterns: &[S]) -> Result<Self, InputError> {
        let mut include = GlobSetBuilder::new();
        let mut exclude = GlobSetBuilder::new();
        let mut roots: Vec<Utf8PathBuf> = Vec::new();
        let mut from_root = false;
        let mut written = Vec::with_capacity(patterns.len());
        for pattern in patterns {
            let pattern = pattern.as_ref();
            written.push(pattern.to_owned());
            let (negated, body) = match pattern.strip_prefix('!') {
                Some(body) => (true, body),
                None => (false, pattern),
            };
            let glob = compile_one(body).map_err(|reason| InputError::BadPattern {
                pattern: pattern.to_owned(),
                reason,
            })?;
            if negated {
                exclude.add(glob);
                continue;
            }
            include.add(glob);
            match walk_root(body) {
                Some(root) => roots.push(root),
                None => from_root = true,
            }
        }
        let build = |builder: GlobSetBuilder| {
            builder.build().map_err(|error| InputError::BadPattern {
                pattern: String::from("<set>"),
                reason: error.to_string(),
            })
        };
        roots.sort();
        roots.dedup();
        // A root under another root would walk the same files twice. The sort
        // above puts a parent before its children, so one pass keeps the
        // shortest of each chain.
        let mut kept: Vec<Utf8PathBuf> = Vec::with_capacity(roots.len());
        for root in roots {
            if kept.iter().any(|existing| root.starts_with(existing)) {
                continue;
            }
            kept.push(root);
        }
        Ok(Self {
            include: build(include)?,
            exclude: build(exclude)?,
            roots: kept,
            from_root,
            written,
        })
    }

    /// Whether `relative` is matched by an include and by no exclude.
    fn matches(&self, relative: &str) -> bool {
        self.include.is_match(relative) && !self.exclude.is_match(relative)
    }

    /// Every file under `root` these patterns match, sorted by path, with the
    /// digest of each one's contents.
    pub(crate) fn resolve(&self, root: &Utf8Path) -> Result<Vec<InputFile>, InputError> {
        // A map rather than a vector: two patterns matching one file must
        // contribute one entry, or the key would depend on how the patterns
        // were spelled rather than on what they matched.
        let mut found: BTreeMap<String, Digest> = BTreeMap::new();
        let mut walks: Vec<Utf8PathBuf> = Vec::with_capacity(self.roots.len() + 1);
        if self.from_root {
            walks.push(root.to_path_buf());
        }
        // A walk from the project root reaches everything except what it
        // prunes, so alongside it only the roots that *are* pruned still need
        // one of their own — which is how `["**", "target/release/uf"]` sees
        // both the project and the binary. Any other root would be a second
        // pass over files the first walk already matched.
        walks.extend(
            self.roots
                .iter()
                .filter(|path| !self.from_root || path.iter().any(|part| PRUNED.contains(&part)))
                .map(|path| root.join(path)),
        );
        for start in walks {
            for entry in WalkDir::new(start.as_std_path())
                .follow_links(false)
                .into_iter()
                .filter_entry(|entry| entry.depth() == 0 || !is_pruned(entry.path()))
            {
                let Ok(entry) = entry else {
                    // A directory that cannot be opened is not a file that
                    // matched, and a task whose inputs live somewhere
                    // unreadable finds that out when it runs.
                    continue;
                };
                if !entry.file_type().is_file() {
                    continue;
                }
                let Ok(path) = Utf8Path::from_path(entry.path()).ok_or(()) else {
                    continue;
                };
                let Ok(relative) = path.strip_prefix(root) else {
                    continue;
                };
                let relative = relative.as_str();
                if !self.matches(relative) {
                    continue;
                }
                if found.len() >= MAX_INPUT_FILES {
                    return Err(InputError::TooMany {
                        matched: found.len() + 1,
                    });
                }
                let digest = file_digest(entry.path()).ok_or_else(|| InputError::Unreadable {
                    path: relative.to_owned(),
                })?;
                found.insert(relative.to_owned(), digest);
            }
        }
        Ok(found
            .into_iter()
            .map(|(path, digest)| InputFile {
                path,
                digest: hex(&digest),
            })
            .collect())
    }

    /// A digest over the patterns as written and every file they matched.
    ///
    /// The patterns themselves are in it, not only their matches: narrowing
    /// `packages/**/*.js` to `packages/core/**/*.js` on a checkout where the
    /// two happen to match the same files is still a task that has been told
    /// to read something different.
    pub(crate) fn digest(&self, domain: &str, files: &[InputFile]) -> Digest {
        let mut fields = Fields::new(domain);
        for pattern in &self.written {
            fields.push(pattern);
        }
        fields.push("--");
        for file in files {
            fields.push(&file.path).push(&file.digest);
        }
        fields.finish()
    }
}

/// Compile one pattern body.
///
/// `literal_separator` is on, so `*` stops at a `/` and only `**` crosses one
/// — the reading everybody who has written a `.gitignore` already has. A bare
/// name is anchored at the project root for the same reason: `uf.config.js`
/// means the one at the root, and a task that wants every one of them says
/// `**/uf.config.js`.
fn compile_one(body: &str) -> Result<Glob, String> {
    GlobBuilder::new(body)
        .literal_separator(true)
        .empty_alternates(true)
        .build()
        .map_err(|error| error.kind().to_string())
}

/// Where `pattern`'s walk begins, or [`None`] for the project root.
fn walk_root(pattern: &str) -> Option<Utf8PathBuf> {
    let mut root = Utf8PathBuf::new();
    for segment in pattern.split('/') {
        if segment.is_empty() || segment.contains(['*', '?', '[', ']', '{', '}']) {
            break;
        }
        root.push(segment);
    }
    (!root.as_str().is_empty()).then_some(root)
}

/// Whether a walk should not descend into `path`.
fn is_pruned(path: &Path) -> bool {
    path.file_name()
        .and_then(|name| name.to_str())
        .is_some_and(|name| PRUNED.contains(&name))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn project(files: &[(&str, &str)]) -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        for (name, source) in files {
            let path = dir.path().join(name);
            std::fs::create_dir_all(path.parent().unwrap()).unwrap();
            std::fs::write(path, source).unwrap();
        }
        dir
    }

    fn resolve(dir: &tempfile::TempDir, patterns: &[&str]) -> Vec<String> {
        let root = Utf8Path::from_path(dir.path()).unwrap();
        Patterns::compile(patterns)
            .unwrap()
            .resolve(root)
            .unwrap()
            .into_iter()
            .map(|file| file.path)
            .collect()
    }

    #[test]
    fn a_star_does_not_cross_a_directory_boundary() {
        let dir = project(&[("src/a.js", "a"), ("src/deep/b.js", "b")]);
        assert_eq!(resolve(&dir, &["src/*.js"]), vec!["src/a.js"]);
        assert_eq!(
            resolve(&dir, &["src/**/*.js"]),
            vec!["src/a.js", "src/deep/b.js"]
        );
    }

    #[test]
    fn a_bang_pattern_excludes() {
        let dir = project(&[("src/a.js", "a"), ("src/a.test.js", "t")]);
        assert_eq!(
            resolve(&dir, &["src/**/*.js", "!src/**/*.test.js"]),
            vec!["src/a.js"]
        );
    }

    /// The pruned directories are what a `**` must not wander into, and the
    /// literal prefix is how a task reaches into one on purpose.
    #[test]
    fn a_walk_prunes_generated_directories_but_a_named_path_still_resolves() {
        let dir = project(&[
            ("src/a.js", "a"),
            ("node_modules/dep/index.js", "d"),
            ("target/release/uf", "binary"),
        ]);
        assert_eq!(resolve(&dir, &["**/*.js"]), vec!["src/a.js"]);
        assert_eq!(
            resolve(&dir, &["target/release/uf"]),
            vec!["target/release/uf"]
        );
    }

    /// The case `fmt:check` in this repository is: everything the project has,
    /// plus one path inside a directory a `**` does not enter.
    #[test]
    fn a_sweep_of_the_project_and_a_named_path_inside_a_pruned_directory() {
        let dir = project(&[
            ("src/a.js", "a"),
            ("node_modules/dep/index.js", "d"),
            ("target/release/uf", "binary"),
        ]);
        assert_eq!(
            resolve(&dir, &["**", "target/release/uf"]),
            vec!["src/a.js", "target/release/uf"]
        );
    }

    #[test]
    fn two_patterns_matching_one_file_contribute_one_entry() {
        let dir = project(&[("src/a.js", "a")]);
        assert_eq!(resolve(&dir, &["src/*.js", "**/*.js"]), vec!["src/a.js"]);
    }

    #[test]
    fn the_patterns_are_in_the_digest_even_when_the_matches_are_equal() {
        let dir = project(&[("src/a.js", "a")]);
        let root = Utf8Path::from_path(dir.path()).unwrap();
        let one = Patterns::compile(&["src/*.js"]).unwrap();
        let two = Patterns::compile(&["src/**/*.js"]).unwrap();
        let files = one.resolve(root).unwrap();
        assert_eq!(files, two.resolve(root).unwrap());
        assert_ne!(one.digest("d", &files), two.digest("d", &files));
    }

    #[test]
    fn a_pattern_that_does_not_compile_is_named() {
        let error = Patterns::compile(&["src/[".to_owned()]).unwrap_err();
        assert!(
            matches!(&error, InputError::BadPattern { pattern, .. } if pattern == "src/["),
            "{error:?}"
        );
    }

    #[test]
    fn a_walk_root_stops_at_the_first_wildcard() {
        assert_eq!(walk_root("target/release/uf").unwrap(), "target/release/uf");
        assert_eq!(walk_root("packages/**/*.js").unwrap(), "packages");
        assert_eq!(walk_root("**/*.sh"), None);
    }
}
