//! Decoding an image once, and writing the sizes and formats a page asks for.
//!
//! # Why this is Rust
//!
//! Decoding, resizing and re-encoding every image in a project is repeated
//! CPU-bound work over the whole repository — the case `docs/architecture.md`
//! names when it says native hot paths belong in native code, and the case a
//! JavaScript dependency serves worst. It is also the work that makes an
//! `<img>` worth writing as a component: a `srcset` can only be generated by
//! something that knows what other sizes exist, and the only way to know is to
//! have made them.
//!
//! # What this does
//!
//! One decode per source. From it:
//!
//! * a variant at each declared width that is not larger than the source —
//!   uf never upscales, because a 640px source stretched to 1920 is bytes
//!   spent making the picture worse — plus one at the source's own width, so
//!   there is always a largest;
//! * each variant re-encoded in the source's own format, which is the
//!   fallback every browser takes;
//! * each variant re-encoded in WebP as well, **kept only when the WebP is
//!   smaller at every one of those widths** (see below);
//! * a blur placeholder, which is free: the decode has already happened — for
//!   an opaque image, since one painted under a transparent one never goes
//!   away.
//!
//! # Formats, and the one this cannot do
//!
//! The encoders here are pure Rust and there is no C toolchain and no native
//! library in the build. That buys PNG, JPEG, and *lossless* WebP, and it
//! stops there:
//!
//! * **AVIF is not emitted.** It needs an AV1 encoder. `ravif`/`rav1e` is pure
//!   Rust and would work, and it is not here: it adds around eighty transitive
//!   crates to this workspace, and it compiles under a `lto = "fat"`,
//!   `codegen-units = 1` release profile that every CI job pays for. That is a
//!   real decision with a real cost on both sides and it should be made
//!   deliberately, not smuggled in under an asset pipeline. When it is made,
//!   it drops into [`encode`] as one more candidate and the comparison below
//!   picks it up with no other change.
//! * **Lossy WebP is not emitted.** There is no pure-Rust encoder for it;
//!   `libwebp` is C.
//!
//! So the honest form of "modern formats with a fallback" is not "always emit
//! WebP". Measured against this build's own PNG encoder — `CompressionType::
//! Best` with adaptive filtering, which is a strong PNG — the lossless WebP
//! this build can write is smaller on some images and much larger on others:
//!
//! ```text
//! source            at source width   resampled to 640   resampled to 320
//! logo                     0.56x             0.87x              0.92x
//! smooth gradient          0.29x             0.59x              0.71x
//! UI screenshot            0.82x             6.82x              6.19x
//! photographic noise       1.00x             1.06x              1.08x
//! ```
//!
//! (WebP bytes over PNG bytes; under 1.00 means WebP won.) The screenshot row
//! is the one that decides the design. Hard edges resample into rings of
//! near-colours, PNG's adaptive filtering absorbs those and this encoder does
//! not, and the result is a "modern format" seven times the size of the
//! fallback. Emitting it anyway and letting a `<picture>` prefer it would make
//! that page slower while the markup claimed an optimisation.
//!
//! [`transform`] therefore encodes both and keeps the alternative only when it
//! is smaller than the fallback at *every* width, and records the measurement
//! when it is not. Every width, not each width independently: a `<picture>`
//! offers a `<source>` as an equivalent rendering of the whole image, so a
//! browser that takes one then chooses a width from that source's `srcset`
//! alone — and a source missing the narrow rungs sends a phone a wide one. The
//! rule is per-image and measured rather than per-format by fiat, the numbers
//! are reported either way, and the day an AVIF encoder is added it is judged
//! the same way.

use camino::{Utf8Path, Utf8PathBuf};
use image::{DynamicImage, ImageEncoder as _, imageops::FilterType};
use serde::{Deserialize, Serialize};

use crate::name::hashed_name_with_suffix;

#[cfg(test)]
mod tests;

/// Largest source image uf will decode, in pixels.
///
/// An image path can come from a dependency and the decoded buffer is four
/// bytes a pixel, so the allocation is bounded rather than trusted: this is
/// 512 megapixels, about 2 GiB decoded, and far past any photograph. The
/// dimensions are read from the header before anything is decoded, so an image
/// over the limit costs a header parse rather than the allocation.
pub const MAX_SOURCE_PIXELS: u64 = 512 * 1024 * 1024;

/// Largest source file uf will read.
pub const MAX_SOURCE_BYTES: u64 = 256 * 1024 * 1024;

/// Width of the blur placeholder, in pixels.
///
/// Small enough that the data URI is a few hundred bytes of the document, big
/// enough to carry the picture's colours and rough shape. The browser scales
/// it up and the blur does the rest.
pub const BLUR_WIDTH: u32 = 16;

/// The filter every resize uses.
///
/// Lanczos3 over anything cheaper: this runs once per image per build, not per
/// request, so the extra milliseconds buy sharpness in a file that will be
/// served a great many times.
const RESIZE_FILTER: FilterType = FilterType::Lanczos3;

/// An image that could not be processed.
#[derive(Debug, thiserror::Error)]
pub enum ImageError {
    /// The file could not be read.
    #[error("failed to read {path}: {source}")]
    Read {
        /// Path that failed.
        path: Utf8PathBuf,
        /// Underlying error.
        #[source]
        source: std::io::Error,
    },
    /// The file is larger than [`MAX_SOURCE_BYTES`].
    #[error("{path} is {bytes} bytes, larger than the {MAX_SOURCE_BYTES} byte limit for an image")]
    TooLarge {
        /// Path that was too large.
        path: Utf8PathBuf,
        /// Its size.
        bytes: u64,
    },
    /// The image is larger than [`MAX_SOURCE_PIXELS`].
    #[error("{path} is {width}x{height}, more than the {MAX_SOURCE_PIXELS} pixel limit")]
    TooManyPixels {
        /// Path that was too large.
        path: Utf8PathBuf,
        /// Its width.
        width: u32,
        /// Its height.
        height: u32,
    },
    /// The bytes are not an image this crate can decode.
    #[error("{path} could not be decoded: {source}")]
    Decode {
        /// Path that failed.
        path: Utf8PathBuf,
        /// Underlying error.
        #[source]
        source: image::ImageError,
    },
    /// A variant could not be encoded.
    #[error("failed to encode {path} as {format}: {source}")]
    Encode {
        /// Path that failed.
        path: Utf8PathBuf,
        /// The format being written.
        format: &'static str,
        /// Underlying error.
        #[source]
        source: image::ImageError,
    },
    /// A variant could not be written.
    #[error("failed to write {path}: {source}")]
    Write {
        /// Path that failed.
        path: Utf8PathBuf,
        /// Underlying error.
        #[source]
        source: std::io::Error,
    },
}

/// A format uf emits.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Emitted {
    /// PNG, deflate-compressed and lossless.
    Png,
    /// JPEG, at the configured quality.
    Jpeg,
    /// WebP, lossless — the only WebP mode a pure-Rust encoder offers.
    Webp,
    /// The source's own bytes, copied. Nothing was decoded and nothing resized.
    Original,
}

impl Emitted {
    /// The file extension.
    #[must_use]
    pub const fn extension(self) -> &'static str {
        match self {
            Self::Png => "png",
            Self::Jpeg => "jpg",
            Self::Webp => "webp",
            Self::Original => "",
        }
    }

    /// The media type, for a `<source type>` and for a server.
    #[must_use]
    pub fn mime(self) -> &'static str {
        match self {
            Self::Png => "image/png",
            Self::Jpeg => "image/jpeg",
            Self::Webp => "image/webp",
            Self::Original => "application/octet-stream",
        }
    }
}

/// What a project asked uf to do with one image.
#[derive(Debug, Clone)]
pub struct ImageRequest<'a> {
    /// The image, as the author wrote it.
    pub source: &'a Utf8Path,
    /// The widths a layout asks for. Ones larger than the source are dropped.
    pub widths: &'a [u32],
    /// JPEG quality, 1–100.
    pub quality: u8,
    /// Whether to produce the blur placeholder.
    pub blur: bool,
    /// Where the variants are written.
    pub out_dir: &'a Utf8Path,
}

/// One emitted file.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Variant {
    /// The emitted file's name, content-hashed.
    pub file: String,
    /// Its width in pixels — the number that goes in the `srcset` descriptor.
    pub width: u32,
    /// Its height in pixels.
    pub height: u32,
    /// Its format.
    pub format: Emitted,
    /// Its media type.
    pub mime: String,
    /// Its size on disk.
    pub bytes: u64,
}

/// A format that was encoded and thrown away, and the numbers that decided it.
///
/// Kept and reported rather than dropped silently. A project that expected a
/// WebP and did not get one is entitled to see that uf made one, measured it,
/// and found it larger — and to see by how much.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Declined {
    /// The format that lost.
    pub format: Emitted,
    /// The width it was encoded at.
    pub width: u32,
    /// What it weighed.
    pub bytes: u64,
    /// What the fallback at the same width weighed.
    pub fallback_bytes: u64,
}

/// One source image, and everything emitted from it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ImageAsset {
    /// The source's intrinsic width, when it was decoded.
    ///
    /// This is what stops the page reflowing: a browser given a width, a
    /// height and a CSS size reserves the box before a byte of the image
    /// arrives. `None` means uf did not decode the file and therefore does not
    /// know — see [`note`](Self::note).
    pub width: Option<u32>,
    /// The source's intrinsic height.
    pub height: Option<u32>,
    /// The format the `<img>` falls back to.
    pub format: Emitted,
    /// Every emitted file, widest last within each format.
    pub variants: Vec<Variant>,
    /// The blur placeholder as a `data:` URI, when one was asked for and made.
    pub blur: Option<String>,
    /// Formats encoded and rejected as larger than the fallback.
    pub declined: Vec<Declined>,
    /// Why nothing was resized, when nothing was.
    ///
    /// Present exactly when the file was passed through untouched. It says so
    /// in words rather than leaving a caller to infer it from a single-variant
    /// list, because "uf cannot resize this" and "this image was already the
    /// right size" must not look the same.
    pub note: Option<String>,
}

impl ImageAsset {
    /// The variants in one format, narrowest first.
    #[must_use]
    pub fn in_format(&self, format: Emitted) -> Vec<&Variant> {
        let mut found: Vec<&Variant> = self
            .variants
            .iter()
            .filter(|variant| variant.format == format)
            .collect();
        found.sort_by_key(|variant| variant.width);
        found
    }

    /// Every format emitted, the fallback last.
    ///
    /// The order a `<picture>` wants: alternatives first, because a browser
    /// takes the first `<source>` it understands, and the format every browser
    /// understands is the one that must not be offered before them.
    #[must_use]
    pub fn formats(&self) -> Vec<Emitted> {
        let mut formats: Vec<Emitted> = self
            .variants
            .iter()
            .map(|variant| variant.format)
            .filter(|format| *format != self.format)
            .collect();
        formats.sort_unstable();
        formats.dedup();
        formats.push(self.format);
        formats
    }
}

/// Decode one image and write every size and format a page asked for.
///
/// # Errors
///
/// [`ImageError`] when the source cannot be read, is over a limit, cannot be
/// decoded by a format this crate was built with, or cannot be written to
/// `out_dir`.
pub fn transform(request: &ImageRequest<'_>) -> Result<ImageAsset, ImageError> {
    let bytes = read_bounded(request.source)?;
    std::fs::create_dir_all(request.out_dir).map_err(|source| ImageError::Write {
        path: request.out_dir.to_owned(),
        source,
    })?;

    let Some(format) = decodable(&bytes) else {
        // Not decodable *for re-encoding*, which is not the same as
        // unreadable: a WebP has a decoder here and is passed through anyway,
        // and it can still be measured. An intrinsic size uf can supply is one
        // the page does not have to be told, so it is read even on the path
        // where nothing else happens.
        let measured = dimensions(request.source, &bytes).ok();
        return passthrough(request, &bytes, measured);
    };

    let (source_width, source_height) = dimensions(request.source, &bytes)?;
    if u64::from(source_width) * u64::from(source_height) > MAX_SOURCE_PIXELS {
        return Err(ImageError::TooManyPixels {
            path: request.source.to_owned(),
            width: source_width,
            height: source_height,
        });
    }

    let decoded = image::load_from_memory_with_format(&bytes, format.into()).map_err(|source| {
        ImageError::Decode {
            path: request.source.to_owned(),
            source,
        }
    })?;

    let stem = request.source.file_stem().unwrap_or("image");
    let mut variants = Vec::new();
    let mut alternatives = Vec::new();
    let mut declined = Vec::new();
    let mut alternative_wins_everywhere = true;

    for width in target_widths(request.widths, source_width) {
        let height = scaled_height(source_width, source_height, width);
        // The intrinsic width is not resampled at all: running a Lanczos
        // kernel over an image to produce the same dimensions costs time and
        // sharpness for nothing.
        let scaled = if width == source_width {
            decoded.clone()
        } else {
            decoded.resize_exact(width, height, RESIZE_FILTER)
        };

        let fallback = encode(&scaled, format, request.quality, request.source)?;
        let alternative = encode(&scaled, Emitted::Webp, request.quality, request.source)?;

        variants.push(write_variant(
            request, stem, &bytes, &fallback, format, width, height,
        )?);
        if alternative.len() < fallback.len() {
            alternatives.push((alternative, width, height));
        } else {
            alternative_wins_everywhere = false;
            declined.push(Declined {
                format: Emitted::Webp,
                width,
                bytes: alternative.len() as u64,
                fallback_bytes: fallback.len() as u64,
            });
        }
    }

    // All the rungs or none of them.
    //
    // A `<picture>` offers each `<source>` as an equivalent rendering of the
    // whole image, and a browser that takes one is then choosing a width from
    // *that* source's `srcset` alone. A source carrying three of the five
    // widths therefore does not mean "prefer WebP where it is smaller"; it
    // means a phone that picked the WebP source has only the wide rungs left
    // to choose from, and downloads one of those instead of the narrow
    // fallback it would otherwise have taken. Offering the ladder only when it
    // is complete is what keeps the comparison the caller can see — the bytes
    // in `declined` — the same comparison the browser is making.
    if alternative_wins_everywhere && !alternatives.is_empty() {
        for (encoded, width, height) in &alternatives {
            variants.push(write_variant(
                request,
                stem,
                &bytes,
                encoded,
                Emitted::Webp,
                *width,
                *height,
            )?);
        }
    } else {
        for (encoded, width, _) in alternatives {
            let fallback_bytes = variants
                .iter()
                .find(|variant| variant.format == format && variant.width == width)
                .map_or(0, |variant| variant.bytes);
            declined.push(Declined {
                format: Emitted::Webp,
                width,
                bytes: encoded.len() as u64,
                fallback_bytes,
            });
        }
        declined.sort_by_key(|entry| entry.width);
    }

    // No placeholder behind an image that has holes in it. The placeholder is
    // painted *under* the image — that is what makes it need no element of its
    // own and cost nothing to remove — so for an opaque photograph it is
    // covered the moment the real bytes decode, and for a logo with a
    // transparent background it stays visible through it forever. A blurred
    // rectangle permanently behind a logo is a worse defect than no
    // placeholder at all, and it is the shape most transparent images are.
    let blur = if request.blur && !has_alpha(&decoded) {
        blur_placeholder(&decoded, source_width, source_height, request.source)?
    } else {
        None
    };

    Ok(ImageAsset {
        width: Some(source_width),
        height: Some(source_height),
        format,
        variants,
        blur,
        declined,
        note: None,
    })
}

/// Copy a file uf will not re-encode, and say exactly why.
///
/// Three different reasons land here and the note distinguishes them, because
/// "uf cannot do this" and "uf decided not to" are not the same answer and a
/// caller that cannot tell them apart will file the second as a bug:
///
/// * an **SVG** is already resolution independent, so resizing it is
///   meaningless and copying it is correct;
/// * a **WebP** can be decoded but not usefully re-encoded — the only WebP
///   this build can write is lossless, and a lossless re-encode of a lossy
///   source is bigger than the file the author already has — so it is measured
///   and passed through;
/// * anything else has **no decoder** compiled in.
///
/// `measured` is the intrinsic size when it could be read. Supplying it is
/// what keeps the second case from costing the page its layout reservation.
fn passthrough(
    request: &ImageRequest<'_>,
    bytes: &[u8],
    measured: Option<(u32, u32)>,
) -> Result<ImageAsset, ImageError> {
    let extension = request
        .source
        .extension()
        .unwrap_or("bin")
        .to_ascii_lowercase();
    let stem = request.source.file_stem().unwrap_or("image");
    let file = crate::name::hashed_name(stem, bytes, &[], &extension);
    let target = request.out_dir.join(&file);
    std::fs::write(&target, bytes).map_err(|source| ImageError::Write {
        path: target,
        source,
    })?;

    let mime = uf_bundle::content_type(Utf8Path::new(&file)).to_owned();

    let note = if extension == "svg" {
        String::from(
            "an SVG is resolution independent, so uf serves it as written rather than \
             rasterising it at a set of widths",
        )
    } else if measured.is_some() {
        format!(
            "uf read .{extension} but did not re-encode it: the only WebP this build can \
             write is lossless, which for an already-compressed source is larger than the \
             file you have. It was served unchanged and its intrinsic size was measured"
        )
    } else {
        format!(
            "uf has no decoder for .{extension} and served the file unchanged: it was not \
             resized, no alternative format was made, and its intrinsic size is unknown"
        )
    };

    let (width, height) = measured.unzip();
    Ok(ImageAsset {
        // `None` is not zero and not a guess. A caller that needs the
        // intrinsic size to reserve the box has to be told uf does not have
        // it, so that it can ask the author for it instead of reserving the
        // wrong box.
        width,
        height,
        format: Emitted::Original,
        variants: vec![Variant {
            file,
            width: width.unwrap_or(0),
            height: height.unwrap_or(0),
            format: Emitted::Original,
            mime,
            bytes: bytes.len() as u64,
        }],
        blur: None,
        declined: Vec::new(),
        note: Some(note),
    })
}

/// Which widths to emit, narrowest first, never wider than the source.
///
/// The source's own width is always among them, so there is a largest variant
/// even when every declared width is bigger than the image — which is the
/// common case for an icon in a project whose widths were chosen for
/// photographs.
fn target_widths(requested: &[u32], source_width: u32) -> Vec<u32> {
    let mut widths: Vec<u32> = requested
        .iter()
        .copied()
        .filter(|width| *width > 0 && *width < source_width)
        .collect();
    widths.push(source_width);
    widths.sort_unstable();
    widths.dedup();
    widths
}

/// The height that keeps the source's aspect ratio at `width`.
///
/// Rounded to nearest and never zero: a 2000x3 source at 16px wide is one pixel
/// tall, not none, and an encoder handed a zero dimension fails.
fn scaled_height(source_width: u32, source_height: u32, width: u32) -> u32 {
    if source_width == 0 {
        return source_height;
    }
    let height = (u64::from(source_height) * u64::from(width) + u64::from(source_width) / 2)
        / u64::from(source_width);
    u32::try_from(height).unwrap_or(u32::MAX).max(1)
}

/// Encode one already-scaled image.
fn encode(
    scaled: &DynamicImage,
    format: Emitted,
    quality: u8,
    source: &Utf8Path,
) -> Result<Vec<u8>, ImageError> {
    let mut out = Vec::new();
    let failed = |error: image::ImageError| ImageError::Encode {
        path: source.to_owned(),
        format: format.extension(),
        source: error,
    };
    match format {
        Emitted::Jpeg => {
            // JPEG has no alpha channel. Flattening to RGB is what the encoder
            // would do anyway; doing it here means the buffer handed over
            // matches the colour type declared with it.
            let rgb = scaled.to_rgb8();
            image::codecs::jpeg::JpegEncoder::new_with_quality(&mut out, quality.clamp(1, 100))
                .write_image(
                    rgb.as_raw(),
                    rgb.width(),
                    rgb.height(),
                    image::ExtendedColorType::Rgb8,
                )
                .map_err(failed)?;
        }
        Emitted::Png => {
            let rgba = scaled.to_rgba8();
            image::codecs::png::PngEncoder::new_with_quality(
                &mut out,
                image::codecs::png::CompressionType::Best,
                image::codecs::png::FilterType::Adaptive,
            )
            .write_image(
                rgba.as_raw(),
                rgba.width(),
                rgba.height(),
                image::ExtendedColorType::Rgba8,
            )
            .map_err(failed)?;
        }
        Emitted::Webp => {
            // Lossless is the only mode available without a C encoder, and it
            // is why the caller measures the result rather than trusting it.
            // RGB when the image has no alpha: the encoder stores a channel it
            // does not need otherwise, and on a photograph that is a quarter of
            // the file for nothing.
            if has_alpha(scaled) {
                let rgba = scaled.to_rgba8();
                image::codecs::webp::WebPEncoder::new_lossless(&mut out)
                    .write_image(
                        rgba.as_raw(),
                        rgba.width(),
                        rgba.height(),
                        image::ExtendedColorType::Rgba8,
                    )
                    .map_err(failed)?;
            } else {
                let rgb = scaled.to_rgb8();
                image::codecs::webp::WebPEncoder::new_lossless(&mut out)
                    .write_image(
                        rgb.as_raw(),
                        rgb.width(),
                        rgb.height(),
                        image::ExtendedColorType::Rgb8,
                    )
                    .map_err(failed)?;
            }
        }
        Emitted::Original => {}
    }
    Ok(out)
}

/// Whether any pixel is not fully opaque.
///
/// The colour type alone is not the answer: a PNG saved with an alpha channel
/// that is 255 everywhere is extremely common, and encoding it with alpha
/// costs a quarter of the file to say nothing.
fn has_alpha(image: &DynamicImage) -> bool {
    if !image.color().has_alpha() {
        return false;
    }
    image.to_rgba8().pixels().any(|pixel| pixel.0[3] != u8::MAX)
}

/// Write one encoded variant under its content-hashed name.
fn write_variant(
    request: &ImageRequest<'_>,
    stem: &str,
    source_bytes: &[u8],
    encoded: &[u8],
    format: Emitted,
    width: u32,
    height: u32,
) -> Result<Variant, ImageError> {
    // The digest covers the *source* bytes and the parameters, not the encoded
    // output: two builds of the same source at the same width must produce the
    // same name even if an encoder's output moves by a byte between versions,
    // or every upgrade of this crate invalidates every CDN entry a project has.
    let file = hashed_name_with_suffix(
        stem,
        source_bytes,
        &[
            &width.to_le_bytes(),
            &[request.quality],
            format.extension().as_bytes(),
        ],
        &format!("-{width}w"),
        format.extension(),
    );
    let target = request.out_dir.join(&file);
    std::fs::write(&target, encoded).map_err(|source| ImageError::Write {
        path: target,
        source,
    })?;
    Ok(Variant {
        file,
        width,
        height,
        format,
        mime: format.mime().to_owned(),
        bytes: encoded.len() as u64,
    })
}

/// The blur placeholder, as a `data:` URI.
///
/// PNG and JPEG are both encoded and the smaller wins. At sixteen pixels wide
/// neither is reliably ahead — a photograph favours JPEG, a flat graphic
/// favours PNG — and the placeholder is inlined into every document that
/// renders the image, so the difference is paid on every page load.
fn blur_placeholder(
    decoded: &DynamicImage,
    source_width: u32,
    source_height: u32,
    source: &Utf8Path,
) -> Result<Option<String>, ImageError> {
    let width = BLUR_WIDTH.min(source_width.max(1));
    let height = scaled_height(source_width, source_height, width);
    let tiny = decoded.resize_exact(width, height, RESIZE_FILTER);

    let png = encode(&tiny, Emitted::Png, 100, source)?;
    let jpeg = encode(&tiny, Emitted::Jpeg, 40, source)?;
    let (bytes, mime) = if jpeg.len() < png.len() {
        (jpeg, "image/jpeg")
    } else {
        (png, "image/png")
    };

    use base64::Engine as _;
    let encoded = base64::engine::general_purpose::STANDARD.encode(&bytes);
    Ok(Some(format!("data:{mime};base64,{encoded}")))
}

/// The format uf will decode these bytes as, if it has a decoder for them.
///
/// Decided from the bytes rather than the extension: a `.jpg` that is really a
/// PNG is common enough, and the decoder that matters is the one that can read
/// what is actually there.
fn decodable(bytes: &[u8]) -> Option<Emitted> {
    match image::guess_format(bytes).ok()? {
        image::ImageFormat::Png => Some(Emitted::Png),
        image::ImageFormat::Jpeg => Some(Emitted::Jpeg),
        // WebP decodes, but re-encoding it can only produce lossless WebP,
        // which for a lossy source is larger than what the author already had.
        // Passing it through is the smaller file and the honest one — and it
        // is still measured, which is the part that matters to the layout.
        _ => None,
    }
}

impl From<Emitted> for image::ImageFormat {
    fn from(value: Emitted) -> Self {
        match value {
            Emitted::Png | Emitted::Original => Self::Png,
            Emitted::Jpeg => Self::Jpeg,
            Emitted::Webp => Self::WebP,
        }
    }
}

/// The source's dimensions, read from its header.
fn dimensions(path: &Utf8Path, bytes: &[u8]) -> Result<(u32, u32), ImageError> {
    image::ImageReader::new(std::io::Cursor::new(bytes))
        .with_guessed_format()
        .map_err(|source| ImageError::Read {
            path: path.to_owned(),
            source,
        })?
        .into_dimensions()
        .map_err(|source| ImageError::Decode {
            path: path.to_owned(),
            source,
        })
}

/// Read an image file, refusing one larger than [`MAX_SOURCE_BYTES`].
fn read_bounded(path: &Utf8Path) -> Result<Vec<u8>, ImageError> {
    let metadata = std::fs::metadata(path).map_err(|source| ImageError::Read {
        path: path.to_owned(),
        source,
    })?;
    if metadata.len() > MAX_SOURCE_BYTES {
        return Err(ImageError::TooLarge {
            path: path.to_owned(),
            bytes: metadata.len(),
        });
    }
    std::fs::read(path).map_err(|source| ImageError::Read {
        path: path.to_owned(),
        source,
    })
}
