//! One Flow module, printed as TypeScript declarations.
//!
//! Most of a Flow type is a TypeScript type written the same way, and the
//! interesting part of this module is the list of places where it is not.
//!
//! * **`mixed` is `unknown`, `empty` is `never`** — the two languages' top and
//!   bottom types line up exactly, and `any` stays `any`.
//! * **`?T` is `T | null | undefined`.** Flow's maybe type admits both, which
//!   is the one thing a translator that wrote `T | null` would get wrong in a
//!   way nobody notices until a consumer passes `undefined`.
//! * **`+x: T` is `readonly x: T`.** Covariance on a property is exactly
//!   TypeScript's `readonly`. `-x: T` has no counterpart at all.
//! * **`+T`/`-T` on a type parameter are `out T`/`in T`**, which TypeScript
//!   has had since 4.7.
//! * **`opaque type` becomes a brand.** See [`Emitter::opaque_type`]: the
//!   nominality is the content of the declaration, and the underlying type is
//!   the one thing that must not be published.
//! * **An exact object type becomes an ordinary one.** Flow has been
//!   exact-by-default since 2023, so this is most object types in a library,
//!   and it is reported once per declaration rather than once per type.
//!
//! What has no TypeScript meaning at all becomes `unknown` and a [`Gap`]
//! naming the declaration. `unknown` rather than `any`, and the difference is
//! the point: `any` silently accepts every use of a value whose type uf could
//! not translate, while `unknown` makes the consumer acknowledge it. A gap in
//! the report and a type that refuses to be used by accident are the same
//! decision made in two places.

use compact_str::{CompactString, ToCompactString};
use uf_flow::Loc;
use uf_flow::ast::{
    self, VarianceKind, class, expression, function as fn_ast, pattern, statement, types,
};

use crate::gap::{Construct, Gap};
use crate::printer::Printer;

/// Print the declarations for one parsed Flow module.
pub(crate) fn module(
    path: &str,
    capacity: usize,
    program: &ast::Program<Loc, Loc>,
) -> (String, Vec<Gap>) {
    let mut emitter = Emitter {
        printer: Printer::new(capacity),
        gaps: Vec::new(),
        context: Vec::new(),
        reported: Vec::new(),
        anonymous: 0,
    };
    emitter.statements(&program.statements);
    emitter.finish(path)
}

/// Which declaration spaces a refused name has to occupy.
///
/// TypeScript keeps types and values apart, so a refused name has to be
/// published into the spaces Flow put it in. A `component` is a value. A Flow
/// enum is both at once — `Status` is a type in `{ status: Status }` and a
/// value in `Status.Active` — and publishing only one of the two would leave
/// the other unresolved, which is the failure this whole mechanism exists to
/// avoid.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Refused {
    /// A name used only as a value.
    Value,
    /// A name used as both, which is what a Flow enum is.
    TypeAndValue,
}

/// Where a type is being printed, for the parentheses it needs.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum Prec {
    /// A whole annotation: nothing needs wrapping.
    Any,
    /// A member of a union.
    Union,
    /// A member of an intersection.
    Intersection,
    /// The operand of `keyof`, `typeof` or `readonly`.
    Prefix,
    /// The object of `T[K]` or the element of `T[]`.
    Postfix,
}

struct Emitter {
    printer: Printer,
    gaps: Vec<Gap>,
    /// The declaration names enclosing what is being printed.
    context: Vec<CompactString>,
    /// Which constructs have already been reported for which declaration.
    reported: Vec<(CompactString, Construct)>,
    /// How many unnamed function parameters have been given a name.
    anonymous: u32,
}

/// The one-based line a location starts on.
fn line(loc: &Loc) -> u32 {
    u32::try_from(loc.start.line).unwrap_or(1).max(1)
}

impl Emitter {
    fn finish(self, path: &str) -> (String, Vec<Gap>) {
        let Self {
            mut printer, gaps, ..
        } = self;
        if printer.is_empty() {
            // A module that exports nothing still gets a file, and it has to
            // say so: an empty `.d.ts` is a script rather than a module to
            // TypeScript, and every `import` of it is then an error about the
            // file rather than about the name.
            printer.text("export {};");
        } else {
            printer
                .prepend(uf_infra::cstr!("// Generated by uf from {path}. Do not edit. ").as_str());
        }
        (printer.finish(), gaps)
    }

    /// Record a gap, at most once per declaration per construct.
    fn gap(&mut self, construct: Construct, reason: &str, at: u32) {
        let declaration = self.declaration();
        if self
            .reported
            .iter()
            .any(|(name, seen)| *seen == construct && *name == declaration)
        {
            return;
        }
        self.reported.push((declaration.clone(), construct));
        self.gaps.push(Gap {
            declaration,
            construct,
            reason: reason.to_compact_string(),
            line: at,
        });
    }

    /// The declaration being printed, for a gap's name.
    fn declaration(&self) -> CompactString {
        if self.context.is_empty() {
            return CompactString::const_new("(module)");
        }
        self.context.join(".").into()
    }

    /// Print `body` with `name` pushed onto the declaration context.
    fn within(&mut self, name: &str, body: impl FnOnce(&mut Self)) {
        self.context.push(name.to_compact_string());
        body(self);
        self.context.pop();
    }

    /// A declaration uf refused, published as a name a consumer can resolve.
    ///
    /// Leaving it out entirely was the first shape, and it is wrong in a way
    /// the report cannot make up for. A Flow enum is refused, but
    /// `{ status: Status }` two lines below still names it, and a `.d.ts`
    /// referring to a type it never declares does not give the consumer a
    /// vaguer type — it stops their build with `Cannot find name 'Status'`,
    /// in a file they did not write and cannot fix. That is the "worse than
    /// no declarations at all" outcome this crate exists to avoid.
    ///
    /// So the *name* survives as `unknown`, and only the name: useless on
    /// purpose, so nothing can be done with it by accident; reported as a
    /// gap, so the author knows; and compilable, so everything around it
    /// still works.
    fn refused(
        &mut self,
        name: &str,
        exported: bool,
        kind: Refused,
        construct: Construct,
        reason: &str,
        at: u32,
    ) {
        self.within(name, |emitter| {
            emitter.gap(construct, reason, at);
            emitter.printer.anchor(at);
            if kind == Refused::TypeAndValue {
                if exported {
                    emitter.printer.text("export ");
                }
                emitter.printer.text("type ");
                emitter.printer.text(name);
                emitter.printer.text(" = unknown;");
                emitter.printer.newline();
            }
            if exported {
                emitter.printer.text("export ");
            }
            emitter.printer.text("declare const ");
            emitter.printer.text(name);
            emitter.printer.text(": unknown;");
        });
    }

    /// A Flow enum, which is a type and a value at once.
    fn flow_enum(&mut self, name: &str, exported: bool, at: u32) {
        self.refused(
            name,
            exported,
            Refused::TypeAndValue,
            Construct::FlowEnum,
            "a Flow enum is a runtime object with `cast`, `isValid`, `members` and `getName` on \
             it, which TypeScript's own `enum` is not, so only its name is published, as \
             `unknown`",
            at,
        );
    }

    /// A Flow component, which is a value.
    fn flow_component(&mut self, name: &str, exported: bool, at: u32) {
        self.refused(
            name,
            exported,
            Refused::Value,
            Construct::ComponentType,
            "Flow's `component` syntax has no TypeScript spelling, and the props type it implies \
             depends on which `@types/react` the consumer installed, so only its name is \
             published, as `unknown`",
            at,
        );
    }

    // -- statements ---------------------------------------------------------

    fn statements(&mut self, statements: &[statement::Statement<Loc, Loc>]) {
        for item in statements {
            self.statement(item);
        }
    }

    fn statement(&mut self, item: &statement::Statement<Loc, Loc>) {
        use statement::StatementInner as S;
        let at = line(item.loc());
        match &**item {
            S::ImportDeclaration { inner, .. } => self.import(inner, at),
            S::ExportNamedDeclaration { inner, .. } => self.export_named(inner, at),
            S::ExportDefaultDeclaration { inner, .. } => self.export_default(inner, at),
            S::DeclareExportDeclaration { inner, .. } => self.declare_export(inner, at),
            S::TypeAlias { inner, .. } | S::DeclareTypeAlias { inner, .. } => {
                self.type_alias(inner, false, at);
            }
            S::OpaqueType { inner, .. } | S::DeclareOpaqueType { inner, .. } => {
                self.opaque_type(inner, false, at);
            }
            S::InterfaceDeclaration { inner, .. } | S::DeclareInterface { inner, .. } => {
                self.interface(inner, false, at);
            }
            S::ClassDeclaration { inner, .. } => self.class(inner, false, false, at),
            S::DeclareClass { inner, .. } => self.declare_class(inner, false, at),
            S::DeclareFunction { inner, .. } => self.declare_function(inner, false, at),
            S::DeclareVariable { inner, .. } => self.declare_variable(inner, false, at),
            S::EnumDeclaration { inner, .. } | S::DeclareEnum { inner, .. } => {
                let name = inner.id.name.to_compact_string();
                self.flow_enum(&name, false, at);
            }
            S::ComponentDeclaration { inner, .. } => {
                let name = inner.id.name.to_compact_string();
                self.flow_component(&name, false, at);
            }
            S::DeclareComponent { inner, .. } => {
                let name = inner.id.name.to_compact_string();
                self.flow_component(&name, false, at);
            }
            S::DeclareModule { .. }
            | S::DeclareNamespace { .. }
            | S::DeclareModuleExports { .. } => {
                self.gap(
                    Construct::AmbientModule,
                    "an ambient declaration describes a module other than this one, and a library's \
                     declaration file is only about itself",
                    at,
                );
            }
            // Everything else is a runtime statement. A declaration file has
            // no runtime, so there is nothing to say about it.
            _ => {}
        }
    }

    fn import(&mut self, import: &statement::ImportDeclaration<Loc, Loc>, at: u32) {
        let source = import.source.1.value.to_string();
        self.printer.anchor(at);
        // Every import in a declaration file is a type import in effect, but
        // the spelling is kept: `import type` where Flow wrote it, so a
        // reader comparing the two files sees the same words.
        let type_only = matches!(
            import.import_kind,
            statement::ImportKind::ImportType | statement::ImportKind::ImportTypeof
        );
        self.printer.text("import ");
        if type_only {
            self.printer.text("type ");
        }
        let mut wrote = false;
        if let Some(default) = &import.default {
            self.printer.text(&default.identifier.name);
            wrote = true;
        }
        match &import.specifiers {
            Some(statement::import_declaration::Specifier::ImportNamespaceSpecifier((_, id))) => {
                if wrote {
                    self.printer.text(", ");
                }
                self.printer.text("* as ");
                self.printer.text(&id.name);
                wrote = true;
            }
            Some(statement::import_declaration::Specifier::ImportNamedSpecifiers(named)) => {
                if wrote {
                    self.printer.text(", ");
                }
                self.printer.text("{ ");
                for (index, specifier) in named.iter().enumerate() {
                    if index > 0 {
                        self.printer.text(", ");
                    }
                    if !type_only
                        && matches!(
                            specifier.kind,
                            Some(statement::ImportKind::ImportType)
                                | Some(statement::ImportKind::ImportTypeof)
                        )
                    {
                        self.printer.text("type ");
                    }
                    self.printer.text(&specifier.remote.name);
                    if let Some(local) = &specifier.local
                        && local.name != specifier.remote.name
                    {
                        self.printer.text(" as ");
                        self.printer.text(&local.name);
                    }
                }
                self.printer.text(" }");
                wrote = true;
            }
            None => {}
        }
        if !wrote {
            // A bare `import "./side-effect.js"` has nothing to contribute to
            // a declaration file.
            self.printer.text("{} ");
        }
        self.printer.text(" from \"");
        self.printer.text(&source);
        self.printer.text("\";");
    }

    fn export_named(&mut self, export: &statement::ExportNamedDeclaration<Loc, Loc>, at: u32) {
        if let Some(declaration) = &export.declaration {
            self.exported_declaration(declaration, at);
            return;
        }
        let type_only = matches!(export.export_kind, statement::ExportKind::ExportType);
        self.printer.anchor(at);
        self.printer.text("export ");
        if type_only {
            self.printer.text("type ");
        }
        match &export.specifiers {
            Some(statement::export_named_declaration::Specifier::ExportSpecifiers(list)) => {
                self.printer.text("{ ");
                for (index, specifier) in list.iter().enumerate() {
                    if index > 0 {
                        self.printer.text(", ");
                    }
                    if !type_only
                        && matches!(specifier.export_kind, statement::ExportKind::ExportType)
                    {
                        self.printer.text("type ");
                    }
                    self.printer.text(&specifier.local.name);
                    if let Some(exported) = &specifier.exported
                        && exported.name != specifier.local.name
                    {
                        self.printer.text(" as ");
                        self.printer.text(&exported.name);
                    }
                }
                self.printer.text(" }");
            }
            Some(statement::export_named_declaration::Specifier::ExportBatchSpecifier(batch)) => {
                match &batch.specifier {
                    Some(id) => {
                        self.printer.text("* as ");
                        self.printer.text(&id.name);
                    }
                    None => self.printer.char('*'),
                }
            }
            None => self.printer.text("{}"),
        }
        if let Some((_, source)) = &export.source {
            self.printer.text(" from \"");
            self.printer.text(&source.value);
            self.printer.char('"');
        }
        self.printer.char(';');
    }

    /// A declaration that carries `export` in front of it.
    fn exported_declaration(&mut self, item: &statement::Statement<Loc, Loc>, at: u32) {
        use statement::StatementInner as S;
        match &**item {
            S::TypeAlias { inner, .. } | S::DeclareTypeAlias { inner, .. } => {
                self.type_alias(inner, true, at);
            }
            S::OpaqueType { inner, .. } | S::DeclareOpaqueType { inner, .. } => {
                self.opaque_type(inner, true, at);
            }
            S::InterfaceDeclaration { inner, .. } | S::DeclareInterface { inner, .. } => {
                self.interface(inner, true, at);
            }
            S::ClassDeclaration { inner, .. } => self.class(inner, true, false, at),
            S::DeclareClass { inner, .. } => self.declare_class(inner, true, at),
            S::FunctionDeclaration { inner, .. } => self.function_declaration(inner, true, at),
            S::DeclareFunction { inner, .. } => self.declare_function(inner, true, at),
            S::VariableDeclaration { inner, .. } => self.variable(inner, true, at),
            S::DeclareVariable { inner, .. } => self.declare_variable(inner, true, at),
            // An exported enum and an exported component are refused, and the
            // `export` has to reach them: a name published without it is one
            // the consumer cannot import, which is a second failure on top of
            // the one already being reported.
            S::EnumDeclaration { inner, .. } | S::DeclareEnum { inner, .. } => {
                let name = inner.id.name.to_compact_string();
                self.flow_enum(&name, true, at);
            }
            S::ComponentDeclaration { inner, .. } => {
                let name = inner.id.name.to_compact_string();
                self.flow_component(&name, true, at);
            }
            S::DeclareComponent { inner, .. } => {
                let name = inner.id.name.to_compact_string();
                self.flow_component(&name, true, at);
            }
            // Anything else exported is a runtime statement, which a
            // declaration file has nothing to say about.
            _ => {}
        }
    }

    fn export_default(&mut self, export: &statement::ExportDefaultDeclaration<Loc, Loc>, at: u32) {
        use statement::export_default_declaration::Declaration as D;
        match &export.declaration {
            D::Declaration(item) => match &**item {
                statement::StatementInner::FunctionDeclaration { inner, .. } => {
                    let name = inner.id.as_ref().map_or_else(
                        || CompactString::const_new("_default"),
                        |id| id.name.to_compact_string(),
                    );
                    self.within(&name, |emitter| {
                        emitter.printer.anchor(at);
                        emitter.printer.text("export default function ");
                        emitter.printer.text(&name);
                        emitter.declared_function_signature(
                            inner.tparams.as_ref(),
                            &inner.params,
                            &inner.return_,
                            at,
                            true,
                        );
                        emitter.printer.char(';');
                    });
                }
                statement::StatementInner::ClassDeclaration { inner, .. } => {
                    self.class(inner, false, true, at);
                }
                _ => self.default_value_gap(at),
            },
            D::Expression(_) => self.default_value_gap(at),
        }
    }

    /// A default export whose type Flow infers from an expression.
    fn default_value_gap(&mut self, at: u32) {
        self.within("default", |emitter| {
            emitter.gap(
                Construct::MissingAnnotation,
                "this module's default export is an expression whose type Flow infers, and a \
                 declaration file cannot infer, so it is published as `unknown`",
                at,
            );
            emitter.printer.anchor(at);
            emitter.printer.text("declare const _default: unknown;");
            emitter.printer.newline();
            emitter.printer.text("export default _default;");
        });
    }

    fn declare_export(&mut self, export: &statement::DeclareExportDeclaration<Loc, Loc>, at: u32) {
        use statement::declare_export_declaration::Declaration as D;
        let Some(declaration) = &export.declaration else {
            // `declare export { … } from "…"`, which is an ordinary
            // re-export once the `declare` is dropped.
            self.printer.anchor(at);
            self.printer.text("export ");
            match &export.specifiers {
                Some(statement::export_named_declaration::Specifier::ExportSpecifiers(list)) => {
                    self.printer.text("{ ");
                    for (index, specifier) in list.iter().enumerate() {
                        if index > 0 {
                            self.printer.text(", ");
                        }
                        self.printer.text(&specifier.local.name);
                        if let Some(exported) = &specifier.exported
                            && exported.name != specifier.local.name
                        {
                            self.printer.text(" as ");
                            self.printer.text(&exported.name);
                        }
                    }
                    self.printer.text(" }");
                }
                Some(statement::export_named_declaration::Specifier::ExportBatchSpecifier(_)) => {
                    self.printer.char('*');
                }
                None => self.printer.text("{}"),
            }
            if let Some((_, source)) = &export.source {
                self.printer.text(" from \"");
                self.printer.text(&source.value);
                self.printer.char('"');
            }
            self.printer.char(';');
            return;
        };
        match declaration {
            D::Variable { declaration, .. } => self.declare_variable(declaration, true, at),
            D::Function { declaration, .. } => self.declare_function(declaration, true, at),
            D::Class { declaration, .. } => self.declare_class(declaration, true, at),
            D::NamedType { declaration, .. } => self.type_alias(declaration, true, at),
            D::NamedOpaqueType { declaration, .. } => self.opaque_type(declaration, true, at),
            D::Interface { declaration, .. } => self.interface(declaration, true, at),
            D::Enum { declaration, .. } => {
                let name = declaration.id.name.to_compact_string();
                self.flow_enum(&name, true, at);
            }
            D::Component { declaration, .. } => {
                let name = declaration.id.name.to_compact_string();
                self.flow_component(&name, true, at);
            }
            D::DefaultType { type_ } => {
                self.within("default", |emitter| {
                    emitter.printer.anchor(at);
                    emitter.printer.text("declare const _default: ");
                    emitter.ty(type_, Prec::Any);
                    emitter.printer.char(';');
                    emitter.printer.newline();
                    emitter.printer.text("export default _default;");
                });
            }
            D::Namespace { .. } => {
                self.gap(
                    Construct::AmbientModule,
                    "an ambient declaration describes a module other than this one, and a library's \
                     declaration file is only about itself",
                    at,
                );
            }
        }
    }

    // -- declarations -------------------------------------------------------

    fn type_alias(&mut self, alias: &statement::TypeAlias<Loc, Loc>, exported: bool, at: u32) {
        let name = alias.id.name.to_compact_string();
        self.within(&name, |emitter| {
            emitter.printer.anchor(at);
            if exported {
                emitter.printer.text("export ");
            }
            emitter.printer.text("type ");
            emitter.printer.text(&name);
            emitter.type_params(alias.tparams.as_ref());
            emitter.printer.text(" = ");
            emitter.ty(&alias.right, Prec::Any);
            emitter.printer.char(';');
        });
    }

    /// An opaque type, published as a branded type.
    ///
    /// Flow's `opaque type Id = string` says two things at once: inside the
    /// file `Id` *is* a string, and outside it `Id` is a type of its own that
    /// no string can be passed as. Only the second half is any of a
    /// consumer's business, and it is the half that has to survive.
    ///
    /// Publishing `type Id = string` — which is what every other Flow-to-
    /// TypeScript tool does — publishes the first half instead, and it is not
    /// a widening but an inversion: it lets a consumer write
    /// `takesAnId("anything")`, which is the exact call Flow exists to
    /// refuse. Publishing nothing is no better, because every signature that
    /// mentions `Id` then names a type that is not declared.
    ///
    /// So the declaration is a brand: a unique symbol nobody outside this file
    /// can produce, and an object type keyed by it. A consumer can hold an
    /// `Id`, pass it back, and store it; what they cannot do is make one, which
    /// is exactly what `opaque` means from outside. A supertype bound —
    /// `opaque type Id: string = string` — is published as an intersection
    /// with that bound, because Flow really does let a consumer use it as one.
    ///
    /// It is reported all the same. A brand is an encoding rather than a
    /// translation, it is visible in the emitted file, and a reader who sees
    /// `{ readonly [Id$brand]: "Id" }` in their editor deserves to know where
    /// it came from.
    fn opaque_type(&mut self, opaque: &statement::OpaqueType<Loc, Loc>, exported: bool, at: u32) {
        let name = opaque.id.name.to_compact_string();
        self.within(&name, |emitter| {
            emitter.gap(
                Construct::OpaqueType,
                "TypeScript has no opaque type, so this is published as a branded type: a \
                 consumer can hold one and pass it back, and cannot construct one, which is what \
                 `opaque` means from outside this module",
                at,
            );
            emitter.printer.anchor(at);
            emitter.printer.text("declare const ");
            emitter.printer.text(&name);
            emitter.printer.text("$brand: unique symbol;");
            emitter.printer.newline();
            if exported {
                emitter.printer.text("export ");
            }
            emitter.printer.text("type ");
            emitter.printer.text(&name);
            emitter.type_params(opaque.tparams.as_ref());
            emitter.printer.text(" = ");
            // The bound Flow lets a consumer rely on, when there is one.
            let bound = opaque
                .upper_bound
                .as_ref()
                .or(opaque.legacy_upper_bound.as_ref());
            if let Some(bound) = bound {
                emitter.ty(bound, Prec::Intersection);
                emitter.printer.text(" & ");
            }
            emitter.printer.text("{ readonly [");
            emitter.printer.text(&name);
            emitter.printer.text("$brand]: \"");
            emitter.printer.text(&name);
            emitter.printer.text("\" };");
        });
    }

    fn interface(&mut self, interface: &statement::Interface<Loc, Loc>, exported: bool, at: u32) {
        let name = interface.id.name.to_compact_string();
        self.within(&name, |emitter| {
            emitter.printer.anchor(at);
            if exported {
                emitter.printer.text("export ");
            }
            emitter.printer.text("interface ");
            emitter.printer.text(&name);
            emitter.type_params(interface.tparams.as_ref());
            if !interface.extends.is_empty() {
                emitter.printer.text(" extends ");
                for (index, (_, parent)) in interface.extends.iter().enumerate() {
                    if index > 0 {
                        emitter.printer.text(", ");
                    }
                    emitter.generic(parent, Prec::Any);
                }
            }
            emitter.printer.char(' ');
            // An interface body is inexact in Flow as well, so there is
            // nothing to report here: the two mean the same thing.
            emitter.object_body(&interface.body.1, false);
        });
    }

    fn declare_class(
        &mut self,
        declared: &statement::DeclareClass<Loc, Loc>,
        exported: bool,
        at: u32,
    ) {
        let name = declared.id.name.to_compact_string();
        self.within(&name, |emitter| {
            emitter.printer.anchor(at);
            if exported {
                emitter.printer.text("export ");
            }
            emitter.printer.text("declare ");
            if declared.abstract_ {
                emitter.printer.text("abstract ");
            }
            emitter.printer.text("class ");
            emitter.printer.text(&name);
            emitter.type_params(declared.tparams.as_ref());
            if let Some((_, extends)) = &declared.extends {
                emitter.printer.text(" extends ");
                emitter.declare_class_extends(extends);
            }
            if let Some(implements) = &declared.implements {
                emitter.printer.text(" implements ");
                for (index, interface) in implements.interfaces.iter().enumerate() {
                    if index > 0 {
                        emitter.printer.text(", ");
                    }
                    emitter.generic_identifier(&interface.id);
                    emitter.type_args(interface.targs.as_ref());
                }
            }
            emitter.printer.char(' ');
            emitter.object_body(&declared.body.1, true);
        });
    }

    fn declare_class_extends(&mut self, extends: &statement::DeclareClassExtends<Loc, Loc>) {
        match extends {
            statement::DeclareClassExtends::ExtendsIdent(generic) => {
                self.generic(generic, Prec::Any);
            }
            statement::DeclareClassExtends::ExtendsCall { callee, .. } => {
                self.generic(&callee.1, Prec::Any);
            }
        }
    }

    fn class(&mut self, declared: &class::Class<Loc, Loc>, exported: bool, default: bool, at: u32) {
        let Some(id) = &declared.id else {
            return;
        };
        let name = id.name.to_compact_string();
        self.within(&name, |emitter| {
            emitter.printer.anchor(at);
            if default {
                emitter.printer.text("export default ");
            } else if exported {
                emitter.printer.text("export declare ");
            } else {
                emitter.printer.text("declare ");
            }
            if declared.abstract_ {
                emitter.printer.text("abstract ");
            }
            emitter.printer.text("class ");
            emitter.printer.text(&name);
            emitter.type_params(declared.tparams.as_ref());
            if let Some(extends) = &declared.extends {
                // `extends` on a class takes an expression. Only a plain name
                // survives into a declaration file — `class extends mixin(X)`
                // has a computed superclass, and a declaration file has no
                // way to call anything.
                if let Some(base) = expression_name(&extends.expr) {
                    emitter.printer.text(" extends ");
                    emitter.printer.text(&base);
                    emitter.type_args(extends.targs.as_ref());
                }
            }
            if let Some(implements) = &declared.implements {
                emitter.printer.text(" implements ");
                for (index, interface) in implements.interfaces.iter().enumerate() {
                    if index > 0 {
                        emitter.printer.text(", ");
                    }
                    emitter.generic_identifier(&interface.id);
                    emitter.type_args(interface.targs.as_ref());
                }
            }
            emitter.printer.text(" {");
            emitter.printer.indent();
            for element in declared.body.body.iter() {
                emitter.class_member(element);
            }
            emitter.printer.dedent();
            emitter.printer.newline();
            emitter.printer.char('}');
        });
    }

    fn class_member(&mut self, element: &class::BodyElement<Loc, Loc>) {
        match element {
            class::BodyElement::Method(method) => {
                let at = line(&method.loc);
                let Some(key) = self.key(&method.key, at) else {
                    return;
                };
                self.printer.anchor(at);
                if let Some(access) = &method.ts_accessibility {
                    self.printer.text(accessibility(access.kind));
                }
                if method.static_ {
                    self.printer.text("static ");
                }
                match method.kind {
                    class::MethodKind::Get => self.printer.text("get "),
                    class::MethodKind::Set => self.printer.text("set "),
                    class::MethodKind::Constructor | class::MethodKind::Method => {}
                }
                self.printer.text(&key);
                let with_return = !matches!(
                    method.kind,
                    class::MethodKind::Constructor | class::MethodKind::Set
                );
                self.declared_function_signature(
                    method.value.1.tparams.as_ref(),
                    &method.value.1.params,
                    &method.value.1.return_,
                    at,
                    with_return,
                );
                self.printer.char(';');
            }
            class::BodyElement::Property(property) => {
                let at = line(&property.loc);
                let Some(key) = self.key(&property.key, at) else {
                    return;
                };
                self.printer.anchor(at);
                if let Some(access) = &property.ts_accessibility {
                    self.printer.text(accessibility(access.kind));
                }
                if property.static_ {
                    self.printer.text("static ");
                }
                self.variance_prefix(property.variance.as_ref(), at);
                self.printer.text(&key);
                if property.optional {
                    self.printer.char('?');
                }
                self.printer.text(": ");
                self.annotation_or_hint(&property.annot, at);
                self.printer.char(';');
            }
            class::BodyElement::DeclareMethod(method) => {
                let at = line(&method.loc);
                let Some(key) = self.key(&method.key, at) else {
                    return;
                };
                self.printer.anchor(at);
                if method.static_ {
                    self.printer.text("static ");
                }
                self.printer.text(&key);
                if method.optional {
                    self.printer.char('?');
                }
                self.printer.text(": ");
                self.ty(&method.annot.annotation, Prec::Any);
                self.printer.char(';');
            }
            class::BodyElement::AbstractMethod(method) => {
                let at = line(&method.loc);
                let Some(key) = self.key(&method.key, at) else {
                    return;
                };
                self.printer.anchor(at);
                self.printer.text("abstract ");
                self.printer.text(&key);
                self.function_signature(
                    method.annot.1.tparams.as_ref(),
                    &method.annot.1.params,
                    &method.annot.1.return_,
                    at,
                );
                self.printer.char(';');
            }
            class::BodyElement::AbstractProperty(property) => {
                let at = line(&property.loc);
                let Some(key) = self.key(&property.key, at) else {
                    return;
                };
                self.printer.anchor(at);
                self.printer.text("abstract ");
                self.variance_prefix(property.variance.as_ref(), at);
                self.printer.text(&key);
                self.printer.text(": ");
                self.annotation_or_hint(&property.annot, at);
                self.printer.char(';');
            }
            class::BodyElement::IndexSignature(indexer) => {
                let at = line(&indexer.loc);
                self.indexer(indexer, at);
            }
            class::BodyElement::PrivateField(field) => {
                self.gap(
                    Construct::PrivateField,
                    "a private field is not part of what a consumer can use, so it is left out of \
                     the declarations",
                    line(&field.loc),
                );
            }
            // A static block is executable code, and a declaration file has no
            // runtime to run it in.
            class::BodyElement::StaticBlock(_) => {}
        }
    }

    fn function_declaration(
        &mut self,
        function: &ast::function::Function<Loc, Loc>,
        exported: bool,
        at: u32,
    ) {
        let Some(id) = &function.id else {
            return;
        };
        let name = id.name.to_compact_string();
        self.within(&name, |emitter| {
            emitter.printer.anchor(at);
            if exported {
                emitter.printer.text("export ");
            }
            emitter.printer.text("declare function ");
            emitter.printer.text(&name);
            emitter.declared_function_signature(
                function.tparams.as_ref(),
                &function.params,
                &function.return_,
                at,
                true,
            );
            emitter.printer.char(';');
        });
    }

    fn declare_function(
        &mut self,
        function: &statement::DeclareFunction<Loc, Loc>,
        exported: bool,
        at: u32,
    ) {
        let Some(id) = &function.id else {
            return;
        };
        let name = id.name.to_compact_string();
        self.within(&name, |emitter| {
            if function.predicate.is_some() {
                emitter.gap(
                    Construct::PredicateFunction,
                    "a `%checks` predicate says what a call proves about its argument from the \
                     function's body, which a declaration file does not have; the return type is \
                     published without it",
                    at,
                );
            }
            emitter.printer.anchor(at);
            if exported {
                emitter.printer.text("export ");
            }
            emitter.printer.text("declare function ");
            emitter.printer.text(&name);
            // `declare function f: (a: A) => B` carries its whole signature in
            // one annotation rather than in parameter position.
            match &*function.annot.annotation {
                types::TypeInner::Function { inner, .. } => {
                    emitter.function_signature(
                        inner.tparams.as_ref(),
                        &inner.params,
                        &inner.return_,
                        at,
                    );
                }
                _ => {
                    emitter.printer.text("(): ");
                    emitter.ty(&function.annot.annotation, Prec::Any);
                }
            }
            emitter.printer.char(';');
        });
    }

    fn declare_variable(
        &mut self,
        variable: &statement::DeclareVariable<Loc, Loc>,
        exported: bool,
        at: u32,
    ) {
        for declarator in variable.declarations.iter() {
            let pattern::Pattern::Identifier { inner, .. } = &declarator.id else {
                continue;
            };
            let name = inner.name.name.to_compact_string();
            self.within(&name, |emitter| {
                emitter.printer.anchor(at);
                if exported {
                    emitter.printer.text("export ");
                }
                emitter.printer.text("declare ");
                emitter.printer.text(variable.kind.as_str());
                emitter.printer.char(' ');
                emitter.printer.text(&name);
                emitter.printer.text(": ");
                emitter.annotation_or_hint(&inner.annot, at);
                emitter.printer.char(';');
            });
        }
    }

    fn variable(
        &mut self,
        variable: &statement::VariableDeclaration<Loc, Loc>,
        exported: bool,
        at: u32,
    ) {
        for declarator in variable.declarations.iter() {
            let pattern::Pattern::Identifier { inner, .. } = &declarator.id else {
                continue;
            };
            let name = inner.name.name.to_compact_string();
            self.within(&name, |emitter| {
                emitter.printer.anchor(at);
                if exported {
                    emitter.printer.text("export ");
                }
                emitter.printer.text("declare ");
                emitter.printer.text(variable.kind.as_str());
                emitter.printer.char(' ');
                emitter.printer.text(&name);
                emitter.printer.text(": ");
                emitter.annotation_or_hint(&inner.annot, at);
                emitter.printer.char(';');
            });
        }
    }

    /// A type annotation, or `unknown` and a gap when Flow inferred it.
    fn annotation_or_hint(&mut self, annot: &types::AnnotationOrHint<Loc, Loc>, at: u32) {
        match annot {
            types::AnnotationOrHint::Available(annotation) => {
                self.ty(&annotation.annotation, Prec::Any);
            }
            types::AnnotationOrHint::Missing(_) => {
                self.gap(
                    Construct::MissingAnnotation,
                    "Flow infers this binding's type from its value, and translating declarations \
                     does not run inference, so it is published as `unknown`",
                    at,
                );
                self.printer.text("unknown");
            }
        }
    }

    // -- signatures ---------------------------------------------------------

    /// The parameter list and return type of a function *type*.
    fn function_signature(
        &mut self,
        tparams: Option<&types::TypeParams<Loc, Loc>>,
        params: &types::function::Params<Loc, Loc>,
        returns: &types::function::ReturnAnnotation<Loc, Loc>,
        at: u32,
    ) {
        self.type_params(tparams);
        self.params(params, at);
        self.printer.text(": ");
        self.return_type(returns, at);
    }

    /// The same, for a declaration whose parameters are patterns.
    ///
    /// `with_return` is false for a constructor and for a setter, and it is
    /// not a nicety: TypeScript rejects a return type on either, so writing
    /// one produces a declaration file that does not compile.
    fn declared_function_signature(
        &mut self,
        tparams: Option<&types::TypeParams<Loc, Loc>>,
        params: &fn_ast::Params<Loc, Loc>,
        returns: &fn_ast::ReturnAnnot<Loc, Loc>,
        at: u32,
        with_return: bool,
    ) {
        self.type_params(tparams);
        self.printer.char('(');
        let mut first = true;
        for param in params.params.iter() {
            if !first {
                self.printer.text(", ");
            }
            first = false;
            self.declared_param(param, at);
        }
        if let Some(rest) = &params.rest {
            if !first {
                self.printer.text(", ");
            }
            self.printer.text("...");
            self.pattern_param(&rest.argument, at);
        }
        self.printer.char(')');
        if !with_return {
            return;
        }
        self.printer.text(": ");
        match returns {
            fn_ast::ReturnAnnot::Available(annotation) => {
                self.ty(&annotation.annotation, Prec::Any);
            }
            fn_ast::ReturnAnnot::TypeGuard(guard) => self.type_guard(&guard.guard, at),
            fn_ast::ReturnAnnot::Missing(_) => {
                self.gap(
                    Construct::MissingAnnotation,
                    "Flow infers this function's return type, and translating declarations does \
                     not run inference, so it is published as `unknown`",
                    at,
                );
                self.printer.text("unknown");
            }
        }
    }

    fn declared_param(&mut self, param: &fn_ast::Param<Loc, Loc>, at: u32) {
        match param {
            fn_ast::Param::RegularParam { argument, .. } => self.pattern_param(argument, at),
            fn_ast::Param::ParamProperty { property, .. } => {
                let name = self
                    .key(&property.key, at)
                    .unwrap_or_else(|| self.next_anonymous());
                self.printer.text(&name);
                self.printer.text(": ");
                self.annotation_or_hint(&property.annot, at);
            }
        }
    }

    fn pattern_param(&mut self, argument: &pattern::Pattern<Loc, Loc>, at: u32) {
        match argument {
            pattern::Pattern::Identifier { inner, .. } => {
                self.printer.text(&inner.name.name);
                if inner.optional {
                    self.printer.char('?');
                }
                self.printer.text(": ");
                self.annotation_or_hint(&inner.annot, at);
            }
            // A destructured parameter has no name a declaration can use, so
            // it gets one. The type is what a caller has to satisfy, and the
            // name is not part of the contract.
            pattern::Pattern::Object { inner, .. } => {
                let name = self.next_anonymous();
                self.printer.text(&name);
                self.printer.text(": ");
                self.annotation_or_hint(&inner.annot, at);
            }
            pattern::Pattern::Array { inner, .. } => {
                let name = self.next_anonymous();
                self.printer.text(&name);
                self.printer.text(": ");
                self.annotation_or_hint(&inner.annot, at);
            }
            pattern::Pattern::Expression { .. } => {
                let name = self.next_anonymous();
                self.printer.text(&name);
                self.printer.text(": unknown");
            }
        }
    }

    fn params(&mut self, params: &types::function::Params<Loc, Loc>, at: u32) {
        self.printer.char('(');
        let mut first = true;
        if let Some(this) = &params.this {
            self.printer.text("this: ");
            self.ty(&this.annot.annotation, Prec::Any);
            first = false;
        }
        for param in params.params.iter() {
            if !first {
                self.printer.text(", ");
            }
            first = false;
            self.param(&param.param, at);
        }
        if let Some(rest) = &params.rest {
            if !first {
                self.printer.text(", ");
            }
            self.printer.text("...");
            self.param(&rest.argument.param, at);
        }
        self.printer.char(')');
    }

    fn param(&mut self, param: &types::function::ParamKind<Loc, Loc>, at: u32) {
        match param {
            types::function::ParamKind::Labeled {
                name,
                annot,
                optional,
            } => {
                self.printer.text(&name.name);
                if *optional {
                    self.printer.char('?');
                }
                self.printer.text(": ");
                self.ty(annot, Prec::Any);
            }
            // `(string) => void` is a legal Flow type and an illegal
            // TypeScript one: every parameter in a TypeScript function type
            // has a name. The name is invented, which costs nothing — a
            // parameter's name in a type is documentation, not contract.
            types::function::ParamKind::Anonymous(annot) => {
                let name = self.next_anonymous();
                self.printer.text(&name);
                self.printer.text(": ");
                self.ty(annot, Prec::Any);
            }
            types::function::ParamKind::Destructuring(argument) => {
                self.pattern_param(argument, at);
            }
        }
    }

    fn next_anonymous(&mut self) -> CompactString {
        let name = uf_infra::into_string(uf_infra::cstr!("arg{}", self.anonymous));
        self.anonymous += 1;
        name.into()
    }

    fn return_type(&mut self, returns: &types::function::ReturnAnnotation<Loc, Loc>, at: u32) {
        match returns {
            types::function::ReturnAnnotation::Available(annotation) => {
                self.ty(&annotation.annotation, Prec::Any);
            }
            types::function::ReturnAnnotation::TypeGuard(guard) => self.type_guard(guard, at),
            types::function::ReturnAnnotation::Missing(_) => {
                self.gap(
                    Construct::MissingAnnotation,
                    "Flow infers this function's return type, and translating declarations does \
                     not run inference, so it is published as `unknown`",
                    at,
                );
                self.printer.text("unknown");
            }
        }
    }

    /// `x is T`, which TypeScript spells the same way.
    fn type_guard(&mut self, guard: &types::TypeGuard<Loc, Loc>, at: u32) {
        match guard.kind {
            types::TypeGuardKind::Default => {
                let Some(ty) = &guard.guard.1 else {
                    self.printer.text("boolean");
                    return;
                };
                self.printer.text(&guard.guard.0.name);
                self.printer.text(" is ");
                self.ty(ty, Prec::Any);
            }
            // `asserts x is T` exists in TypeScript, but Flow's `implies`
            // does not, and an assertion signature changes what a *call*
            // means rather than what it returns — translating one into the
            // other would change control flow in the consumer's code.
            types::TypeGuardKind::Asserts | types::TypeGuardKind::Implies => {
                self.gap(
                    Construct::PredicateFunction,
                    "this function's return type is a Flow assertion, which changes what a call \
                     proves rather than what it returns, so it is published as `boolean`",
                    at,
                );
                self.printer.text("boolean");
            }
        }
    }

    fn type_params(&mut self, params: Option<&types::TypeParams<Loc, Loc>>) {
        let Some(params) = params else {
            return;
        };
        if params.params.is_empty() {
            return;
        }
        self.printer.char('<');
        for (index, param) in params.params.iter().enumerate() {
            if index > 0 {
                self.printer.text(", ");
            }
            // Variance on a type parameter is `in`/`out` in TypeScript, which
            // means what `-`/`+` mean in Flow.
            if let Some(variance) = &param.variance {
                match variance.kind {
                    VarianceKind::Plus | VarianceKind::Out => self.printer.text("out "),
                    VarianceKind::Minus | VarianceKind::In => self.printer.text("in "),
                    VarianceKind::InOut => self.printer.text("in out "),
                    VarianceKind::Readonly | VarianceKind::Writeonly => {}
                }
            }
            if param.const_.is_some() {
                self.printer.text("const ");
            }
            self.printer.text(&param.name.name);
            if let types::AnnotationOrHint::Available(bound) = &param.bound {
                self.printer.text(" extends ");
                self.ty(&bound.annotation, Prec::Union);
            }
            if let Some(default) = &param.default {
                self.printer.text(" = ");
                self.ty(default, Prec::Union);
            }
        }
        self.printer.char('>');
    }

    fn type_args(&mut self, args: Option<&types::TypeArgs<Loc, Loc>>) {
        let Some(args) = args else {
            return;
        };
        if args.arguments.is_empty() {
            return;
        }
        self.printer.char('<');
        for (index, argument) in args.arguments.iter().enumerate() {
            if index > 0 {
                self.printer.text(", ");
            }
            self.ty(argument, Prec::Any);
        }
        self.printer.char('>');
    }

    // -- types --------------------------------------------------------------

    fn ty(&mut self, ty: &types::Type<Loc, Loc>, prec: Prec) {
        use types::TypeInner as T;
        let at = line(ty.loc());
        match &**ty {
            T::Any { .. } => self.printer.text("any"),
            T::Mixed { .. } => self.printer.text("unknown"),
            T::Empty { .. } => self.printer.text("never"),
            T::Void { .. } => self.printer.text("void"),
            T::Null { .. } => self.printer.text("null"),
            T::Number { .. } => self.printer.text("number"),
            T::BigInt { .. } => self.printer.text("bigint"),
            T::String { .. } => self.printer.text("string"),
            T::Boolean { .. } => self.printer.text("boolean"),
            T::Symbol { .. } => self.printer.text("symbol"),
            T::Unknown { .. } => self.printer.text("unknown"),
            T::Never { .. } => self.printer.text("never"),
            T::Undefined { .. } => self.printer.text("undefined"),
            T::UniqueSymbol { .. } => self.printer.text("unique symbol"),
            T::Exists { .. } => {
                self.gap(
                    Construct::ExistentialType,
                    "`*` asks Flow to infer a type argument, and TypeScript has nothing that asks \
                     for inference in a type position, so it is published as `unknown`",
                    at,
                );
                self.printer.text("unknown");
            }
            // Flow's maybe type admits null *and* undefined. Writing
            // `T | null` would be a translation that looks right and rejects
            // a value Flow accepts.
            T::Nullable { inner, .. } => {
                let wrap = prec > Prec::Union;
                self.open(wrap);
                self.ty(&inner.argument, Prec::Intersection);
                self.printer.text(" | null | undefined");
                self.close(wrap);
            }
            T::Function { inner, .. } => {
                let wrap = prec > Prec::Any;
                self.open(wrap);
                self.type_params(inner.tparams.as_ref());
                self.params(&inner.params, at);
                self.printer.text(" => ");
                self.return_type(&inner.return_, at);
                self.close(wrap);
            }
            T::ConstructorType {
                inner, abstract_, ..
            } => {
                let wrap = prec > Prec::Any;
                self.open(wrap);
                if *abstract_ {
                    self.printer.text("abstract ");
                }
                self.printer.text("new ");
                self.type_params(inner.tparams.as_ref());
                self.params(&inner.params, at);
                self.printer.text(" => ");
                self.return_type(&inner.return_, at);
                self.close(wrap);
            }
            T::Component { .. } => {
                self.gap(
                    Construct::ComponentType,
                    "a `component` type has no TypeScript spelling, and the props type it implies \
                     depends on which `@types/react` the consumer installed, so it is published \
                     as `unknown`",
                    at,
                );
                self.printer.text("unknown");
            }
            T::Object { inner, .. } => self.object_type(inner, at),
            T::Interface { inner, .. } => {
                // An anonymous `interface { … }` in a type position. There is
                // no anonymous interface in TypeScript; an object type means
                // the same thing, and an intersection carries the heritage.
                let wrap = prec > Prec::Intersection && !inner.extends.is_empty();
                self.open(wrap);
                for (_, parent) in inner.extends.iter() {
                    self.generic(parent, Prec::Intersection);
                    self.printer.text(" & ");
                }
                self.object_type(&inner.body.1, at);
                self.close(wrap);
            }
            T::Array { inner, .. } => {
                self.ty(&inner.argument, Prec::Postfix);
                self.printer.text("[]");
            }
            T::Conditional { inner, .. } => {
                let wrap = prec > Prec::Any;
                self.open(wrap);
                self.ty(&inner.check_type, Prec::Prefix);
                self.printer.text(" extends ");
                self.ty(&inner.extends_type, Prec::Prefix);
                self.printer.text(" ? ");
                self.ty(&inner.true_type, Prec::Any);
                self.printer.text(" : ");
                self.ty(&inner.false_type, Prec::Any);
                self.close(wrap);
            }
            T::Infer { inner, .. } => {
                self.printer.text("infer ");
                self.printer.text(&inner.tparam.name.name);
                if let types::AnnotationOrHint::Available(bound) = &inner.tparam.bound {
                    self.printer.text(" extends ");
                    self.ty(&bound.annotation, Prec::Union);
                }
            }
            T::Generic { inner, .. } => self.generic(inner, prec),
            T::IndexedAccess { inner, .. } => {
                self.ty(&inner.object, Prec::Postfix);
                self.printer.char('[');
                self.ty(&inner.index, Prec::Any);
                self.printer.char(']');
            }
            T::OptionalIndexedAccess { inner, .. } => {
                self.gap(
                    Construct::OptionalIndexedAccess,
                    "`?.[]` indexes a type that may be null, and TypeScript indexes only types \
                     that cannot be, so the result is published as `unknown`",
                    at,
                );
                let _ = inner;
                self.printer.text("unknown");
            }
            T::Union { inner, .. } => {
                let wrap = prec > Prec::Union;
                self.open(wrap);
                for (index, member) in members(&inner.types).into_iter().enumerate() {
                    if index > 0 {
                        self.printer.text(" | ");
                    }
                    self.ty(member, Prec::Intersection);
                }
                self.close(wrap);
            }
            T::Intersection { inner, .. } => {
                let wrap = prec > Prec::Intersection;
                self.open(wrap);
                for (index, member) in members(&inner.types).into_iter().enumerate() {
                    if index > 0 {
                        self.printer.text(" & ");
                    }
                    self.ty(member, Prec::Prefix);
                }
                self.close(wrap);
            }
            T::Typeof { inner, .. } => {
                let wrap = prec > Prec::Prefix;
                self.open(wrap);
                self.printer.text("typeof ");
                self.typeof_target(&inner.argument);
                self.close(wrap);
            }
            T::Keyof { inner, .. } => {
                let wrap = prec > Prec::Prefix;
                self.open(wrap);
                self.printer.text("keyof ");
                self.ty(&inner.argument, Prec::Prefix);
                self.close(wrap);
            }
            T::Renders { .. } => {
                self.gap(
                    Construct::RendersType,
                    "a `renders` type states what a component renders, which TypeScript has no \
                     way to say, so it is published as `unknown`",
                    at,
                );
                self.printer.text("unknown");
            }
            T::ReadOnly { inner, .. } => {
                let wrap = prec > Prec::Prefix;
                self.open(wrap);
                self.printer.text("readonly ");
                self.ty(&inner.argument, Prec::Prefix);
                self.close(wrap);
            }
            T::Tuple { inner, .. } => self.tuple(inner, at),
            T::StringLiteral { literal, .. } => {
                self.printer.text(&quoted(&literal.value));
            }
            T::NumberLiteral { literal, .. } => self.printer.text(&literal.raw),
            T::BigIntLiteral { literal, .. } => self.printer.text(&literal.raw),
            T::BooleanLiteral { literal, .. } => {
                self.printer
                    .text(if literal.value { "true" } else { "false" });
            }
            T::TemplateLiteral { inner, .. } => {
                self.printer.char('`');
                for (index, quasi) in inner.quasis.iter().enumerate() {
                    self.printer.text(&quasi.value.raw);
                    if let Some(interpolated) = inner.types.get(index) {
                        self.printer.text("${");
                        self.ty(interpolated, Prec::Any);
                        self.printer.char('}');
                    }
                }
                self.printer.char('`');
            }
        }
    }

    fn tuple(&mut self, tuple: &types::Tuple<Loc, Loc>, at: u32) {
        if tuple.inexact {
            self.gap(
                Construct::InexactTuple,
                "an inexact tuple accepts extra elements, and a TypeScript tuple does not, so it \
                 is published as a tuple of exactly the elements written",
                at,
            );
        }
        self.printer.char('[');
        for (index, element) in tuple.elements.iter().enumerate() {
            if index > 0 {
                self.printer.text(", ");
            }
            match element {
                types::tuple::Element::UnlabeledElement {
                    annot, optional, ..
                } => {
                    self.ty(annot, Prec::Any);
                    if *optional {
                        self.printer.char('?');
                    }
                }
                types::tuple::Element::LabeledElement { element, .. } => {
                    self.printer.text(&element.name.name);
                    if element.optional {
                        self.printer.char('?');
                    }
                    self.printer.text(": ");
                    self.ty(&element.annot, Prec::Any);
                }
                types::tuple::Element::SpreadElement { element, .. } => {
                    self.printer.text("...");
                    if let Some(name) = &element.name {
                        self.printer.text(&name.name);
                        self.printer.text(": ");
                    }
                    self.ty(&element.annot, Prec::Any);
                }
            }
        }
        self.printer.char(']');
    }

    /// An object type in a type position, as `{ … }`.
    fn object_type(&mut self, object: &types::Object<Loc, Loc>, at: u32) {
        self.report_exactness(object, at);
        let setters = setter_keys(object);
        self.printer.char('{');
        let mut wrote = false;
        for property in object.properties.iter() {
            let mark = self.printer.mark();
            if wrote {
                self.printer.char(';');
            }
            self.printer.char(' ');
            if self.object_property(property, &setters) {
                wrote = true;
            } else {
                self.printer.rewind(mark);
            }
        }
        if wrote {
            self.printer.text(" }");
        } else {
            self.printer.char('}');
        }
    }

    /// An object type as a declaration body, one member per source line.
    fn object_body(&mut self, object: &types::Object<Loc, Loc>, report: bool) {
        if report {
            self.report_exactness(object, line(&object_loc(object)));
        }
        let setters = setter_keys(object);
        self.printer.char('{');
        self.printer.indent();
        for property in object.properties.iter() {
            let at = line(&property_loc(property));
            let mark = self.printer.mark();
            self.printer.anchor(at);
            if self.object_property(property, &setters) {
                self.printer.char(';');
            } else {
                self.printer.rewind(mark);
            }
        }
        self.printer.dedent();
        self.printer.newline();
        self.printer.char('}');
    }

    /// Say that exactness was lost, unless the type said it was inexact.
    fn report_exactness(&mut self, object: &types::Object<Loc, Loc>, at: u32) {
        if object.inexact {
            return;
        }
        self.gap(
            Construct::ExactObject,
            "this is an exact object type, and TypeScript's object types are inexact: every \
             property is still declared and still checked, but a consumer passing an object with \
             an extra property will not be stopped",
            at,
        );
    }

    /// Print one member, and say whether anything was printed.
    ///
    /// The return value is what keeps the separators honest: a member that
    /// refuses to print — a spread, an internal slot, an indexer TypeScript
    /// cannot key — must not leave a `;` behind it, and `{ ; extra: boolean }`
    /// is not a type, it is a syntax error in a file the consumer did not
    /// write.
    fn object_property(
        &mut self,
        property: &types::object::Property<Loc, Loc>,
        setters: &[CompactString],
    ) -> bool {
        use types::object::Property as P;
        match property {
            P::NormalProperty(normal) => {
                let at = line(&normal.loc);
                let Some(key) = self.key(&normal.key, at) else {
                    return false;
                };
                // TypeScript has no `get`/`set` in an object type: a pair of
                // accessors is one property, and printing both would declare
                // the same name twice, which is an error rather than a wider
                // type. The getter prints it; a key with no setter is
                // `readonly`, which is what a getter alone means.
                if matches!(&normal.value, types::object::PropertyValue::Set(..))
                    && setters.contains(&key)
                {
                    return false;
                }
                if matches!(&normal.value, types::object::PropertyValue::Get(..))
                    && !setters.contains(&key)
                {
                    self.printer.text("readonly ");
                }
                self.variance_prefix(normal.variance.as_ref(), at);
                self.printer.text(&key);
                if normal.optional {
                    self.printer.char('?');
                }
                match &normal.value {
                    types::object::PropertyValue::Init(Some(ty)) => {
                        if normal.method {
                            // A method shorthand keeps its shape: `f(a: A): B`
                            // rather than `f: (a: A) => B`, which is what the
                            // source said and which TypeScript checks
                            // bivariantly, as Flow does for a method.
                            if let types::TypeInner::Function { inner, .. } = &**ty {
                                self.function_signature(
                                    inner.tparams.as_ref(),
                                    &inner.params,
                                    &inner.return_,
                                    at,
                                );
                                return true;
                            }
                        }
                        self.printer.text(": ");
                        self.ty(ty, Prec::Any);
                    }
                    types::object::PropertyValue::Init(None) => {
                        self.printer.text(": unknown");
                    }
                    types::object::PropertyValue::Get(_, function) => {
                        self.printer.text(": ");
                        self.return_type(&function.return_, at);
                    }
                    types::object::PropertyValue::Set(_, function) => {
                        self.printer.text(": ");
                        match function.params.params.first() {
                            Some(param) => match &param.param {
                                types::function::ParamKind::Labeled { annot, .. }
                                | types::function::ParamKind::Anonymous(annot) => {
                                    self.ty(annot, Prec::Any);
                                }
                                types::function::ParamKind::Destructuring(_) => {
                                    self.printer.text("unknown");
                                }
                            },
                            None => self.printer.text("unknown"),
                        }
                    }
                }
                true
            }
            P::Indexer(indexer) => self.indexer(indexer, line(&indexer.loc)),
            P::CallProperty(call) => {
                let at = line(&call.loc);
                self.function_signature(
                    call.value.1.tparams.as_ref(),
                    &call.value.1.params,
                    &call.value.1.return_,
                    at,
                );
                true
            }
            P::SpreadProperty(spread) => {
                self.gap(
                    Construct::ObjectSpread,
                    "a spread copies one object type's properties into another and lets later \
                     ones win; a TypeScript intersection keeps both types of a shared property, \
                     which is a different type, so the spread is left out",
                    line(&spread.loc),
                );
                false
            }
            P::InternalSlot(slot) => {
                self.gap(
                    Construct::InternalSlot,
                    "an internal slot is not a property a consumer can name, so it is left out of \
                     the declarations",
                    line(&slot.loc),
                );
                false
            }
            P::PrivateField(field) => {
                self.gap(
                    Construct::PrivateField,
                    "a private field is not part of what a consumer can use, so it is left out of \
                     the declarations",
                    line(&field.loc),
                );
                false
            }
            P::MappedType(mapped) => {
                self.printer.char('[');
                self.printer.text(&mapped.key_tparam.name.name);
                if let types::AnnotationOrHint::Available(bound) = &mapped.key_tparam.bound {
                    self.printer.text(" in ");
                    self.ty(&bound.annotation, Prec::Any);
                }
                if let Some(name_type) = &mapped.name_type {
                    self.printer.text(" as ");
                    self.ty(name_type, Prec::Any);
                }
                self.printer.char(']');
                match mapped.optional {
                    types::object::MappedTypeOptionalFlag::PlusOptional
                    | types::object::MappedTypeOptionalFlag::Optional => self.printer.char('?'),
                    types::object::MappedTypeOptionalFlag::MinusOptional => {
                        self.printer.text("-?");
                    }
                    types::object::MappedTypeOptionalFlag::NoOptionalFlag => {}
                }
                self.printer.text(": ");
                self.ty(&mapped.prop_type, Prec::Any);
                true
            }
        }
    }

    fn indexer(&mut self, indexer: &types::object::Indexer<Loc, Loc>, at: u32) -> bool {
        // TypeScript keys an index signature by `string`, `number`, `symbol`
        // or a template literal. Flow allows any type, and one keyed by
        // anything else has no index signature that means it.
        if !keyable(&indexer.key) {
            self.gap(
                Construct::IndexerKey,
                "TypeScript indexes only by `string`, `number` or `symbol`, so this indexer is \
                 left out and the properties it described are not declared",
                at,
            );
            return false;
        }
        self.variance_prefix(indexer.variance.as_ref(), at);
        self.printer.char('[');
        self.printer
            .text(indexer.id.as_ref().map_or("key", |id| &id.name));
        self.printer.text(": ");
        self.ty(&indexer.key, Prec::Any);
        self.printer.text("]: ");
        self.ty(&indexer.value, Prec::Any);
        true
    }

    /// `+x` is `readonly x`; `-x` has no TypeScript counterpart.
    fn variance_prefix(&mut self, variance: Option<&ast::Variance<Loc>>, at: u32) {
        let Some(variance) = variance else {
            return;
        };
        match variance.kind {
            VarianceKind::Plus | VarianceKind::Readonly => self.printer.text("readonly "),
            VarianceKind::Minus | VarianceKind::Writeonly => {
                self.gap(
                    Construct::WriteOnlyProperty,
                    "this property is write-only in Flow, and TypeScript has `readonly` and \
                     nothing on the other side, so it is published as an ordinary property a \
                     consumer may also read",
                    at,
                );
            }
            VarianceKind::In | VarianceKind::Out | VarianceKind::InOut => {}
        }
    }

    fn key(&mut self, key: &expression::object::Key<Loc, Loc>, at: u32) -> Option<CompactString> {
        match key {
            expression::object::Key::Identifier(id) => Some(id.name.to_compact_string()),
            expression::object::Key::StringLiteral((_, literal)) => {
                Some(quoted(&literal.value).into())
            }
            expression::object::Key::NumberLiteral((_, literal)) => {
                Some(literal.raw.to_compact_string())
            }
            expression::object::Key::BigIntLiteral((_, literal)) => {
                Some(literal.raw.to_compact_string())
            }
            expression::object::Key::PrivateName(_) => {
                self.gap(
                    Construct::PrivateField,
                    "a private field is not part of what a consumer can use, so it is left out of \
                     the declarations",
                    at,
                );
                None
            }
            expression::object::Key::Computed(_) => {
                self.gap(
                    Construct::InternalSlot,
                    "this member's key is computed, and a declaration file cannot evaluate an \
                     expression, so the member is left out",
                    at,
                );
                None
            }
        }
    }

    // -- named types --------------------------------------------------------

    fn generic(&mut self, generic: &types::Generic<Loc, Loc>, prec: Prec) {
        let at = line(&generic_loc(generic));
        let name = match &generic.id {
            types::generic::Identifier::Unqualified(id) => id.name.to_compact_string(),
            types::generic::Identifier::Qualified(qualified) => qualified_name(qualified),
            types::generic::Identifier::ImportTypeAnnot(_) => CompactString::const_new(""),
        };

        // A React type names something only `@types/react` declares, and
        // which of them a consumer installed is not knowable from here.
        if name.starts_with("React$") || name.starts_with("React.") || name == "React" {
            self.gap(
                Construct::ReactType,
                "this names a React type, whose TypeScript spelling depends on which \
                 `@types/react` the consumer installed, so it is published as `unknown`",
                at,
            );
            self.printer.text("unknown");
            return;
        }

        let args: Vec<&types::Type<Loc, Loc>> = generic
            .targs
            .as_ref()
            .map(|targs| targs.arguments.iter().collect())
            .unwrap_or_default();

        match (name.as_str(), args.len()) {
            ("$ReadOnly", 1) => {
                self.printer.text("Readonly<");
                self.ty(args[0], Prec::Any);
                self.printer.char('>');
            }
            ("$ReadOnlyArray", 1) => {
                let wrap = prec > Prec::Prefix;
                self.open(wrap);
                self.printer.text("readonly ");
                self.ty(args[0], Prec::Postfix);
                self.printer.text("[]");
                self.close(wrap);
            }
            ("$ReadOnlyMap", 2) => self.named("ReadonlyMap", &args),
            ("$ReadOnlySet", 1) => self.named("ReadonlySet", &args),
            ("$ReadOnlyWeakMap", 2) => self.named("WeakMap", &args),
            ("$ReadOnlyWeakSet", 1) => self.named("WeakSet", &args),
            ("$NonMaybeType", 1) => self.named("NonNullable", &args),
            ("$Keys", 1) => {
                let wrap = prec > Prec::Prefix;
                self.open(wrap);
                self.printer.text("keyof ");
                self.ty(args[0], Prec::Prefix);
                self.close(wrap);
            }
            ("$Values", 1) => {
                self.ty(args[0], Prec::Postfix);
                self.printer.text("[keyof ");
                self.ty(args[0], Prec::Prefix);
                self.printer.char(']');
            }
            ("$ElementType" | "$PropertyType", 2) => {
                self.ty(args[0], Prec::Postfix);
                self.printer.char('[');
                self.ty(args[1], Prec::Any);
                self.printer.char(']');
            }
            // `$Exact<T>` is the exactness that does not survive; the type
            // inside it does.
            ("$Exact", 1) => {
                self.gap(
                    Construct::ExactObject,
                    "`$Exact<…>` asks for an object type that rejects extra properties, which \
                     TypeScript cannot express, so the type inside it is published as written",
                    at,
                );
                self.ty(args[0], prec);
            }
            // Flow's `Object` and `Function` are its pre-`mixed` escape
            // hatches, and both really do mean `any`.
            ("Object", 0) => self.printer.text("any"),
            ("Function", 0) => self.printer.text("Function"),
            (
                "$Diff" | "$Rest" | "$Shape" | "$ObjMap" | "$ObjMapi" | "$ObjMapConst"
                | "$TupleMap" | "$Call" | "$Exports" | "$CharSet" | "$Supertype" | "$Subtype"
                | "Class",
                _,
            ) => {
                self.gap(
                    Construct::FlowUtility,
                    &uf_infra::into_string(uf_infra::cstr!(
                        "`{name}` has no TypeScript equivalent that reduces the same way, so it \
                         is published as `unknown`"
                    )),
                    at,
                );
                self.printer.text("unknown");
            }
            _ => {
                // Not a name this crate knows, which in a library's own
                // declarations usually means one of the library's own types.
                // Copied through with its arguments.
                if name.is_empty() {
                    self.printer.text("unknown");
                    return;
                }
                self.printer.text(&name);
                self.type_args(generic.targs.as_ref());
            }
        }
    }

    fn named(&mut self, name: &str, args: &[&types::Type<Loc, Loc>]) {
        self.printer.text(name);
        self.printer.char('<');
        for (index, argument) in args.iter().enumerate() {
            if index > 0 {
                self.printer.text(", ");
            }
            self.ty(argument, Prec::Any);
        }
        self.printer.char('>');
    }

    fn generic_identifier(&mut self, id: &types::generic::Identifier<Loc, Loc>) {
        match id {
            types::generic::Identifier::Unqualified(id) => self.printer.text(&id.name),
            types::generic::Identifier::Qualified(qualified) => {
                let name = qualified_name(qualified);
                self.printer.text(&name);
            }
            types::generic::Identifier::ImportTypeAnnot(_) => self.printer.text("unknown"),
        }
    }

    fn typeof_target(&mut self, target: &types::typeof_::Target<Loc, Loc>) {
        match target {
            types::typeof_::Target::Unqualified(id) => self.printer.text(&id.name),
            types::typeof_::Target::Qualified(qualified) => {
                self.typeof_target(&qualified.qualification);
                self.printer.char('.');
                self.printer.text(&qualified.id.name);
            }
            types::typeof_::Target::Import(_) => self.printer.text("unknown"),
        }
    }

    fn open(&mut self, wrap: bool) {
        if wrap {
            self.printer.char('(');
        }
    }

    fn close(&mut self, wrap: bool) {
        if wrap {
            self.printer.char(')');
        }
    }
}

/// The keys an object type declares a setter for.
///
/// Read before any member is printed, because whether a getter prints
/// `readonly` is a fact about the *other* members beside it.
fn setter_keys(object: &types::Object<Loc, Loc>) -> Vec<CompactString> {
    object
        .properties
        .iter()
        .filter_map(|property| match property {
            types::object::Property::NormalProperty(normal)
                if matches!(&normal.value, types::object::PropertyValue::Set(..)) =>
            {
                key_text(&normal.key)
            }
            _ => None,
        })
        .collect()
}

/// A member's key as it will be printed, without reporting anything.
fn key_text(key: &expression::object::Key<Loc, Loc>) -> Option<CompactString> {
    match key {
        expression::object::Key::Identifier(id) => Some(id.name.to_compact_string()),
        expression::object::Key::StringLiteral((_, literal)) => Some(quoted(&literal.value).into()),
        expression::object::Key::NumberLiteral((_, literal)) => {
            Some(literal.raw.to_compact_string())
        }
        expression::object::Key::BigIntLiteral((_, literal)) => {
            Some(literal.raw.to_compact_string())
        }
        expression::object::Key::PrivateName(_) | expression::object::Key::Computed(_) => None,
    }
}

/// The triple the port stores a union's or an intersection's members in.
///
/// Two types and a list rather than one list, because the grammar needs at
/// least two members to have a union at all. It is the first thing anyone
/// walking Flow types trips over.
type Members = (
    types::Type<Loc, Loc>,
    types::Type<Loc, Loc>,
    Vec<types::Type<Loc, Loc>>,
);

/// A union or intersection's members, flattened out of that triple.
fn members(types: &Members) -> Vec<&types::Type<Loc, Loc>> {
    let mut all = vec![&types.0, &types.1];
    all.extend(types.2.iter());
    all
}

/// The dotted name of a qualified type reference: `React.Node`.
fn qualified_name(qualified: &types::generic::Qualified<Loc, Loc>) -> CompactString {
    let mut parts: Vec<CompactString> = Vec::new();
    let mut head = &qualified.qualification;
    parts.push(qualified.id.name.to_compact_string());
    loop {
        match head {
            types::generic::Identifier::Unqualified(id) => {
                parts.push(id.name.to_compact_string());
                break;
            }
            types::generic::Identifier::Qualified(inner) => {
                parts.push(inner.id.name.to_compact_string());
                head = &inner.qualification;
            }
            types::generic::Identifier::ImportTypeAnnot(_) => break,
        }
    }
    parts.reverse();
    parts.join(".").into()
}

/// Whether TypeScript can key an index signature by this type.
fn keyable(key: &types::Type<Loc, Loc>) -> bool {
    matches!(
        &**key,
        types::TypeInner::String { .. }
            | types::TypeInner::Number { .. }
            | types::TypeInner::Symbol { .. }
            | types::TypeInner::TemplateLiteral { .. }
    )
}

/// A plain identifier a class extends, or nothing when it is computed.
fn expression_name(expression: &expression::Expression<Loc, Loc>) -> Option<CompactString> {
    match &**expression {
        expression::ExpressionInner::Identifier { inner, .. } => {
            Some(inner.name.to_compact_string())
        }
        _ => None,
    }
}

/// A TypeScript string literal for `value`.
fn quoted(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for character in value.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

/// TypeScript's spelling of a member's accessibility.
fn accessibility(kind: class::ts_accessibility::Kind) -> &'static str {
    match kind {
        class::ts_accessibility::Kind::Public => "public ",
        class::ts_accessibility::Kind::Protected => "protected ",
        class::ts_accessibility::Kind::Private => "private ",
    }
}

/// Where an object type's first property was written, for a gap's line.
fn object_loc(object: &types::Object<Loc, Loc>) -> Loc {
    object
        .properties
        .first()
        .map_or_else(synthetic_loc, property_loc)
}

fn property_loc(property: &types::object::Property<Loc, Loc>) -> Loc {
    use types::object::Property as P;
    match property {
        P::NormalProperty(it) => it.loc.clone(),
        P::SpreadProperty(it) => it.loc.clone(),
        P::Indexer(it) => it.loc.clone(),
        P::CallProperty(it) => it.loc.clone(),
        P::InternalSlot(it) => it.loc.clone(),
        P::MappedType(it) => it.loc.clone(),
        P::PrivateField(it) => it.loc.clone(),
    }
}

fn generic_loc(generic: &types::Generic<Loc, Loc>) -> Loc {
    match &generic.id {
        types::generic::Identifier::Unqualified(id) => id.loc.clone(),
        types::generic::Identifier::Qualified(qualified) => qualified.loc.clone(),
        types::generic::Identifier::ImportTypeAnnot(it) => it.loc.clone(),
    }
}

/// A location for something with none of its own: the first line.
fn synthetic_loc() -> Loc {
    Loc {
        source: None,
        start: uf_flow::Position { line: 1, column: 0 },
        end: uf_flow::Position { line: 1, column: 0 },
    }
}
