//! The literal contents of every file `uf create` writes.
//!
//! Each scaffold is one list of `(relative path, contents)` pairs, so the file
//! set a template produces can be read at a glance and changing what a new
//! project looks like never touches the code that puts it on disk. The app
//! template doubles as the crate's worked example of idiomatic `// @flow` uf
//! source.

/// The files `uf create app react` writes.
///
/// Every import here resolves to a package that is implemented, so a freshly
/// created project runs. This used to be a showcase — it imported the effect
/// library, the validator, the query client, the UI kit, Relay, StyleX and
/// React Native — and ten of those packages are declarations that throw when
/// called, so the project it produced could not start. A starter that does not
/// start teaches nothing.
pub(crate) fn app_react_files(name: &str) -> Vec<(&'static str, String)> {
    vec![
        ("package.json", app_package_json(name)),
        ("uf.config.js", app_config()),
        ("app.js", app_entry()),
        ("app/_uf.layout.js", app_layout()),
        ("app/_uf.page.js", app_page()),
        ("app/_uf.page.test.js", app_test()),
        ("app/Counter.js", app_counter()),
        ("app/useCounter.js", app_counter_hook()),
        (".gitignore", gitignore()),
    ]
}

pub(crate) fn lib_files(name: &str) -> Vec<(&'static str, String)> {
    vec![
        ("package.json", lib_package_json(name)),
        ("uf.config.js", lib_config()),
        ("index.js", lib_index()),
        ("index.test.js", lib_test()),
        (".gitignore", gitignore()),
    ]
}

/// What uf writes into a project that the project should not commit.
///
/// A scaffolded project had none, so the first `uf build` left `dist/`,
/// `router.js` and `.uf/` in `git status` and the first commit of a new
/// project carried them. Every entry here is something uf itself generates,
/// checked by running `uf create`, `uf build` and `uf test` and looking at
/// what appeared:
///
/// * `dist/` — the build output.
/// * `router.js` — the generated route types. It is Flow source and it looks
///   hand-written, which is exactly why it needs to be named: this
///   repository ignores its own `docs/router.js` for the same reason.
/// * `server-actions.js` — the generated server action types, written by
///   `uf prepare` for the same reason and with the same problem: Flow source
///   that reads as if somebody wrote it.
/// * `.uf/` — uf's own state: the build cache, the resolved config, the test
///   timings, the plans `uf prepare`, `uf publish` and `uf release` write.
/// * `.uniflowed/` — where `uf env use` records the active profile, and where
///   `uf env install` links this project's toolchain.
/// * `.env.local` and `.env.*.local` — the two files in the `.env` cascade that
///   are a developer's own rather than the project's. They are where a
///   credential goes, so a template that left them out would be a template that
///   invites committing one. The tracked `.env` and `.env.<mode>` are not
///   ignored: those are the project's defaults and belong in the repository.
/// * `node_modules/` — the package manager's.
fn gitignore() -> String {
    r#"# Generated by uf.
dist/
router.js
server-actions.js
.uf/
.uniflowed/

.env.local
.env.*.local

node_modules/
"#
    .to_string()
}

/// The version a scaffolded manifest names for every `@uniflowed/*` package:
/// the version of the uf binary that wrote the manifest.
///
/// It used to be `"latest"`, and `latest` is a dist-tag rather than a version —
/// a pointer the registry resolves at install time, to whatever it happens to
/// point at that day. On npm it did not point at the current release. With
/// `uf@0.0.0-alpha.7` out, `latest` was `0.0.0-alpha.1` on every name a
/// template writes, which is where the very first publish left it: a
/// prerelease is published on the `alpha` tag precisely so it cannot
/// displace a stable release, so nothing had moved `latest` since. The first
/// thing a new project installed was therefore five releases behind the binary
/// that scaffolded it, and not even one release of its own —
/// `@uniflowed/react` at alpha.1 beside a transitive `@uniflowed/host` at
/// alpha.2. See ubugeeei-prod/uf#408.
///
/// An exact version rather than a range, because the packages and the binary
/// are two halves of one release. uf parses the Flow, generates the router
/// types and runs the tests; the packages are what that generated code and
/// those tests import, published from this repository at this version on the
/// same tag. Pinning is what makes a project reproducible later: the manifest
/// records which uf wrote it.
///
/// A range would not narrow that to a pair, and it is wider than it reads.
/// `^0.0.0-alpha.7` expands to `>=0.0.0-alpha.7 <0.0.1-0`, which matches every
/// later `0.0.0-alpha.*` *and* `0.0.0` itself — so a project created by alpha.7
/// would install alpha.12's packages against an alpha.7 binary on the first
/// `npm install` after alpha.12 went out, which nobody ran on purpose.
/// `~0.0.0-alpha.7` is wider still. Only the bare version is one version.
///
/// This is a starting point, not a ceiling: `uf create` writes the manifest
/// once and the project owns it from then on.
const UNIFLOWED_VERSION: &str = env!("CARGO_PKG_VERSION");

fn app_package_json(name: &str) -> String {
    let uf = UNIFLOWED_VERSION;
    format!(
        r#"{{
  "name": "{name}",
  "private": true,
  "type": "module",
  "dependencies": {{
    "@uniflowed/config": "{uf}",
    "@uniflowed/react": "{uf}",
    "@uniflowed/router": "{uf}",
    "@uniflowed/vite": "{uf}",
    "react": "^19.2.0",
    "react-dom": "^19.2.0"
  }},
  "devDependencies": {{
    "@uniflowed/test": "{uf}"
  }}
}}
"#
    )
}

/// The manifest `uf create lib` writes.
///
/// It names the test runner and not the loader the runner is started with.
/// `@uniflowed/test` depends on `@uniflowed/host`, so a project that says it
/// wants to run tests gets what running them takes; naming the loader here
/// as well made every scaffolded library carry a dependency it never imports,
/// and — until the first release that sends `@uniflowed/host` — one that
/// `uf install` could not resolve at all.
///
/// Both names are pinned to `UNIFLOWED_VERSION`, for the reasons written
/// there.
///
/// # What this manifest says a Flow library ships
///
/// Two halves, named by two conditions. `uf build` writes the compiled
/// JavaScript to `dist/`, and `"default"` points at it; the Flow source stays
/// at the package root, and `"flow"` points at that. The argument is in
/// `uf_cli`'s `commands::build::library`, and three details of it are here:
///
/// * **`"default"` is the compiled build, not the source.** A resolver that
///   knows no conditions takes `default`, so `default` has to be the file
///   every runtime can evaluate. Publishing Flow source as `default` — which
///   is what the previous `"exports": { ".": "./index.js" }` did — is a
///   package that is a syntax error everywhere except inside uf. uf's own
///   `packages/*` get away with it because `@uniflowed/host`'s `isFlowModule`
///   names that scope, and a user's library does not get that deal.
/// * **`files` names `dist`, and it has to.** npm falls back to `.gitignore`
///   when a package has no `.npmignore`, and the `.gitignore` this same
///   template writes ignores `dist/`. Without this list, `npm publish` would
///   pack the source and leave out the build — a tarball whose `default`
///   condition points at a file that is not in it.
/// * **`version`, because a library is published.** The application template
///   says `"private": true`; this one is the opposite kind of project, and a
///   manifest with no version cannot be published at all.
///
/// There is no `.js.flow` and there never will be: `docs/architecture.md` says
/// a shipped module owns its own declarations, so the Flow source *is* the
/// declaration file and shipping it twice would be two answers to one
/// question.
fn lib_package_json(name: &str) -> String {
    let uf = UNIFLOWED_VERSION;
    format!(
        r#"{{
  "name": "{name}",
  "version": "0.0.0",
  "type": "module",
  "sideEffects": false,
  "exports": {{
    ".": {{
      "flow": "./index.js",
      "default": "./dist/index.js"
    }}
  }},
  "files": [
    "index.js",
    "dist"
  ],
  "devDependencies": {{
    "@uniflowed/config": "{uf}",
    "@uniflowed/test": "{uf}"
  }}
}}
"#
    )
}

fn app_config() -> String {
    r#"// @flow
import { defineConfig } from "@uniflowed/config";

export default defineConfig({
  tasks: {
    dev: { command: "uf dev" },
    build: { command: "uf build" },
    check: { command: "uf check" },
    lint: { command: "uf lint" },
    fmt: { command: "uf fmt" },
    test: { command: "uf test" },
  },
});
"#
    .to_string()
}

/// The configuration `uf create lib` writes.
///
/// `app.router.enabled: false` is the whole declaration, and it is what makes
/// `uf build` build a library rather than an application — see `uf_config`'s
/// `LibraryPlan` and ubugeeei-prod/uf#268. There is deliberately no `build.lib`
/// beside it: its defaults are exactly this project (`index.js`, ES modules,
/// every declared dependency left as an import), and a scaffold that wrote
/// them out would be teaching a reader that they are required.
///
/// There is no `dev` task either, and that is the same fact from the other
/// side: a library has no application to serve.
fn lib_config() -> String {
    r#"// @flow
import { defineConfig } from "@uniflowed/config";

export default defineConfig({
  app: {
    // Turning the file-system router off is what makes this a library:
    // `uf build` compiles index.js to dist/ rather than looking for an
    // application to render.
    router: {
      enabled: false,
    },
  },
  tasks: {
    build: { command: "uf build" },
    check: { command: "uf check" },
    lint: { command: "uf lint" },
    fmt: { command: "uf fmt" },
    test: { command: "uf test" },
  },
});
"#
    .to_string()
}

fn app_entry() -> String {
    r#"// @flow
import { routerView } from "@uniflowed/router";

export default routerView("./app");
"#
    .to_string()
}

/// The document, and nothing else.
///
/// Two things it deliberately does not do.
///
/// It wraps the page in **no `<Suspense>`**. One with `fallback={null}` around
/// every page is worse than none: a page that suspends under it renders as an
/// empty document instead of failing the way React says it should, and nothing
/// says so. That is the argument `RouteView` already makes for not inserting
/// one — `tests/library/streaming.test.js` — and a scaffold should not ship
/// the shape the router refuses. A route that wants a boundary declares one.
///
/// And `children` is **`mixed`, not `React.Node`**, which is a scaffold
/// decision rather than advice. `React.Node` comes from `@uniflowed/react`,
/// and `uf create` writes a project whose dependencies are not installed yet:
/// until `uf install` runs, that import resolves to nothing and an annotation
/// written against it is an error. `mixed` is what a document shell can say
/// with nothing installed, and an intrinsic element takes it. A project that
/// has installed its dependencies should write `React.Node`; see
/// `/guide/project`.
fn app_layout() -> String {
    r#"// @flow

export component Layout(children: mixed) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
"#
    .to_string()
}

fn app_page() -> String {
    r#"// @flow
import * as React from "@uniflowed/react";

import { Counter } from "./Counter.js";

/// The states this page can be in. An enum rather than a union of strings so
/// the `match` below is exhaustive: adding a member here stops compiling until
/// every place that reads it has been updated.
enum Mood {
  Calm,
  Sharp,
}

component Headline(mood: Mood) {
  const tone = match (mood) {
    Mood.Calm => "at native speed",
    Mood.Sharp => "without the pile of tools",
  };

  return <h1>Flow {tone}</h1>;
}

export component Page() {
  return (
    <main>
      <Headline mood={Mood.Calm} />
      <p>
        Edit <code>app/_uf.page.js</code> and this page reloads. There is no second config file to
        keep in step with this one.
      </p>
      <Counter initial={0} />
    </main>
  );
}
"#
    .to_string()
}

fn app_counter() -> String {
    r#""use client";
// @flow
import * as React from "@uniflowed/react";

import { useCounter } from "./useCounter.js";

/// A component declaration: Flow reads the parameter list as the props, so
/// there is no separate props type to keep in step with the signature.
export component Counter(initial: number) {
  const [count, increment] = useCounter(initial);

  return (
    <button type="button" onClick={increment}>
      count: {count}
    </button>
  );
}
"#
    .to_string()
}

fn app_counter_hook() -> String {
    r#""use client";
// @flow
import { useCallback, useState } from "@uniflowed/react";

/// A hook declaration. Flow refuses a call to this from anywhere that is not a
/// component or another hook, so the rules of hooks are a type error rather
/// than a lint rule you have to remember to install.
export hook useCounter(initial: number): [number, () => void] {
  const [count, setCount] = useState(initial);
  const increment = useCallback(() => setCount((value) => value + 1), []);
  return [count, increment];
}
"#
    .to_string()
}

fn app_test() -> String {
    r#"// @flow
import { describe, expect, it } from "@uniflowed/test";

import { useCounter } from "./useCounter.js";

describe("useCounter", () => {
  it("is a hook, so it is only callable from a component or another hook", () => {
    expect(typeof useCounter).toBe("function");
  });
});
"#
    .to_string()
}

fn lib_index() -> String {
    r#"// @flow
export opaque type UniflowedId = string;

export function createId(raw: string): UniflowedId {
  return raw;
}
"#
    .to_string()
}

fn lib_test() -> String {
    r#"// @flow
import { describe, expect, it } from "@uniflowed/test";
import { createId } from "./index.js";

describe("createId", () => {
  it("preserves the source value behind an opaque boundary", () => {
    expect(createId("flow")).toBe("flow");
  });
});
"#
    .to_string()
}
