[package]
name = "uniflowed_test"
description = "Native test discovery and runner core for uniflowed."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
uniflowed_infra = { path = "../uniflowed_infra" }
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true
similar-asserts.workspace = true

[[bench]]
name = "test_discovery"
harness = false
