#!/bin/sh
set -eu

if command -v wild >/dev/null 2>&1; then
  exec wild "$@"
fi

if command -v mold >/dev/null 2>&1; then
  exec mold "$@"
fi

if command -v ld.lld >/dev/null 2>&1; then
  exec ld.lld "$@"
fi

if command -v ld.gold >/dev/null 2>&1; then
  exec ld.gold "$@"
fi

exec ld "$@"
