// Generated by uf from input.js. Do not edit.

export type Exact = { id: string; size: number };

export type Inexact = { id: string };

export type Optional = { id?: string };

export type Covariant = { readonly id: string };

export type Contravariant = { sink: string };

export type Indexed = { [key: string]: number };

export type Unkeyable = {};

export type Methods = { run(input: string): number; size: number };






export type Spread = { extra: boolean };

export type Callable = { (input: string): number };
