// @noflow
//
// `../matrix.json`, read, checked, and rendered as the documentation's table.
//
// One module for all three because they are one fact seen three ways: what
// CI runs (`../run.mjs`), what CI's results must show (`../report.mjs`), and
// what the deploy guide tells a reader (`docs/app/guide/deploy/$page.mdx`,
// compared by `tests/library/deploy-matrix.test.js`). A cell's status is
// written once, in the JSON, and every one of those reads it from here.

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/** `tools/deploy-matrix/matrix.json`. */
export const MATRIX_FILE = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "matrix.json",
);

/** What a cell may say, and how the documentation says it. */
export const STATUSES = {
  verified: "Verified in CI",
  rejected: "Unsupported (rejected)",
  "not-emulated": "Not emulated",
  planned: "Planned",
};

/** The documented alternatives a check can be asked to assert; see `./checks.mjs`. */
const EXPECTATIONS = new Set(["whole", "static"]);

/** The markers around the generated table in the deploy guide. */
export const DOCS_BEGIN =
  "{/* deploy-matrix:begin — generated by `node tools/deploy-matrix/report.mjs --docs`; edit tools/deploy-matrix/matrix.json */}";
export const DOCS_END = "{/* deploy-matrix:end */}";

/**
 * Read and validate the matrix. Throws naming the first thing that is wrong,
 * because a matrix that says something the harness cannot check is a claim.
 */
export function loadMatrix(file = MATRIX_FILE) {
  const matrix = JSON.parse(readFileSync(file, "utf8"));
  const modes = new Set(matrix.modes.map((mode) => mode.id));
  const ids = new Set();
  for (const target of matrix.targets) {
    if (ids.has(target.id)) throw new Error(`matrix.json: target ${target.id} is listed twice`);
    ids.add(target.id);
    for (const [mode, cell] of Object.entries(target.cells ?? {})) {
      const where = `matrix.json: ${target.id} × ${mode}`;
      if (!modes.has(mode)) throw new Error(`${where}: no such mode`);
      if (!(cell.status in STATUSES)) throw new Error(`${where}: unknown status ${cell.status}`);
      if (cell.status === "rejected" && cell.refusal == null) {
        throw new Error(`${where}: a rejected cell names the refusal that proves it`);
      }
      if (cell.refusal != null) {
        for (const key of ["features", "config", "pattern"]) {
          if (cell.refusal[key] == null) throw new Error(`${where}: refusal has no ${key}`);
        }
      }
      if (cell.expect != null && !EXPECTATIONS.has(cell.expect)) {
        throw new Error(`${where}: unknown expect ${cell.expect}`);
      }
      if (cell.note != null && matrix.notes?.[cell.note] == null) {
        throw new Error(`${where}: note ${cell.note} is not in notes`);
      }
      if ((cell.status === "not-emulated" || cell.status === "planned") && cell.note == null) {
        throw new Error(`${where}: a ${cell.status} cell says why in a note`);
      }
    }
  }
  return matrix;
}

/**
 * Every mode's cell for `target`, in the matrix's mode order. A mode the
 * target does not mention is `verified`: the default is the claim that costs
 * the most to make, so leaving a cell out is never a way to avoid checking it.
 */
export function cellsOf(matrix, target) {
  const cells = {};
  for (const mode of matrix.modes)
    cells[mode.id] = target.cells?.[mode.id] ?? { status: "verified" };
  return cells;
}

/**
 * The deploy guide's section between [`DOCS_BEGIN`] and [`DOCS_END`]: the
 * matrix as a table with modes as rows and targets as columns, the notes a
 * cell points at, and how each target was run.
 */
export function renderDocs(matrix) {
  const noteOrder = [];
  const noteNumber = (note) => {
    if (!noteOrder.includes(note)) noteOrder.push(note);
    return noteOrder.indexOf(note) + 1;
  };
  const header = `| Mode | ${matrix.targets.map((target) => target.title).join(" | ")} |`;
  const rule = `| --- | ${matrix.targets.map(() => "---").join(" | ")} |`;
  const rows = matrix.modes.map((mode) => {
    const cells = matrix.targets.map((target) => {
      const cell = cellsOf(matrix, target)[mode.id];
      const label = STATUSES[cell.status];
      return cell.note == null ? label : `${label} [${noteNumber(cell.note)}]`;
    });
    return `| ${mode.title} | ${cells.join(" | ")} |`;
  });
  const notes = noteOrder.map((note, at) => `${at + 1}. ${matrix.notes[note]}`);
  const runtimes = [
    "| Target | Adapter | Run as |",
    "| --- | --- | --- |",
    ...matrix.targets.map(
      (target) => `| ${target.title} | \`${target.adapter}\` | ${target.runtime} |`,
    ),
  ];
  return [DOCS_BEGIN, "", header, rule, ...rows, "", ...notes, "", ...runtimes, "", DOCS_END].join(
    "\n",
  );
}

/** The generated section of `page`, or `null` when the markers are missing. */
export function docsSection(page) {
  const begin = page.indexOf(DOCS_BEGIN);
  const end = page.indexOf(DOCS_END);
  if (begin === -1 || end === -1 || end < begin) return null;
  return page.slice(begin, end + DOCS_END.length);
}
