[package]
name = "uf_runtime"
description = "Runtime contract for Capability JS Hosts, WinterTC, and deploy-anywhere targets."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
serde.workspace = true
smallvec.workspace = true
